export const JS_BRIDGE_MESSAGE_IPC_CHANNEL = 'JS_BRIDGE_MESSAGE_IPC_CHANNEL';
export const JS_BRIDGE_MESSAGE_EXT_CHANNEL = 'JS_BRIDGE_MESSAGE_EXT_CHANNEL';
export const JS_BRIDGE_MESSAGE_DIRECTION = {
  'HOST_TO_INPAGE': 'HOST_TO_INPAGE',
  'INPAGE_TO_HOST': 'INPAGE_TO_HOST',
};
