export const JS_BRIDGE_MESSAGE_IPC_CHANNEL = 'JS_BRIDGE_MESSAGE_IPC_CHANNEL';
export const JS_BRIDGE_MESSAGE_EXT_CHANNEL = 'JS_BRIDGE_MESSAGE_EXT_CHANNEL';
export const JS_BRIDGE_MESSAGE_DIRECTION = {
  'HOST_TO_INPAGE': 'HOST_TO_INPAGE',
  'INPAGE_TO_HOST': 'INPAGE_TO_HOST',
};
// TODO rename to EXT_PORT_DIRECTION
export const EXT_PORT_CS_TO_BG = 'EXT_PORT_CS_TO_BG';
export const EXT_PORT_UI_TO_BG = 'EXT_PORT_UI_TO_BG';
