import { EOneKeyDeepLinkPath } from '@onekeyhq/shared/src/consts/deeplinkConsts';
import { EQRCodeHandlerType } from '@onekeyhq/shared/types/qrCode';

import type { IFeaturedChangelogPreviewValue, IQRCodeHandler } from '../type';

/*
onekey-wallet://preview-featured-changelog?version=6.5.0

Ops-only Featured Changelog preview deeplink (QR generated by the admin
dashboard). Without this handler the generic DEEPLINK fallback wins and the
scanner UI only shows a raw Info/Copy dialog instead of opening the page.
*/
const featuredChangelogPreview: IQRCodeHandler<
  IFeaturedChangelogPreviewValue
> = async (value, options) => {
  const deeplinkValue = options?.deeplinkResult;
  if (
    deeplinkValue?.data?.hostname ===
    EOneKeyDeepLinkPath.preview_featured_changelog
  ) {
    const version = deeplinkValue.data.urlParamList?.version;
    return {
      type: EQRCodeHandlerType.FEATURED_CHANGELOG_PREVIEW,
      data: {
        version: typeof version === 'string' ? version.trim() : undefined,
      },
    };
  }
  return null;
};

export default featuredChangelogPreview;
