export const TRADING_VIEW_NATIVE_CANDLE_BODY_WIDTH = 5;
export const TRADING_VIEW_NATIVE_CANDLE_GAP = 3;
export const TRADING_VIEW_NATIVE_CANDLE_STEP =
  TRADING_VIEW_NATIVE_CANDLE_BODY_WIDTH + TRADING_VIEW_NATIVE_CANDLE_GAP;
export const TRADING_VIEW_NATIVE_CANDLE_WICK_WIDTH = 1;
export const TRADING_VIEW_NATIVE_DEFAULT_ZOOM_SCALE = 1;
export const TRADING_VIEW_NATIVE_MIN_ZOOM_SCALE = 0.5;
export const TRADING_VIEW_NATIVE_MAX_ZOOM_SCALE = 3;
export const TRADING_VIEW_NATIVE_CHART_PADDING = 24;
export const TRADING_VIEW_NATIVE_VOLUME_HEIGHT_RATIO = 0.2;
export const TRADING_VIEW_NATIVE_PRICE_VOLUME_GAP_RATIO = 0.04;
export const TRADING_VIEW_NATIVE_VOLUME_OPACITY = 0.8;
export const TRADING_VIEW_NATIVE_SWITCHING_INTERVAL_OPACITY = 0.8;
export const TRADING_VIEW_NATIVE_PRICE_AXIS_WIDTH = 80;
export const TRADING_VIEW_NATIVE_PRICE_AXIS_TICK_COUNT = 5;
export const TRADING_VIEW_NATIVE_CHART_UP_COLOR = '#30A46C';
export const TRADING_VIEW_NATIVE_CHART_DOWN_COLOR = '#E5484D';
