export const TRADING_VIEW_NATIVE_CANDLE_BODY_WIDTH = 5;
export const TRADING_VIEW_NATIVE_CANDLE_GAP = 3;
export const TRADING_VIEW_NATIVE_CANDLE_STEP =
  TRADING_VIEW_NATIVE_CANDLE_BODY_WIDTH + TRADING_VIEW_NATIVE_CANDLE_GAP;
export const TRADING_VIEW_NATIVE_CANDLE_WICK_WIDTH = 1;
export const TRADING_VIEW_NATIVE_DEFAULT_ZOOM_SCALE = 1;
export const TRADING_VIEW_NATIVE_MIN_ZOOM_SCALE = 0.5;
export const TRADING_VIEW_NATIVE_MAX_ZOOM_SCALE = 3;
