export const swapNetworksIncludeAllNetwork = [
  {
    'networkId': 'onekeyall--0',
    'name': 'All networks',
    'symbol': 'ALL NETWORKS',
    'logoURI':
      'https://uni.onekey-asset.com/static/logo/chain_selector_logo.png',
    'shortcode': 'onekeyall',
    'shortname': 'onekeyall',
    'isAllNetworks': true,
  },
  {
    'name': 'Ethereum',
    'symbol': 'ETH',
    'shortcode': 'eth',
    'shortname': 'eth',
    'logoURI': 'https://uni.onekey-asset.com/static/chain/eth.png',
    'networkId': 'evm--1',
    'defaultSelectToken': {
      'from': '0xb9d09bc374577dac1ab853de412a903408204ea8',
      'to': '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
    },
    'supportCrossChainSwap': true,
    'supportSingleSwap': true,
    'supportLimit': true,
  },
  {
    'name': 'Optimism',
    'symbol': 'ETH',
    'shortcode': 'optimism',
    'shortname': 'optimism',
    'logoURI': 'https://uni.onekey-asset.com/static/chain/optimism.png',
    'networkId': 'evm--10',
    'defaultSelectToken': {
      'from': '',
      'to': '0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85',
    },
    'supportCrossChainSwap': true,
    'supportSingleSwap': true,
    'supportLimit': false,
  },
  {
    'name': 'Avalanche',
    'symbol': 'AVAX',
    'shortcode': 'avalanche',
    'shortname': 'avalanche',
    'logoURI': 'https://uni.onekey-asset.com/static/chain/avalanche.png',
    'networkId': 'evm--43114',
    'defaultSelectToken': {
      'from': '',
      'to': '0xa7d7079b0fead91f3e65f86e8915cb59c1a4c664',
    },
    'supportCrossChainSwap': true,
    'supportSingleSwap': true,
    'supportLimit': false,
  },
  {
    'name': 'Polygon',
    'symbol': 'POL',
    'shortcode': 'polygon',
    'shortname': 'polygon',
    'logoURI': 'https://uni.onekey-asset.com/static/chain/polygon.png',
    'networkId': 'evm--137',
    'defaultSelectToken': {
      'from': '',
      'to': '0x3c499c542cef5e3811e1192ce70d8cc03d5c3359',
    },
    'supportCrossChainSwap': true,
    'supportSingleSwap': true,
    'supportLimit': false,
  },
  {
    'name': 'BNB Chain',
    'symbol': 'BNB',
    'shortcode': 'bsc',
    'shortname': 'bsc',
    'logoURI': 'https://uni.onekey-asset.com/static/chain/bsc.png',
    'networkId': 'evm--56',
    'defaultSelectToken': {
      'from': '',
      'to': '0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d',
    },
    'supportCrossChainSwap': true,
    'supportSingleSwap': true,
    'supportLimit': false,
  },
  {
    'name': 'Arbitrum',
    'symbol': 'ETH',
    'shortcode': 'arbitrum',
    'shortname': 'arbitrum',
    'logoURI': 'https://uni.onekey-asset.com/static/chain/arbitrum.png',
    'networkId': 'evm--42161',
    'defaultSelectToken': {
      'from': '',
      'to': '0xaf88d065e77c8cC2239327C5EDb3A432268e5831',
    },
    'supportCrossChainSwap': true,
    'supportSingleSwap': true,
    'supportLimit': true,
  },
  {
    'name': 'Base',
    'symbol': 'ETH',
    'shortcode': 'base',
    'shortname': 'base',
    'logoURI': 'https://uni.onekey-asset.com/static/chain/base.png',
    'networkId': 'evm--8453',
    'defaultSelectToken': {
      'from': '',
      'to': '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
    },
    'supportCrossChainSwap': true,
    'supportSingleSwap': true,
    'supportLimit': true,
  },
  {
    'name': 'Solana',
    'symbol': 'SOL',
    'shortcode': 'sol',
    'shortname': 'sol',
    'logoURI': 'https://uni.onekey-asset.com/static/chain/sol.png',
    'networkId': 'sol--101',
    'defaultSelectToken': {
      'from': '',
      'to': 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
    },
    'supportCrossChainSwap': true,
    'supportSingleSwap': true,
    'supportLimit': false,
  },
  {
    'name': 'Fantom',
    'symbol': 'FTM',
    'shortcode': 'fantom',
    'shortname': 'fantom',
    'logoURI': 'https://uni.onekey-asset.com/static/chain/fantom.png',
    'networkId': 'evm--250',
    'defaultSelectToken': {
      'from': '',
      'to': '0x04068da6c83afcfa0e13ba15a6696662335d5b75',
    },
    'supportCrossChainSwap': true,
    'supportSingleSwap': true,
    'supportLimit': false,
  },
];
