export enum ERookieTaskType {
  DEPOSIT = 'deposit',
  MARKET = 'market',
  SWAP = 'swap',
  PERPS = 'perps',
  DAPP = 'dapp',
  HYPERLIQUID_REFERRAL = 'hyperliquid_referral',
}

// Task progress: key existence indicates completion, value is timestamp
export interface IRookieGuideProgress {
  [ERookieTaskType.DEPOSIT]?: number;
  [ERookieTaskType.MARKET]?: number;
  [ERookieTaskType.SWAP]?: number;
  [ERookieTaskType.PERPS]?: number;
  [ERookieTaskType.DAPP]?: number;
  [ERookieTaskType.HYPERLIQUID_REFERRAL]?: number;
}

// Data stored in SimpleDB
export interface IRookieGuideData {
  isActivated?: boolean; // true after user opens the guide page
  progress: IRookieGuideProgress;
}

export interface IRookieGuideOneKeyIdInfo {
  isLoggedIn: boolean;
  email?: string;
  userId?: string;
}

export interface IRookieGuideInfo {
  fiatBalance: string;
  currency: string;
  oneKeyId: IRookieGuideOneKeyIdInfo;
  instanceId: string;
  taskProgress: IRookieGuideProgress;
  hyperliquidReferral?: {
    eligible: boolean;
    reason: string;
    address?: string;
  };
}

// ============ Rookie Share Types ============

// Data passed from H5 WebView for sharing.
// Note: referralCode / referralUrl are injected by the App from the
// logged-in user's primary referral code in wallet_showRookieShare; any
// values passed from H5 are ignored.
export interface IRookieShareData {
  // Content card
  imageUrl: string; // Badge/avatar image URL (required)
  title: string; // Main title (required)
  subtitle?: string; // Subtitle (optional)

  // Footer area
  footerText?: string; // Footer text, defaults to "Open source and easy to use from day one."
  referralCode?: string; // Referral code (displayed in footer). Injected by App.
  referralUrl?: string; // Referral URL (QR code / copy / X share target). Injected by App.

  // Localization
  // BCP-47 locale (e.g. "zh-TW", "en-US") used to localize the footer copy
  // generated by the App. When omitted, falls back to the current App locale.
  // When provided but unsupported, falls back to English. Title/subtitle are
  // passed verbatim from the H5 site and remain in the site's language.
  locale?: string;
}

export interface IRookieShareImageGeneratorRef {
  generate: () => Promise<string>; // Returns Base64 PNG
}
