checksumBehavior: update

enableGlobalCache: true

nodeLinker: node-modules

logFilters:
  - code: YN0013
    level: discard
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.3.1.cjs
