
// Objective-C API for talking to the following Go packages
//
//	github.com/ProtonMail/gopenpgp/v3/crypto
//	github.com/ProtonMail/gopenpgp/v3/armor
//	github.com/ProtonMail/gopenpgp/v3/constants
//	github.com/ProtonMail/gopenpgp/v3/mime
//	github.com/ProtonMail/gopenpgp/v3/mobile
//	github.com/ProtonMail/gopenpgp/v3/profile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Gopenpgp_FRAMEWORK_H__
#define __Gopenpgp_FRAMEWORK_H__

#include "Crypto.objc.h"
#include "Armor.objc.h"
#include "Constants.objc.h"
#include "Mime.objc.h"
#include "Mobile.objc.h"
#include "Profile.objc.h"
#include "Universe.objc.h"

#endif
