export const CLI_ERROR_CODES = {
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  VAULT_MISSING: 'VAULT_MISSING',
  VAULT_CORRUPT: 'VAULT_CORRUPT',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SERVICE_UNREACHABLE: 'SERVICE_UNREACHABLE',
  SERVICE_KEY_NOT_FOUND: 'SERVICE_KEY_NOT_FOUND',
  LOCK_TIMEOUT: 'LOCK_TIMEOUT',
  CLOCK_BACK_DETECTED: 'CLOCK_BACK_DETECTED',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  INVALID_TX: 'INVALID_TX',
  ADDRESS_NOT_DERIVED: 'ADDRESS_NOT_DERIVED',
  VAULT_WRITE_FAILED: 'VAULT_WRITE_FAILED',
  UNKNOWN_COMMAND: 'UNKNOWN_COMMAND',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ICliErrorCode =
  (typeof CLI_ERROR_CODES)[keyof typeof CLI_ERROR_CODES];
