export const PRIME_TRANSFER_CHUNK_SIZE = 64 * 1024;
export const PRIME_TRANSFER_MAX_PAYLOAD_SIZE = 64 * 1024 * 1024;
export const PRIME_TRANSFER_MAX_CHUNKS = Math.ceil(
  PRIME_TRANSFER_MAX_PAYLOAD_SIZE / PRIME_TRANSFER_CHUNK_SIZE,
);
