import extensionIdsConsts from './extensionIdsConsts.js';

// Chrome Web Store extensionId used by EXT_RATE_URL.chrome.
export const ONEKEY_EXTENSION_ID_CHROME_PROD =
  extensionIdsConsts.ONEKEY_EXTENSION_ID_CHROME_PROD;

// Microsoft Edge Add-ons extensionId used by EXT_RATE_URL.edge.
export const ONEKEY_EXTENSION_ID_EDGE_PROD =
  extensionIdsConsts.ONEKEY_EXTENSION_ID_EDGE_PROD;

// DEV extensionId generated by apps/ext/src/manifest/shared.js.
export const ONEKEY_EXTENSION_ID_DEV =
  extensionIdsConsts.ONEKEY_EXTENSION_ID_DEV;
