export const POLLING_INTERVAL = 15000;
export const POLLING_INTERVAL_FOR_TOTAL_VALUE = POLLING_INTERVAL;
export const POLLING_INTERVAL_FOR_TOKEN = POLLING_INTERVAL;
export const POLLING_INTERVAL_FOR_NFT = POLLING_INTERVAL;
export const POLLING_INTERVAL_FOR_HISTORY = POLLING_INTERVAL;

export const POLLING_DEBOUNCE_INTERVAL = 1000;

export const SEARCH_DEBOUNCE_INTERVAL = 500;
export const SEARCH_KEY_MIN_LENGTH = 2;

export const ENABLE_SEARCH_MIN_LENGTH = 10;
export const ENABLE_SEARCH_TOKEN_LIST_MIN_LENGTH = ENABLE_SEARCH_MIN_LENGTH;
export const ENABLE_SEARCH_NFT_LIST_MIN_LENGTH = ENABLE_SEARCH_MIN_LENGTH;
export const ENABLE_SEARCH_HISTORY_MIN_LENGTH = ENABLE_SEARCH_MIN_LENGTH;
