export const dark = {
  'background-default': '#13131B',
  'background-hovered': '#1D1D2A',
  'background-selected': '#262631',
  'surface-default': '#1E1E2A',
  'surface-subdued': '#191924',
  'surface-hovered': '#242433',
  'surface-pressed': '#2A2A3C',
  'surface-selected': '#303045',
  'surface-warning-default': '#2C2100',
  'surface-warning-subdued': '#221A00',
  'surface-critical-default': '#3C181A',
  'surface-critical-subdued': '#291415',
  'surface-critical-subdued-hovered': '#481A1D',
  'surface-success-default': '#0F291E',
  'surface-success-subdued': '#0C1F17',
  'surface-highlight-default': '#10243E',
  'surface-neutral-default': '#3D3D4D',
  'surface-neutral-subdued': '#2C2C3A',
  'surface-neutral-hovered': '#4D4D60',
  'surface-neutral-pressed': '#57576B',
  'surface-neutral-disabled': '#2C2C3A',
  'text-default': '#E2E2E8',
  'text-subdued': '#8C8CA1',
  'text-disabled': '#58586A',
  'text-critical': '#FF6369',
  'text-warning': '#F0C000',
  'text-success': '#4CC38A',
  'text-highlight': '#52A9FF',
  'text-on-primary': '#FFFFFF',
  'text-on-critical': '#FFFFFF',
  'icon-default': '#E2E2E8',
  'icon-subdued': '#8C8CA1',
  'icon-hovered': '#F4F4F7',
  'icon-pressed': '#E2E2E8',
  'icon-disabled': '#48485B',
  'icon-critical': '#E5484D',
  'icon-warning': '#F5D90A',
  'icon-success': '#30A46C',
  'icon-highlight': '#0091FF',
  'icon-on-primary': '#FFFFFF',
  'icon-on-critical': '#FFFFFF',
  'interactive-default': '#33C641',
  'interactive-hovered': '#67D572',
  'interactive-disabled': '#004206',
  'border-default': '#33334D',
  'border-subdued': '#303046',
  'border-hovered': '#383857',
  'border-disabled': '#3D3D4D',
  'border-critical-default': '#822025',
  'border-critical-subdued': '#671E22',
  'border-success-default': '#1B543A',
  'border-success-subdued': '#164430',
  'border-warning-default': '#594A05',
  'border-warning-subdued': '#493C00',
  'focused-default': '#33C641',
  'focused-critical': '#E5484D',
  'checkbox-border-disabled': '#4C4C5C',
  'action-primary-default': '#00B812',
  'action-primary-hovered': '#67D572',
  'action-primary-pressed': '#006F0B',
  'action-primary-disabled': '#343442',
  'action-primary-focus': '#00B81233',
  'action-secondary-default': '#1E1E2A',
  'action-secondary-hovered': '#242433',
  'action-secondary-pressed': '#2A2A3C',
  'action-secondary-disabled': '#262631',
  'action-critical-default': '#E5484D',
  'action-critical-hovered': '#F2555A',
  'action-critical-pressed': '#AA2429',
  'action-critical-disabled': '#343442',
  'decorative-surface-one': '#153111',
  'decorative-icon-one': '#5CC34C',
  'decorative-surface-two': '#102A4C',
  'decorative-icon-two': '#52A9FF',
  'decorative-surface-three': '#3A1E48',
  'decorative-icon-three': '#BF7AF0',
  'decorative-surface-four': '#451A37',
  'decorative-icon-four': '#E34BA9',
  'decorative-surface-five': '#481A1D',
  'decorative-icon-five': '#FF6369',
  'backdrop': 'rgba(61, 61, 77, 0.75)',
  'divider': '#2C2C3F',
};

export const light = {
  'background-default': '#FFFFFF',
  'background-hovered': '#E8E8ED',
  'background-selected': '#D4D4DD',
  'surface-default': '#FFFFFF',
  'surface-subdued': '#F6F6F9',
  'surface-hovered': '#F0F0F4',
  'surface-pressed': '#EEEEF2',
  'surface-selected': '#E6E6EF',
  'surface-warning-default': '#FFFBD1',
  'surface-warning-subdued': '#FFFCE8',
  'surface-critical-default': '#FFEFEF',
  'surface-critical-subdued': '#FFF8F8',
  'surface-critical-subdued-hovered': '#FFE5E5',
  'surface-success-default': '#E9F9EE',
  'surface-success-subdued': '#F2FCF5',
  'surface-highlight-default': '#EDF6FF',
  'surface-neutral-default': '#E8E8ED',
  'surface-neutral-subdued': '#F0F0F4',
  'surface-neutral-hovered': '#DCDCE5',
  'surface-neutral-pressed': '#D3D3DE',
  'surface-neutral-disabled': '#D4D4DD',
  'text-default': '#1F1F38',
  'text-subdued': '#737387',
  'text-disabled': '#A0A0B0',
  'text-critical': '#CD2B31',
  'text-warning': '#946800',
  'text-success': '#18794E',
  'text-highlight': '#006ADC',
  'text-on-primary': '#FFFFFF',
  'text-on-critical': '#FFFFFF',
  'icon-default': '#1F1F38',
  'icon-subdued': '#848499',
  'icon-hovered': '#383852',
  'icon-pressed': '#4B4B63',
  'icon-disabled': '#D4D4DD',
  'icon-critical': '#E5484D',
  'icon-warning': '#F5D90A',
  'icon-success': '#30A46C',
  'icon-highlight': '#0091FF',
  'icon-on-primary': '#FFFFFF',
  'icon-on-critical': '#FFFFFF',
  'interactive-default': '#00B812',
  'interactive-hovered': '#00930E',
  'interactive-disabled': '#D8F3DA',
  'border-default': '#EAECEE',
  'border-subdued': '#E6E8EA',
  'border-hovered': '#A0A0B0',
  'border-disabled': '#E8E8ED',
  'border-critical-default': '#F3AEAF',
  'border-critical-subdued': '#F9C6C6',
  'border-success-default': '#92CEAC',
  'border-success-subdued': '#B4DFC4',
  'border-warning-default': '#EFD36C',
  'border-warning-subdued': '#F9E68C',
  'focused-default': '#00B812',
  'focused-critical': '#E5484D',
  'checkbox-border-disabled': '#3D3D4D',
  'action-primary-default': '#00B812',
  'action-primary-hovered': '#00930E',
  'action-primary-pressed': '#006F0B',
  'action-primary-disabled': '#E8E8ED',
  'action-primary-focus': '#00B81233',
  'action-secondary-default': '#F6F6F8',
  'action-secondary-hovered': '#F1F1F4',
  'action-secondary-pressed': '#EBEBEF',
  'action-secondary-disabled': '#FFFFFF',
  'action-critical-default': '#E5484D',
  'action-critical-hovered': '#DC3D43',
  'action-critical-pressed': '#EB9091',
  'action-critical-disabled': '#E8E8ED',
  'decorative-surface-one': '#E0F3DD',
  'decorative-icon-one': '#257918',
  'decorative-surface-two': '#E1F0FF',
  'decorative-icon-two': '#006ADC',
  'decorative-surface-three': '#F3E7FC',
  'decorative-icon-three': '#793AAF',
  'decorative-surface-four': '#FCE5F3',
  'decorative-icon-four': '#CD1D8D',
  'decorative-surface-five': '#FFE5E5',
  'decorative-icon-five': '#CD2B31',
  'backdrop': 'rgba(107, 107, 128, 0.75)',
  'divider': '#F3F3F6',
};

const theme = {
  light,
  dark,
} as const;

export type ThemeVariant = keyof typeof theme;
export type ThemeValues = typeof theme[ThemeVariant];
export type ThemeToken = keyof ThemeValues;

export default theme;
