export const dark = {
  'background-default': '#13131B',
  'background-hovered': '#1D1D2A',
  'background-selected': '#262631',
  'surface-default': '#262631',
  'surface-subdued': '#1D1D2A',
  'surface-hovered': '#2C2C3A',
  'surface-selected': '#3D3D4D',
  'surface-warning-default': '#6B5600',
  'surface-warning-subdued': '#4D3E00',
  'surface-critical-default': '#6B1914',
  'surface-critical-subdued': '#49110E',
  'surface-critical-subdued-hovered': '#6B1914',
  'surface-success-default': '#195F2B',
  'surface-success-subdued': '#103D1B',
  'surface-highlight-default': '#00336B',
  'surface-neutral-default': '#3D3D4D',
  'surface-neutral-subdued': '#2C2C3A',
  'surface-neutral-hovered': '#58586A',
  'surface-neutral-disabled': '#2C2C3A',
  'text-default': '#E2E2E8',
  'text-subdued': '#8C8CA1',
  'text-disabled': '#58586A',
  'text-critical': '#FF6259',
  'text-warning': '#CCA300',
  'text-success': '#34C759',
  'text-on-primary': '#FFFFFF',
  'text-on-critical': '#FFFFFF',
  'icon-default': '#8C8CA1',
  'icon-subdued': '#636378',
  'icon-hovered': '#F4F4F7',
  'icon-pressed': '#E2E2E8',
  'icon-disabled': '#48485B',
  'icon-critical': '#FF6259',
  'icon-warning': '#FFD633',
  'icon-success': '#5DD27A',
  'icon-on-primary': '#FFFFFF',
  'icon-on-critical': '#FFFFFF',
  'interactive-default': '#33C641',
  'interactive-hovered': '#67D572',
  'interactive-disabled': '#004206',
  'border-default': '#4C4C5C',
  'border-subdued': '#3D3D4D',
  'border-hovered': '#8C8CA1',
  'border-disabled': '#3D3D4D',
  'border-critical-default': '#CC2F26',
  'border-critical-subdued': '#7A1C17',
  'border-success-subdued': '#165526',
  'border-warning-subdued': '#165526',
  'focused-default': '#33C641',
  'focused-critical': '#FF6259',
  'checkbox-border-disabled': '#4C4C5C',
  'action-primary-default': '#00B812',
  'action-primary-hovered': '#67D572',
  'action-primary-pressed': '#006F0B',
  'action-primary-disabled': '#343442',
  'action-primary-focus': '#00B81233',
  'action-primary-activate-disabled': '#004206',
  'action-secondary-default': '#262631',
  'action-secondary-hovered': '#3D3D4D',
  'action-secondary-pressed': '#1D1D2A',
  'action-secondary-disabled': '#1D1D2A',
  'action-critical-default': '#CC2F26',
  'action-critical-hovered': '#FF3B30',
  'action-critical-pressed': '#9A241D',
  'action-critical-disabled': '#343442',
  'decorative-surface-one': '#005809',
  'decorative-icon-one': '#33C641',
  'backdrop': 'rgba(61, 61, 77, 0.75)',
  'divider': '#343442',
};

export const light = {
  'background-default': '#F3F3F6',
  'background-hovered': '#E8E8ED',
  'background-selected': '#D4D4DD',
  'surface-default': '#FFFFFF',
  'surface-subdued': '#F9F9FB',
  'surface-hovered': '#F3F3F6',
  'surface-selected': '#E8E8ED',
  'surface-warning-default': '#FFEDA3',
  'surface-warning-subdued': '#FFFBEB',
  'surface-critical-default': '#FFB8B4',
  'surface-critical-subdued': '#FFF0EF',
  'surface-critical-subdued-hovered': '#FFE0DF',
  'surface-success-default': '#B6EBC3',
  'surface-success-subdued': '#EBF9EC',
  'surface-highlight-default': '#BDDCFF',
  'surface-neutral-default': '#E8E8ED',
  'surface-neutral-subdued': '#F9F9FB',
  'surface-neutral-hovered': '#D4D4DD',
  'surface-neutral-disabled': '#D4D4DD',
  'text-default': '#1F1F38',
  'text-subdued': '#6B6B80',
  'text-disabled': '#A0A0B0',
  'text-critical': '#CC2F26',
  'text-warning': '#886E07',
  'text-success': '#1F7836',
  'text-on-primary': '#FFFFFF',
  'text-on-critical': '#FFFFFF',
  'icon-default': '#6B6B80',
  'icon-subdued': '#A0A0B0',
  'icon-hovered': '#383852',
  'icon-pressed': '#4B4B63',
  'icon-disabled': '#D4D4DD',
  'icon-critical': '#FF3B30',
  'icon-warning': '#FFCC00',
  'icon-success': '#34C759',
  'icon-on-primary': '#FFFFFF',
  'icon-on-critical': '#FFFFFF',
  'interactive-default': '#00B812',
  'interactive-hovered': '#00930E',
  'interactive-disabled': '#EBF9EC',
  'border-default': '#D4D4DD',
  'border-subdued': '#E8E8ED',
  'border-hovered': '#A0A0B0',
  'border-disabled': '#E8E8ED',
  'border-critical-default': '#FF8A84',
  'border-critical-subdued': '#FFB8B4',
  'border-success-subdued': '#A3E5A9',
  'border-warning-subdued': '#A3E5A9',
  'focused-default': '#00B812',
  'focused-critical': '#FF3B30',
  'checkbox-border-disabled': '#3D3D4D',
  'action-primary-default': '#00B812',
  'action-primary-hovered': '#00930E',
  'action-primary-pressed': '#006F0B',
  'action-primary-disabled': '#E8E8ED',
  'action-primary-focus': '#00B81233',
  'action-primary-activate-disabled': '#004206',
  'action-secondary-default': '#FFFFFF',
  'action-secondary-hovered': '#F3F3F6',
  'action-secondary-pressed': '#E8E8ED',
  'action-secondary-disabled': '#F3F3F6',
  'action-critical-default': '#FF3B30',
  'action-critical-hovered': '#CC2F26',
  'action-critical-pressed': '#9A241D',
  'action-critical-disabled': '#E8E8ED',
  'decorative-surface-one': '#005809',
  'decorative-icon-one': '#33C641',
  'backdrop': 'rgba(107, 107, 128, 0.75)',
  'divider': '#F3F3F6',
};

const theme = {
  light,
  dark,
} as const;

export type ThemeVariant = keyof typeof theme;
export type ThemeValues = typeof theme[ThemeVariant];

const DEFAULT_THEME_VARIANT = 'dark';

export const getDefaultTheme = (initial?: string): ThemeVariant => {
  if (Object.keys(theme).includes(initial ?? '')) {
    return initial as ThemeVariant;
  }

  // TODO: 系统主题判断 & 缓存判断
  return DEFAULT_THEME_VARIANT;
};

export default theme;
