export const dark = {
  'background-default': '#13131B',
  'background-hovered': '#1D1D2A',
  'background-selected': '#262631',
  'surface-default': '#1E1E2A',
  'surface-subdued': '#191924',
  'surface-hovered': '#242433',
  'surface-pressed': '#2A2A3C',
  'surface-selected': '#303045',
  'surface-warning-default': '#6B5600',
  'surface-warning-subdued': '#4D3E00',
  'surface-critical-default': '#6B1914',
  'surface-critical-subdued': '#49110E',
  'surface-critical-subdued-hovered': '#6B1914',
  'surface-success-default': '#195F2B',
  'surface-success-subdued': '#103D1B',
  'surface-highlight-default': '#00336B',
  'surface-neutral-default': '#3D3D4D',
  'surface-neutral-subdued': '#2C2C3A',
  'surface-neutral-hovered': '#4D4D60',
  'surface-neutral-pressed': '#57576B',
  'surface-neutral-disabled': '#2C2C3A',
  'text-default': '#E2E2E8',
  'text-subdued': '#8C8CA1',
  'text-disabled': '#58586A',
  'text-critical': '#FF6259',
  'text-warning': '#CCA300',
  'text-success': '#34C759',
  'text-highlight': '#67B0FF',
  'text-on-primary': '#FFFFFF',
  'text-on-critical': '#FFFFFF',
  'icon-default': '#E2E2E8',
  'icon-subdued': '#8C8CA1',
  'icon-hovered': '#F4F4F7',
  'icon-pressed': '#E2E2E8',
  'icon-disabled': '#48485B',
  'icon-critical': '#FF6259',
  'icon-warning': '#FFD633',
  'icon-success': '#5DD27A',
  'icon-highlight': '#67B0FF',
  'icon-on-primary': '#FFFFFF',
  'icon-on-critical': '#FFFFFF',
  'interactive-default': '#33C641',
  'interactive-hovered': '#67D572',
  'interactive-disabled': '#004206',
  'border-default': '#33334D',
  'border-subdued': '#303046',
  'border-hovered': '#383857',
  'border-disabled': '#3D3D4D',
  'border-critical-default': '#CC2F26',
  'border-critical-subdued': '#7A1C17',
  'border-success-subdued': '#165526',
  'border-warning-subdued': '#7A6200',
  'focused-default': '#33C641',
  'focused-critical': '#FF6259',
  'checkbox-border-disabled': '#4C4C5C',
  'action-primary-default': '#00B812',
  'action-primary-hovered': '#67D572',
  'action-primary-pressed': '#006F0B',
  'action-primary-disabled': '#343442',
  'action-primary-focus': '#00B81233',
  'action-secondary-default': '#262631',
  'action-secondary-hovered': '#363645',
  'action-secondary-pressed': '#3D3D4D',
  'action-secondary-disabled': '#262631',
  'action-critical-default': '#CC2F26',
  'action-critical-hovered': '#FF3B30',
  'action-critical-pressed': '#9A241D',
  'action-critical-disabled': '#343442',
  'decorative-surface-one': '#153111',
  'decorative-icon-one': '#5CC34C',
  'decorative-surface-two': '#102A4C',
  'decorative-icon-two': '#52A9FF',
  'decorative-surface-three': '#3A1E48',
  'decorative-icon-three': '#BF7AF0',
  'decorative-surface-four': '#451A37',
  'decorative-icon-four': '#E34BA9',
  'decorative-surface-five': '#481A1D',
  'decorative-icon-five': '#FF6369',
  'backdrop': 'rgba(61, 61, 77, 0.75)',
  'divider': '#2C2C3F',
};

export const light = {
  'background-default': '#FFFFFF',
  'background-hovered': '#E8E8ED',
  'background-selected': '#D4D4DD',
  'surface-default': '#FFFFFF',
  'surface-subdued': '#F6F6F9',
  'surface-hovered': '#F0F0F4',
  'surface-pressed': '#EEEEF2',
  'surface-selected': '#E6E6EF',
  'surface-warning-default': '#FFF1B8',
  'surface-warning-subdued': '#FFFBEB',
  'surface-critical-default': '#FFB8B4',
  'surface-critical-subdued': '#FFF0EF',
  'surface-critical-subdued-hovered': '#FFE0DF',
  'surface-success-default': '#B6EBC3',
  'surface-success-subdued': '#EBF9EC',
  'surface-highlight-default': '#BDDCFF',
  'surface-neutral-default': '#E8E8ED',
  'surface-neutral-subdued': '#F0F0F4',
  'surface-neutral-hovered': '#DCDCE5',
  'surface-neutral-pressed': '#D3D3DE',
  'surface-neutral-disabled': '#D4D4DD',
  'text-default': '#1F1F38',
  'text-subdued': '#737387',
  'text-disabled': '#A0A0B0',
  'text-critical': '#CC2F26',
  'text-warning': '#C7A10A',
  'text-success': '#1F7836',
  'text-highlight': '#007AFF',
  'text-on-primary': '#FFFFFF',
  'text-on-critical': '#FFFFFF',
  'icon-default': '#1F1F38',
  'icon-subdued': '#848499',
  'icon-hovered': '#383852',
  'icon-pressed': '#4B4B63',
  'icon-disabled': '#D4D4DD',
  'icon-critical': '#FF3B30',
  'icon-warning': '#F0C000',
  'icon-success': '#34C759',
  'icon-highlight': '#007AFF',
  'icon-on-primary': '#FFFFFF',
  'icon-on-critical': '#FFFFFF',
  'interactive-default': '#00B812',
  'interactive-hovered': '#00930E',
  'interactive-disabled': '#D8F3DA',
  'border-default': '#EAECEE',
  'border-subdued': '#E6E8EA',
  'border-hovered': '#A0A0B0',
  'border-disabled': '#E8E8ED',
  'border-critical-default': '#FF8A84',
  'border-critical-subdued': '#FFB8B4',
  'border-success-subdued': '#A3E5A9',
  'border-warning-subdued': '#FFE167',
  'focused-default': '#00B812',
  'focused-critical': '#FF3B30',
  'checkbox-border-disabled': '#3D3D4D',
  'action-primary-default': '#00B812',
  'action-primary-hovered': '#00930E',
  'action-primary-pressed': '#006F0B',
  'action-primary-disabled': '#E8E8ED',
  'action-primary-focus': '#00B81233',
  'action-secondary-default': '#F6F6F8',
  'action-secondary-hovered': '#F1F1F4',
  'action-secondary-pressed': '#EBEBEF',
  'action-secondary-disabled': '#FFFFFF',
  'action-critical-default': '#FF3B30',
  'action-critical-hovered': '#CC2F26',
  'action-critical-pressed': '#9A241D',
  'action-critical-disabled': '#E8E8ED',
  'decorative-surface-one': '#E0F3DD',
  'decorative-icon-one': '#257918',
  'decorative-surface-two': '#E1F0FF',
  'decorative-icon-two': '#006ADC',
  'decorative-surface-three': '#F3E7FC',
  'decorative-icon-three': '#793AAF',
  'decorative-surface-four': '#FCE5F3',
  'decorative-icon-four': '#CD1D8D',
  'decorative-surface-five': '#FFE5E5',
  'decorative-icon-five': '#CD2B31',
  'backdrop': 'rgba(107, 107, 128, 0.75)',
  'divider': '#F3F3F6',
};

const theme = {
  light,
  dark,
} as const;

export type ThemeVariant = keyof typeof theme;
export type ThemeValues = typeof theme[ThemeVariant];
export type ThemeToken = keyof ThemeValues;

export default theme;
