require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

# react-native-permissions
require File.join(File.dirname(`node --print "require.resolve('react-native-permissions/package.json')"`), "scripts/setup")


require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = '1'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.5'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

# react-native-permissions
setup_permissions([
  # 'AppTrackingTransparency',
  'Bluetooth',
  # 'Calendars',
  # 'CalendarsWriteOnly',
  # 'Camera',
  # 'Contacts',
  # 'FaceID',
  # 'LocationAccuracy',
  # 'LocationAlways',
  # 'LocationWhenInUse',
  # 'MediaLibrary',
  # 'Microphone',
  # 'Motion',
  # 'Notifications',
  # 'PhotoLibrary',
  # 'PhotoLibraryAddOnly',
  # 'Reminders',
  # 'Siri',
  # 'SpeechRecognition',
  # 'StoreKit',
])

target 'OneKeyWallet' do
  use_expo_modules!
  config = use_native_modules!

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']
  use_frameworks! :linkage => :static

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
    installer.pods_project.targets.each do |target|
      # https://github.com/mockingbot/react-native-zip-archive/issues/307
      # error: /node_modules/react-native-zip-archive/ios/RNZipArchive.m unsupported option '-G' for target 'arm64-apple-ios14.0-simulator' 
      if target.name == 'RNZipArchive'
        target.source_build_phase.files.each do |file|
          if file.settings && file.settings['COMPILER_FLAGS']
              file.settings['COMPILER_FLAGS'] = ''
          end
        end
      end
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        if config.name == 'Debug'
          config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
        else
          config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
        end
      end
    end

    bitcode_strip_path = `xcrun --find bitcode_strip`.chop!

    def strip_bitcode_from_framework(bitcode_strip_path, framework_path)
      command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
      puts "Stripping bitcode: #{command}"
      system(command)
    end

    framework_paths = [
      File.join(Dir.pwd.split('/apps')[0], "node_modules/@onekeyfe/react-native-lite-card/ios/GPChannelSDKCore.framework/GPChannelSDKCore"),
    ]

    framework_paths.each do |framework_relative_path|
      strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
    end

    #https://github.com/facebook/react-native/issues/38067#issuecomment-2471023926
    installer.target_installation_results.pod_target_installation_results.each do |pod_name, target_installation_result|
      target_installation_result.native_target.build_configurations.each do |config|
      # For third party modules who have React-bridging dependency to search correct headers
        config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
        # 'react/bridging/CallbackWrapper.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/ReactCommon/react/bridging" '
        # 'react/debug/react_native_assert.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-debug/react/debug" '
        # 'react/utils/jsi-utils.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-utils/react/utils" '
        # 'ReactCommon/TurboModuleBinding.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/ReactCommon/ReactCommon/react/nativemodule/core" '
        # 'ReactCommon/RCTTurboModuleWithJSIBindings.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-NativeModulesApple/ReactCommon" '
        # 'react/renderer/graphics/Float.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-graphics/react/renderer/graphics/react/renderer/graphics/platform/ios" '
        # 'react/renderer/core/ReactPrimitives.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-Fabric/react/renderer/core" '
        # 'react/renderer/imagemanager/ImageRequest.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-Fabric/react/renderer/imagemanager" '
        # 'react/renderer/graphics/Size.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-graphics/react/renderer/graphics" '
        # 'react/renderer/components/view/HostPlatformViewEventEmitter.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-Fabric/react/renderer/components/view/react/renderer/components/view/platform/cxx" '
        # 'react/renderer/components/view/ViewEventEmitter.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-Fabric/react/renderer/components/view" '
        # 'react/renderer/debug/DebugStringConvertible.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-rendererdebug/react/renderer/debug" '
        # 'react/renderer/components/image/conversions.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-FabricImage/react/renderer/components/image" '
        # 'react/renderer/componentregistry/ComponentDescriptorProviderRegistry.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-Fabric/react/renderer/componentregistry" '
        # 'react/renderer/components/iostextinput/primitives.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-FabricComponents/react/renderer/components/iostextinput/react/renderer/components/textinput/platform/ios" '
        # 'react/renderer/components/rncore/ComponentDescriptors.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-FabricComponents/react/renderer/components/rncore" '
        # 'react/renderer/components/unimplementedview/UnimplementedViewComponentDescriptor.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-FabricComponents/react/renderer/components/unimplementedview" '
        # 'react/renderer/scheduler/SurfaceHandler.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-Fabric/react/renderer/scheduler" '
        # 'react/renderer/attributedstring/AttributedString.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-Fabric/react/renderer/attributedstring" '
        # 'react/renderer/mounting/ShadowView.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-Fabric/react/renderer/mounting" '
        # 'react/renderer/components/textinput/BaseTextInputProps.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-FabricComponents/react/renderer/components/textinput" '
        # 'react/renderer/components/text/BaseTextProps.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-FabricComponents/react/renderer/components/text" '
        # 'react/renderer/textlayoutmanager/TextLayoutManager.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-FabricComponents/react/renderer/textlayoutmanager/react/renderer/textlayoutmanager/platform/ios" '
        # 'react/renderer/textlayoutmanager/TextLayoutContext.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-FabricComponents/react/renderer/textlayoutmanager" '
        # 'react/renderer/telemetry/SurfaceTelemetry.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-Fabric/react/renderer/telemetry" '
        # 'react/renderer/components/root/RootShadowNode.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-Fabric/react/renderer/components/root" '
        # 'react/renderer/leakchecker/LeakChecker.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-Fabric/react/renderer/leakchecker" '
        # 'react/renderer/uimanager/UIManagerCommitHook.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-Fabric/react/renderer/uimanager" '
        # 'ReactCommon/RCTHost.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-RuntimeApple/ReactCommon" '
        # 'react/renderer/componentregistry/native/NativeComponentRegistryBinding.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-Fabric/react/renderer/componentregistry/native" '
        # 'react/config/ReactNativeConfig.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-nativeconfig/react/config" '
        # 'react/renderer/imagemanager/RCTImagePrimitivesConversions.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-ImageManager/react/renderer/imagemanager" '
        # 'react/renderer/components/inputaccessory/InputAccessoryComponentDescriptor.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-FabricComponents/react/renderer/components/inputaccessory" '
        # 'react/renderer/components/legacyviewmanagerinterop/LegacyViewManagerInteropComponentDescriptor.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-Fabric/react/renderer/components/legacyviewmanagerinterop" '
        # 'react/renderer/components/modal/ModalHostViewComponentDescriptor.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-FabricComponents/react/renderer/components/modal" '
        # 'react/renderer/components/safeareaview/SafeAreaViewComponentDescriptor.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-FabricComponents/react/renderer/components/safeareaview" '
        # 'react/renderer/components/scrollview/RCTComponentViewHelpers.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-FabricComponents/react/renderer/components/scrollview" '
        # 'react/renderer/consistency/ShadowTreeRevisionConsistencyManager.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-rendererconsistency/react/renderer/consistency" '
        # 'react/renderer/uimanager/consistency/LatestShadowTreeRevisionProvider.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-Fabric/react/renderer/uimanager/consistency" '
        # 'react/renderer/animations/LayoutAnimationDriver.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-Fabric/react/renderer/animations" '
        # 'react/featureflags/ReactNativeFeatureFlags.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-featureflags/react/featureflags" '
        # 'react/performance/timeline/PerformanceEntryReporter.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-performancetimeline/react/performance/timeline" '
        # 'react/renderer/observers/events/EventPerformanceLogger.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-Fabric/react/renderer/observers/events" '
        # 'react/renderer/runtimescheduler/RuntimeScheduler.h' file not found
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Public/React-runtimescheduler/react/renderer/runtimescheduler" '
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end

end
