/* cspell:disable -- device catalog identifiers */
import type { TKnownDeviceCpuTier } from '../devicePerformanceTierTypes';

// Business tiers use Geekbench 6 single-core thresholds: low < 1000,
// medium 1000-1799, and high >= 1800. These are not Geekbench classifications.
export const IOS_DEVICE_CPU_TIER_BY_MODEL: Readonly<
  Record<string, TKnownDeviceCpuTier>
> = {
  'ipad (10th generation)': 'high',
  'ipad (5th generation)': 'low',
  'ipad (6th generation)': 'low',
  'ipad (7th generation)': 'low',
  'ipad (8th generation)': 'medium',
  'ipad (9th generation)': 'medium',
  'ipad air (3rd generation)': 'medium',
  'ipad air (4th generation)': 'high',
  'ipad air (5th generation)': 'high',
  'ipad air 2': 'low',
  'ipad mini (5th generation)': 'medium',
  'ipad mini (6th generation)': 'high',
  'ipad mini 4': 'low',
  'ipad pro (10.5-inch)': 'low',
  'ipad pro (11-inch) (2nd generation)': 'medium',
  'ipad pro (11-inch) (3rd generation)': 'high',
  'ipad pro (12.9-inch) (2nd generation)': 'low',
  'ipad pro (12.9-inch) (3rd generation)': 'medium',
  'ipad pro (12.9-inch) (4th generation)': 'medium',
  'ipad pro (12.9-inch) (5th generation)': 'high',
  'ipad pro (9.7-inch)': 'low',
  'ipad pro 11-inch (3rd generation)': 'high',
  'ipad pro 12.9-inch': 'low',
  'ipad pro 12.9-inch (3rd generation)': 'medium',
  'iphone 11': 'medium',
  'iphone 11 pro': 'medium',
  'iphone 11 pro max': 'medium',
  'iphone 12': 'high',
  'iphone 12 mini': 'high',
  'iphone 12 pro': 'high',
  'iphone 12 pro max': 'high',
  'iphone 13': 'high',
  'iphone 13 mini': 'high',
  'iphone 13 pro': 'high',
  'iphone 13 pro max': 'high',
  'iphone 14': 'high',
  'iphone 14 plus': 'high',
  'iphone 14 pro': 'high',
  'iphone 14 pro max': 'high',
  'iphone 15': 'high',
  'iphone 15 plus': 'high',
  'iphone 15 pro': 'high',
  'iphone 15 pro max': 'high',
  'iphone 16': 'high',
  'iphone 16 plus': 'high',
  'iphone 16 pro': 'high',
  'iphone 16 pro max': 'high',
  'iphone 17': 'high',
  'iphone 17 pro': 'high',
  'iphone 17 pro max': 'high',
  'iphone 6s': 'low',
  'iphone 6s plus': 'low',
  'iphone 7': 'low',
  'iphone 7 plus': 'low',
  'iphone 8': 'medium',
  'iphone 8 plus': 'medium',
  'iphone air': 'high',
  'iphone se': 'low',
  'iphone se (2nd generation)': 'medium',
  'iphone se (3rd generation)': 'high',
  'iphone x': 'medium',
  'iphone xr': 'medium',
  'iphone xs': 'medium',
  'iphone xs max': 'medium',
};
