import { useEffect } from 'react';

import { hideAsync } from 'expo-splash-screen';
import { GestureHandlerRootView } from 'react-native-gesture-handler';

import BootRecovery from '@onekeyhq/shared/src/modules/BootRecovery';

// storybook.requires is generated by the withStorybook Metro wrapper on every
// STORYBOOK_ENABLED start; it's committed because its content is stable (story
// discovery happens via require.context, not an embedded file list).
import { view } from './storybook.requires';

const StorybookUIRoot = view.getStorybookUI({
  // Deterministic cold launches for the spike; revisit for daily use.
  shouldPersistSelection: false,
});

const rootStyle = { flex: 1 } as const;

function StorybookRoot() {
  useEffect(() => {
    // Some component modules call expo-splash-screen's preventAutoHideAsync at
    // module scope (content/Splash, pulled in via the content barrel from e.g.
    // Checkbox). The wallet hides the splash from its SplashProvider; this
    // shell has no such provider, so dismiss it after first mount or the
    // Storybook UI stays stuck behind the native launch screen.
    void hideAsync().catch(() => undefined);

    // The native watchdog (AppDelegate) counts every launch as failed until
    // markBootSuccess resets it; the wallet does this in Bootstrap after a 5s
    // stability window. Without mirroring it here, a few storybook relaunches
    // in a row trip the "We hit a snag" recovery screen.
    const timer = setTimeout(() => {
      try {
        BootRecovery.markBootSuccess();
      } catch {
        // Recovery bookkeeping must never crash the dev shell.
      }
    }, 5000);
    return () => clearTimeout(timer);
  }, []);
  return (
    // Gesture context for swipe-driven overlay components (backpackapp
    // toasts, sheets). The wallet mounts its GestureHandlerRootView in kit's
    // provider tree, which this shell doesn't use, so it owns one here.
    <GestureHandlerRootView style={rootStyle}>
      <StorybookUIRoot />
    </GestureHandlerRootView>
  );
}

export default StorybookRoot;
