// storybook.requires is generated by the withStorybook Metro wrapper on every
// STORYBOOK_ENABLED start; it's committed because its content is stable (story
// discovery happens via require.context, not an embedded file list).
import { view } from './storybook.requires';

const StorybookUIRoot = view.getStorybookUI({
  // Deterministic cold launches for the spike; revisit for daily use.
  shouldPersistSelection: false,
});

export default StorybookUIRoot;
