export const MAX_SIDEBAR_WIDTH = 208;

export const MIN_SIDEBAR_WIDTH = 72;

export const DESKTOP_MODE_UI_PAGE_MARGIN = 0;

export const DESKTOP_MODE_UI_PAGE_BORDER_WIDTH = 1;

export const DESKTOP_MODE_UI_HEADER_HEIGHT = 52;
