/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable spellcheck/spell-checker */
import { memoFn } from '@onekeyhq/shared/src/utils/cacheUtils';
import type { IServerNetwork } from '@onekeyhq/shared/types';
import { ENetworkStatus } from '@onekeyhq/shared/types';

import platformEnv from '../platformEnv';

// dangerNetwork represents a virtual network
export const dangerAllNetworkRepresent: IServerNetwork = {
  'chainId': '0',
  'code': 'onekeyall',
  'decimals': 0,
  'id': 'onekeyall--0',
  'impl': 'onekeyall',
  'isTestnet': false,
  'isAllNetworks': true,
  'logoURI': 'https://uni.onekey-asset.com/static/logo/chain_selector_logo.png',
  'name': 'All Networks',
  'shortcode': 'onekeyall',
  'shortname': 'onekeyall',
  'symbol': 'ALL NETWORKS',
  'feeMeta': {
    'code': '',
    'decimals': 0,
    'symbol': '0',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

// EVM networks
const eth: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1',
  'id': 'evm--1',
  'name': 'Ethereum',
  'symbol': 'ETH',
  'code': 'eth',
  'shortcode': 'eth',
  'shortname': 'ETH',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': true,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 3,
    'isTokenSupported': true,
    'isNFTEnabled': true,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/eth.png',
  'defaultEnabled': true,
  'backendIndex': true,
};
const bsc: IServerNetwork = {
  'impl': 'evm',
  'chainId': '56',
  'id': 'evm--56',
  'name': 'BNB Chain',
  'symbol': 'BNB',
  'code': 'bsc',
  'shortcode': 'bsc',
  'shortname': 'BSC',
  'decimals': 18,
  'feeMeta': {
    'code': 'bsc',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 4,
    'isTokenSupported': true,
    'isNFTEnabled': true,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/bsc.png',
  'defaultEnabled': true,
  'backendIndex': true,
};
const polygon: IServerNetwork = {
  'impl': 'evm',
  'chainId': '137',
  'id': 'evm--137',
  'name': 'Polygon',
  'symbol': 'POL',
  'code': 'polygon',
  'shortcode': 'polygon',
  'shortname': 'Polygon',
  'decimals': 18,
  'feeMeta': {
    'code': 'polygon',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': true,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 5,
    'isTokenSupported': true,
    'isNFTEnabled': true,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/polygon.png',
  'defaultEnabled': true,
  'backendIndex': true,
};
const fantom: IServerNetwork = {
  'impl': 'evm',
  'chainId': '250',
  'id': 'evm--250',
  'name': 'Fantom',
  'symbol': 'FTM',
  'code': 'fantom',
  'shortcode': 'fantom',
  'shortname': 'FTM',
  'decimals': 18,
  'feeMeta': {
    'code': 'fantom',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 6,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/fantom.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const arbitrum: IServerNetwork = {
  'impl': 'evm',
  'chainId': '42161',
  'id': 'evm--42161',
  'name': 'Arbitrum',
  'symbol': 'ETH',
  'code': 'arbitrum',
  'shortcode': 'arbitrum',
  'shortname': 'Arbitrum',
  'decimals': 18,
  'feeMeta': {
    'code': 'arbitrum',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 7,
    'isTokenSupported': true,
    'isNFTEnabled': true,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/arbitrum.png',
  'defaultEnabled': true,
  'backendIndex': true,
};
const avalanche: IServerNetwork = {
  'impl': 'evm',
  'chainId': '43114',
  'id': 'evm--43114',
  'name': 'Avalanche',
  'symbol': 'AVAX',
  'code': 'avalanche',
  'shortcode': 'avalanche',
  'shortname': 'Avalanche',
  'decimals': 18,
  'feeMeta': {
    'code': 'avalanche',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 8,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/avalanche.png',
  'defaultEnabled': true,
  'backendIndex': true,
};
const okt: IServerNetwork = {
  'impl': 'evm',
  'chainId': '66',
  'id': 'evm--66',
  'name': 'OKX Chain',
  'symbol': 'OKT',
  'code': 'okt',
  'shortcode': 'okt',
  'shortname': 'OKC',
  'decimals': 18,
  'feeMeta': {
    'code': 'okt',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 10,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/okx-chain.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const optimism: IServerNetwork = {
  'impl': 'evm',
  'chainId': '10',
  'id': 'evm--10',
  'name': 'Optimism',
  'symbol': 'ETH',
  'code': 'optimism',
  'shortcode': 'optimism',
  'shortname': 'Optimism',
  'decimals': 18,
  'feeMeta': {
    'code': 'optimism',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': true,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 11,
    'isTokenSupported': true,
    'isNFTEnabled': true,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/optimism.png',
  'defaultEnabled': true,
  'backendIndex': true,
};
const xdai: IServerNetwork = {
  'impl': 'evm',
  'chainId': '100',
  'id': 'evm--100',
  'name': 'Gnosis Chain',
  'symbol': 'xDAI',
  'code': 'xdai',
  'shortcode': 'xdai',
  'shortname': 'GNO',
  'decimals': 18,
  'feeMeta': {
    'code': 'xdai',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 12,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/gno.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const celo: IServerNetwork = {
  'impl': 'evm',
  'chainId': '42220',
  'id': 'evm--42220',
  'name': 'Celo',
  'symbol': 'CELO',
  'code': 'celo',
  'shortcode': 'celo',
  'shortname': 'CELO',
  'decimals': 18,
  'feeMeta': {
    'code': 'celo',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 16,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/celo.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const zksyncera: IServerNetwork = {
  'impl': 'evm',
  'chainId': '324',
  'id': 'evm--324',
  'name': 'zkSync Era',
  'symbol': 'ETH',
  'code': 'zksyncera',
  'shortcode': 'zksyncera',
  'shortname': 'ZKSYNCERA',
  'decimals': 18,
  'feeMeta': {
    'code': 'zksyncera',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/zksync-era-mainnet.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const zklinknova: IServerNetwork = {
  'impl': 'evm',
  'chainId': '810180',
  'id': 'evm--810180',
  'name': 'zkLink Nova',
  'symbol': 'ETH',
  'code': 'zklinknova',
  'shortcode': 'zklinknova',
  'shortname': 'zklink-nova',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/zklinknova.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const opbnb: IServerNetwork = {
  'impl': 'evm',
  'chainId': '204',
  'id': 'evm--204',
  'name': 'opBNB',
  'symbol': 'BNB',
  'code': 'opbnb',
  'shortcode': 'opbnb',
  'shortname': 'obnb',
  'decimals': 18,
  'feeMeta': {
    'code': 'bnb',
    'decimals': 9,
    'symbol': 'Gwei',
    'isWithL1BaseFee': true,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/opbnb.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const zora: IServerNetwork = {
  'impl': 'evm',
  'chainId': '7777777',
  'id': 'evm--7777777',
  'name': 'Zora',
  'symbol': 'ETH',
  'code': 'zora',
  'shortcode': 'zora',
  'shortname': 'zora',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/zora.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const zetachain: IServerNetwork = {
  'impl': 'evm',
  'chainId': '7000',
  'id': 'evm--7000',
  'name': 'ZetaChain',
  'symbol': 'ZETA',
  'code': 'zetachain',
  'shortcode': 'zetachain',
  'shortname': 'zetachain-mainnet',
  'decimals': 18,
  'feeMeta': {
    'code': 'zeta',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/zetachain.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const okb: IServerNetwork = {
  'impl': 'evm',
  'chainId': '196',
  'id': 'evm--196',
  'name': 'X Layer',
  'symbol': 'OKB',
  'code': 'okb',
  'shortcode': 'okb',
  'shortname': 'okb',
  'decimals': 18,
  'feeMeta': {
    'code': 'okb',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/okb.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const wemix: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1111',
  'id': 'evm--1111',
  'name': 'WEMIX3.0',
  'symbol': 'WEMIX',
  'code': 'wemix',
  'shortcode': 'wemix',
  'shortname': 'wemix',
  'decimals': 18,
  'feeMeta': {
    'code': 'wemix',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/wemix.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const taiko: IServerNetwork = {
  'impl': 'evm',
  'chainId': '167000',
  'id': 'evm--167000',
  'name': 'Taiko',
  'symbol': 'ETH',
  'code': 'taiko',
  'shortcode': 'taiko',
  'shortname': 'tko-mainnet',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/taiko.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const scr: IServerNetwork = {
  'impl': 'evm',
  'chainId': '534352',
  'id': 'evm--534352',
  'name': 'Scroll',
  'symbol': 'ETH',
  'code': 'scr',
  'shortcode': 'scr',
  'shortname': 'scr',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
    'isWithL1BaseFee': true,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/scr.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const ronin: IServerNetwork = {
  'impl': 'evm',
  'chainId': '2020',
  'id': 'evm--2020',
  'name': 'Ronin',
  'symbol': 'RON',
  'code': 'ronin',
  'shortcode': 'ronin',
  'shortname': 'ronin',
  'decimals': 18,
  'feeMeta': {
    'code': 'ron',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/ronin.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const pulse: IServerNetwork = {
  'impl': 'evm',
  'chainId': '369',
  'id': 'evm--369',
  'name': 'PulseChain',
  'symbol': 'PLS',
  'code': 'pulse',
  'shortcode': 'pulse',
  'shortname': 'pls',
  'decimals': 18,
  'feeMeta': {
    'code': 'pls',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/pulse.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const polygonzkevm: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1101',
  'id': 'evm--1101',
  'name': 'Polygon Zkevm',
  'symbol': 'ETH',
  'code': 'polygonzkevm',
  'shortcode': 'polygonzkevm',
  'shortname': 'polygonzkevm',
  'decimals': 18,
  'feeMeta': {
    'code': 'polygonzkevm',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/polygon-zkevm.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const octa: IServerNetwork = {
  'impl': 'evm',
  'chainId': '800001',
  'id': 'evm--800001',
  'name': 'OctaSpace',
  'symbol': 'OCTA',
  'code': 'octa',
  'shortcode': 'octa',
  'shortname': 'octa',
  'decimals': 18,
  'feeMeta': {
    'code': 'octa',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/octa.webp',
  'defaultEnabled': true,
  'backendIndex': false,
};
const moonbeam: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1284',
  'id': 'evm--1284',
  'name': 'Moonbeam',
  'symbol': 'GLMR',
  'code': 'moonbeam',
  'shortcode': 'moonbeam',
  'shortname': 'mbeam',
  'decimals': 18,
  'feeMeta': {
    'code': 'glmr',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/moonbeam.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const mode: IServerNetwork = {
  'impl': 'evm',
  'chainId': '34443',
  'id': 'evm--34443',
  'name': 'Mode',
  'symbol': 'ETH',
  'code': 'mode',
  'shortcode': 'mode',
  'shortname': 'mode',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
    'isWithL1BaseFee': true,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/mode.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const mvm: IServerNetwork = {
  'impl': 'evm',
  'chainId': '73927',
  'id': 'evm--73927',
  'name': 'Mixin',
  'symbol': 'ETH',
  'code': 'mvm',
  'shortcode': 'mvm',
  'shortname': 'MVM',
  'decimals': 18,
  'feeMeta': {
    'code': 'mvm',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI':
    'https://uni.onekey-asset.com/static/chain/mixin-virtual-machine.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const metis: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1088',
  'id': 'evm--1088',
  'name': 'Metis',
  'symbol': 'METIS',
  'code': 'metis',
  'shortcode': 'metis',
  'shortname': 'metis-andromeda',
  'decimals': 18,
  'feeMeta': {
    'code': 'metis',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/metis.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const merlinmainnet: IServerNetwork = {
  'impl': 'evm',
  'chainId': '4200',
  'id': 'evm--4200',
  'name': 'Merlin',
  'symbol': 'BTC',
  'code': 'merlinmainnet',
  'shortcode': 'merlinmainnet',
  'shortname': 'Merlin-Mainnet',
  'decimals': 18,
  'feeMeta': {
    'code': 'btc',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/merlinmainnet.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const mantle: IServerNetwork = {
  'impl': 'evm',
  'chainId': '5000',
  'id': 'evm--5000',
  'name': 'Mantle',
  'symbol': 'MNT',
  'code': 'mantle',
  'shortcode': 'mantle',
  'shortname': 'Mantle',
  'decimals': 18,
  'feeMeta': {
    'code': 'mantle',
    'decimals': 9,
    'symbol': 'Gwei',
    'maxSendFeeUpRatio': 1.2,
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/mantle.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const mantapacific: IServerNetwork = {
  'impl': 'evm',
  'chainId': '169',
  'id': 'evm--169',
  'name': 'Manta Pacific',
  'symbol': 'MANTASPACIFIC',
  'code': 'mantapacific',
  'shortcode': 'mantapacific',
  'shortname': 'mantapacific',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'ETH',
    'maxSendFeeUpRatio': 1.2,
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI':
    'https://uni.onekey-asset.com/static/chain/manta-pacific-mainnet.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const linea: IServerNetwork = {
  'impl': 'evm',
  'chainId': '59144',
  'id': 'evm--59144',
  'name': 'Linea',
  'symbol': 'ETH',
  'code': 'linea',
  'shortcode': 'linea',
  'shortname': 'Linea',
  'decimals': 18,
  'feeMeta': {
    'code': 'Linea',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/linea.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const kaia: IServerNetwork = {
  'impl': 'evm',
  'chainId': '8217',
  'id': 'evm--8217',
  'name': 'Kaia',
  'symbol': 'KAIA',
  'code': 'Kaia',
  'shortcode': 'kaia',
  'shortname': 'kaia',
  'decimals': 18,
  'feeMeta': {
    'code': 'kaia',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/kaia.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const kava: IServerNetwork = {
  'impl': 'evm',
  'chainId': '2222',
  'id': 'evm--2222',
  'name': 'Kava',
  'symbol': 'KAVA',
  'code': 'kava',
  'shortcode': 'kava',
  'shortname': 'kava',
  'decimals': 18,
  'feeMeta': {
    'code': 'kava',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/kava.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const iotex: IServerNetwork = {
  'impl': 'evm',
  'chainId': '4689',
  'id': 'evm--4689',
  'name': 'IoTeX',
  'symbol': 'IOTX',
  'code': 'iotex',
  'shortcode': 'iotex',
  'shortname': 'iotex',
  'decimals': 18,
  'feeMeta': {
    'code': 'iotex',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/iotex.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const harmony: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1666600000',
  'id': 'evm--1666600000',
  'name': 'Harmony',
  'symbol': 'ONE',
  'code': 'harmony',
  'shortcode': 'harmony',
  'shortname': 'hmy-s0',
  'decimals': 18,
  'feeMeta': {
    'code': 'one',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/harmony.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const flare: IServerNetwork = {
  'impl': 'evm',
  'chainId': '14',
  'id': 'evm--14',
  'name': 'Flare',
  'symbol': 'FLR',
  'code': 'flare',
  'shortcode': 'flare',
  'shortname': 'flr',
  'decimals': 18,
  'feeMeta': {
    'code': 'flr',
    'decimals': 9,
    'symbol': 'Gwei',
    'maxSendFeeUpRatio': 1.1,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/flare.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const fevm: IServerNetwork = {
  'impl': 'evm',
  'chainId': '314',
  'id': 'evm--314',
  'name': 'Filecoin FEVM',
  'symbol': 'FIL',
  'code': 'fevm',
  'shortcode': 'fevm',
  'shortname': 'FEVM',
  'decimals': 18,
  'feeMeta': {
    'code': 'fevm',
    'decimals': 9,
    'symbol': 'Gwei',
    'maxSendFeeUpRatio': 1.1,
    'isEIP1559FeeEnabled': true,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/fevm.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const ethw: IServerNetwork = {
  'impl': 'evm',
  'chainId': '10001',
  'id': 'evm--10001',
  'name': 'EthereumPoW',
  'symbol': 'ETHW',
  'code': 'ethw',
  'shortcode': 'ethw',
  'shortname': 'ETHW',
  'decimals': 18,
  'feeMeta': {
    'code': 'ethw',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/ethw.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const sepolia: IServerNetwork = {
  'impl': 'evm',
  'chainId': '11155111',
  'id': 'evm--11155111',
  'name': 'Ethereum Sepolia Testnet',
  'symbol': 'TETH',
  'code': 'sepolia',
  'shortcode': 'sepolia',
  'shortname': 'Sepolia',
  'decimals': 18,
  'feeMeta': {
    'code': 'sepolia',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': true,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/sepolia.png',
  'defaultEnabled': false,
  'backendIndex': true,
};
const etc: IServerNetwork = {
  'impl': 'evm',
  'chainId': '61',
  'id': 'evm--61',
  'name': 'Ethereum Classic',
  'symbol': 'ETC',
  'code': 'etc',
  'shortcode': 'etc',
  'shortname': 'ETC',
  'decimals': 18,
  'feeMeta': {
    'code': 'etc',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/etc.png',
  'defaultEnabled': true,
  'backendIndex': true,
};
const ace: IServerNetwork = {
  'impl': 'evm',
  'chainId': '648',
  'id': 'evm--648',
  'name': 'Endurance',
  'symbol': 'ACE',
  'code': 'ace',
  'shortcode': 'ace',
  'shortname': 'ace',
  'decimals': 18,
  'feeMeta': {
    'code': 'ace',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/ace.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const dymension: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1100',
  'id': 'evm--1100',
  'name': 'Dymension',
  'symbol': 'DYM',
  'code': 'dymension',
  'shortcode': 'dymension',
  'shortname': 'dymension',
  'decimals': 18,
  'feeMeta': {
    'code': 'dym',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/dymension.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const dis: IServerNetwork = {
  'impl': 'evm',
  'chainId': '513100',
  'id': 'evm--513100',
  'name': 'DIS CHAIN',
  'symbol': 'DIS',
  'code': 'dis',
  'shortcode': 'dis',
  'shortname': 'DIS',
  'decimals': 18,
  'feeMeta': {
    'code': 'dis',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/dis.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const cyeth: IServerNetwork = {
  'impl': 'evm',
  'chainId': '7560',
  'id': 'evm--7560',
  'name': 'Cyber',
  'symbol': 'ETH',
  'code': 'cyeth',
  'shortcode': 'cyeth',
  'shortname': 'cyeth',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/cyeth.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const cronos: IServerNetwork = {
  'impl': 'evm',
  'chainId': '25',
  'id': 'evm--25',
  'name': 'Cronos',
  'symbol': 'CRO',
  'code': 'cronos',
  'shortcode': 'cronos',
  'shortname': 'CRO',
  'decimals': 18,
  'feeMeta': {
    'code': 'cronos',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/cronos.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const core: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1116',
  'id': 'evm--1116',
  'name': 'Core',
  'symbol': 'CORE',
  'code': 'core',
  'shortcode': 'core',
  'shortname': 'core',
  'decimals': 18,
  'feeMeta': {
    'code': 'core',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/core.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const cfxespace: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1030',
  'id': 'evm--1030',
  'name': 'Conflux eSpace',
  'symbol': 'CFX',
  'code': 'cfxespace',
  'shortcode': 'cfxespace',
  'shortname': 'CFXESPACE',
  'decimals': 18,
  'feeMeta': {
    'code': 'cfxespace',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/conflux-espace.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const b2: IServerNetwork = {
  'impl': 'evm',
  'chainId': '223',
  'id': 'evm--223',
  'name': 'B² Mainnet',
  'symbol': 'BTC',
  'code': 'b2',
  'shortcode': 'b2',
  'shortname': 'b2',
  'decimals': 18,
  'feeMeta': {
    'code': 'btc',
    'decimals': 9,
    'symbol': 'Gwei',
    'maxSendFeeUpRatio': 1.1,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/b2.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const bouncebit: IServerNetwork = {
  'impl': 'evm',
  'chainId': '6001',
  'id': 'evm--6001',
  'name': 'BounceBit',
  'symbol': 'BB',
  'code': 'bouncebit',
  'shortcode': 'bouncebit',
  'shortname': 'bouncebit-mainnet',
  'decimals': 18,
  'feeMeta': {
    'code': 'bb',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/bouncebit.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const boba: IServerNetwork = {
  'impl': 'evm',
  'chainId': '288',
  'id': 'evm--288',
  'name': 'Boba',
  'symbol': 'ETH',
  'code': 'boba',
  'shortcode': 'boba',
  'shortname': 'Boba',
  'decimals': 18,
  'feeMeta': {
    'code': 'boba',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': true,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/boba.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const blast: IServerNetwork = {
  'impl': 'evm',
  'chainId': '81457',
  'id': 'evm--81457',
  'name': 'Blast',
  'symbol': 'BLAST',
  'code': 'blast',
  'shortcode': 'blast',
  'shortname': 'blast',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'ETH',
    'maxSendFeeUpRatio': 1.2,
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/logo/blast.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const btr: IServerNetwork = {
  'impl': 'evm',
  'chainId': '200901',
  'id': 'evm--200901',
  'name': 'Bitlayer',
  'symbol': 'BTC',
  'code': 'btr',
  'shortcode': 'btr',
  'shortname': 'btr',
  'decimals': 18,
  'feeMeta': {
    'code': 'btc',
    'decimals': 9,
    'symbol': 'Gwei',
    'maxSendFeeUpRatio': 1.1,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/btr.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const base: IServerNetwork = {
  'impl': 'evm',
  'chainId': '8453',
  'id': 'evm--8453',
  'name': 'Base',
  'symbol': 'ETH',
  'code': 'base',
  'shortcode': 'base',
  'shortname': 'Base',
  'decimals': 18,
  'feeMeta': {
    'code': 'base',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': true,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/base.png',
  'defaultEnabled': true,
  'backendIndex': true,
};
const bob: IServerNetwork = {
  'impl': 'evm',
  'chainId': '60808',
  'id': 'evm--60808',
  'name': 'BOB',
  'symbol': 'ETH',
  'code': 'bob',
  'shortcode': 'bob',
  'shortname': 'bob',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/bob.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const aurora: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1313161554',
  'id': 'evm--1313161554',
  'name': 'Aurora',
  'symbol': 'ETH',
  'code': 'aurora',
  'shortcode': 'aurora',
  'shortname': 'Aurora',
  'decimals': 18,
  'feeMeta': {
    'code': 'aurora',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/aurora.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const holesky: IServerNetwork = {
  'impl': 'evm',
  'chainId': '17000',
  'id': 'evm--17000',
  'name': 'Ethereum Holesky Testnet',
  'symbol': 'ETH',
  'code': 'holesky',
  'shortcode': 'holesky',
  'shortname': 'Holesky',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': true,
  'extensions': {
    'position': 9999,
    'isTokenSupported': false,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/holesky.png',
  'defaultEnabled': false,
  'backendIndex': false,
};
const zircuit: IServerNetwork = {
  'impl': 'evm',
  'chainId': '48900',
  'id': 'evm--48900',
  'name': 'Zircuit',
  'symbol': 'ETH',
  'code': 'zircuit',
  'shortcode': 'zircuit',
  'shortname': 'Zircuit',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': false,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/zircuit.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const neox: IServerNetwork = {
  'impl': 'evm',
  'chainId': '47763',
  'id': 'evm--47763',
  'name': 'Neo X Mainnet',
  'symbol': 'GAS',
  'code': 'neox',
  'shortcode': 'neox',
  'shortname': 'neox',
  'decimals': 18,
  'feeMeta': {
    'code': 'gas',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI':
    'https://uni.onekey-asset.com/dashboard/logo/upload_1729561119021.0.635920670130657.0.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const azero: IServerNetwork = {
  'impl': 'evm',
  'chainId': '41455',
  'id': 'evm--41455',
  'name': 'Aleph Zero EVM',
  'symbol': 'AZERO',
  'code': 'alephazero',
  'shortcode': 'alephazero',
  'shortname': 'azero',
  'decimals': 18,
  'feeMeta': {
    'code': 'azero',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI':
    'https://uni.onekey-asset.com/dashboard/logo/upload_1729837141734.0.5402483107018017.0.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const dtc: IServerNetwork = {
  'impl': 'evm',
  'chainId': '9798',
  'id': 'evm--9798',
  'name': 'DataTradeChain',
  'symbol': 'DTT',
  'code': 'dtc',
  'shortcode': 'dtc',
  'shortname': 'DTC',
  'decimals': 18,
  'feeMeta': {
    'code': 'dtt',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/dtc.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const btc: IServerNetwork = {
  'chainId': '0',
  'code': 'btc',
  'decimals': 8,
  'extensions': {
    'position': 2,
  },
  'id': 'btc--0',
  'impl': 'btc',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/btc.png',
  'name': 'Bitcoin',
  'shortcode': 'btc',
  'shortname': 'BTC',
  'symbol': 'BTC',
  'feeMeta': {
    'code': 'btc',
    'decimals': 8,
    'symbol': 'BTC',
  },
  'defaultEnabled': true,
  'backendIndex': true,
  'status': ENetworkStatus.LISTED,
};

const tbtc: IServerNetwork = {
  'chainId': '0',
  'code': 'tbtc',
  'decimals': 8,
  'id': 'tbtc--0',
  'impl': 'tbtc',
  'isTestnet': true,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/bitcoin-testnet.png',
  'name': 'Bitcoin Testnet',
  'shortcode': 'tbtc',
  'shortname': 'TBTC',
  'symbol': 'TBTC',
  'feeMeta': {
    'code': 'tbtc',
    'decimals': 8,
    'symbol': 'TBTC',
  },
  'defaultEnabled': false,
  'status': ENetworkStatus.LISTED,
};

const sbtc: IServerNetwork = {
  'chainId': '0',
  'code': 'sbtc',
  'decimals': 8,
  'id': 'tbtc--1',
  'impl': 'tbtc',
  'isTestnet': true,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/sbtc.png',
  'name': 'Bitcoin Signet',
  'shortcode': 'sbtc',
  'shortname': 'SBTC',
  'symbol': 'SBTC',
  'feeMeta': {
    'code': 'sbtc',
    'decimals': 8,
    'symbol': 'SBTC',
  },
  'defaultEnabled': false,
  'status': ENetworkStatus.LISTED,
};

const doge: IServerNetwork = {
  'chainId': '0',
  'code': 'doge',
  'decimals': 8,
  'id': 'doge--0',
  'impl': 'doge',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/doge.png',
  'name': 'Dogecoin',
  'shortcode': 'doge',
  'shortname': 'DOGE',
  'symbol': 'DOGE',
  'feeMeta': {
    'code': 'doge',
    'decimals': 8,
    'symbol': 'DOGE',
  },
  'defaultEnabled': true,
  'backendIndex': true,
  'status': ENetworkStatus.LISTED,
};

const bch: IServerNetwork = {
  'chainId': '0',
  'code': 'bch',
  'decimals': 8,
  'id': 'bch--0',
  'impl': 'bch',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/bch.png',
  'name': 'Bitcoin Cash',
  'shortcode': 'bch',
  'shortname': 'BCH',
  'symbol': 'BCH',
  'feeMeta': {
    'code': 'bch',
    'decimals': 8,
    'symbol': 'BCH',
  },
  'defaultEnabled': true,
  'backendIndex': true,
  'status': ENetworkStatus.LISTED,
};

const ltc: IServerNetwork = {
  'chainId': '0',
  'code': 'ltc',
  'decimals': 8,
  'id': 'ltc--0',
  'impl': 'ltc',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/ltc.png',
  'name': 'Litecoin',
  'shortcode': 'ltc',
  'shortname': 'LTC',
  'symbol': 'LTC',
  'feeMeta': {
    'code': 'ltc',
    'decimals': 8,
    'symbol': 'LTC',
  },
  'defaultEnabled': true,
  'backendIndex': true,
  'status': ENetworkStatus.LISTED,
};

const neurai: IServerNetwork = {
  'chainId': '0',
  'code': 'neurai',
  'decimals': 8,
  'id': 'neurai--0',
  'impl': 'neurai',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/neurai.png',
  'name': 'Neurai',
  'shortcode': 'xna',
  'shortname': 'XNA',
  'symbol': 'XNA',
  'feeMeta': {
    'code': 'xna',
    'decimals': 8,
    'symbol': 'XNA',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const tatom: IServerNetwork = {
  'chainId': 'theta-testnet-001',
  'code': 'tatom',
  'decimals': 6,
  'id': 'cosmos--theta-testnet-001',
  'impl': 'cosmos',
  'isTestnet': true,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/cosmos.png',
  'name': 'Cosmos Testnet',
  'shortcode': 'tatom',
  'shortname': 'TCosmos',
  'symbol': 'TATOM',
  'feeMeta': {
    'code': 'tatom',
    'decimals': 6,
    'symbol': 'TATOM',
  },
  'defaultEnabled': false,
  'status': ENetworkStatus.LISTED,
};

const cosmoshub: IServerNetwork = {
  'chainId': 'cosmoshub-4',
  'code': 'cosmoshub',
  'decimals': 6,
  'id': 'cosmos--cosmoshub-4',
  'impl': 'cosmos',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/cosmos.png',
  'name': 'Cosmos',
  'shortcode': 'cosmoshub',
  'shortname': 'Cosmos',
  'symbol': 'ATOM',
  'feeMeta': {
    'code': 'cosmoshub',
    'decimals': 6,
    'symbol': 'ATOM',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const osmosis: IServerNetwork = {
  'chainId': 'osmosis-1',
  'code': 'osmosis',
  'decimals': 6,
  'id': 'cosmos--osmosis-1',
  'impl': 'cosmos',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/osmosis.png',
  'name': 'Osmosis',
  'shortcode': 'osmosis',
  'shortname': 'Osmosis',
  'symbol': 'OSMO',
  'feeMeta': {
    'code': 'osmosis',
    'decimals': 6,
    'symbol': 'OSMO',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const akash: IServerNetwork = {
  'chainId': 'akashnet-2',
  'code': 'akash',
  'decimals': 6,
  'id': 'cosmos--akashnet-2',
  'impl': 'cosmos',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/akash.png',
  'name': 'Akash',
  'shortcode': 'akash',
  'shortname': 'Akash',
  'symbol': 'AKT',
  'feeMeta': {
    'code': 'akash',
    'decimals': 6,
    'symbol': 'AKT',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const cryptoorgchain: IServerNetwork = {
  'chainId': 'crypto-org-chain-mainnet-1',
  'code': 'cryptoorgchain',
  'decimals': 8,
  'id': 'cosmos--crypto-org-chain-mainnet-1',
  'impl': 'cosmos',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/cryptoorg.png',
  'name': 'Crypto.org',
  'shortcode': 'cryptoorgchain',
  'shortname': 'Crypto.org',
  'symbol': 'CRO',
  'feeMeta': {
    'code': 'cryptoorgchain',
    'decimals': 8,
    'symbol': 'CRO',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const fetchai: IServerNetwork = {
  'chainId': 'fetchhub-4',
  'code': 'fetch',
  'decimals': 18,
  'id': 'cosmos--fetchhub-4',
  'impl': 'cosmos',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/fetch.png',
  'name': 'Fetch.ai',
  'shortcode': 'fetch',
  'shortname': 'Fetch.ai',
  'symbol': 'FET',
  'feeMeta': {
    'code': 'fetch',
    'decimals': 18,
    'symbol': 'FET',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const juno: IServerNetwork = {
  'chainId': 'juno-1',
  'code': 'juno',
  'decimals': 6,
  'id': 'cosmos--juno-1',
  'impl': 'cosmos',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/juno.png',
  'name': 'Juno',
  'shortcode': 'juno',
  'shortname': 'Juno',
  'symbol': 'JUNO',
  'feeMeta': {
    'code': 'juno',
    'decimals': 6,
    'symbol': 'JUNO',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const secret: IServerNetwork = {
  'chainId': 'secret-4',
  'code': 'secretnetwork',
  'decimals': 6,
  'id': 'cosmos--secret-4',
  'impl': 'cosmos',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/secret.png',
  'name': 'Secret Network',
  'shortcode': 'secretnetwork',
  'shortname': 'Secret Network',
  'symbol': 'SCRT',
  'feeMeta': {
    'code': 'secretnetwork',
    'decimals': 6,
    'symbol': 'SCRT',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const celestia: IServerNetwork = {
  'chainId': 'celestia',
  'code': 'celestia',
  'decimals': 6,
  'id': 'cosmos--celestia',
  'impl': 'cosmos',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/celestia.png',
  'name': 'Celestia',
  'shortcode': 'celestia',
  'shortname': 'Celestia',
  'symbol': 'TIA',
  'feeMeta': {
    'code': 'tia',
    'decimals': 6,
    'symbol': 'TIA',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const lightning: IServerNetwork = {
  'chainId': '0',
  'code': 'lightning',
  'decimals': 0,
  'extensions': {
    'position': 2,
  },
  'id': 'lightning--0',
  'impl': 'lightning',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/lnd.png',
  'name': 'Lightning Network',
  'shortcode': 'lightning',
  'shortname': 'Lightning',
  'symbol': 'sats',
  'feeMeta': {
    'code': 'lightning',
    'decimals': 0,
    'symbol': 'sats',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};
const tlightning: IServerNetwork = {
  'chainId': '0',
  'code': 'tlightning',
  'decimals': 0,
  'id': 'tlightning--0',
  'impl': 'tlightning',
  'isTestnet': true,
  'logoURI':
    'https://uni.onekey-asset.com/static/chain/lightning-network-testnet.png',
  'name': 'Lightning Network Testnet',
  'shortcode': 'tlightning',
  'shortname': 'LightningTestnet',
  'symbol': 'sats',
  'feeMeta': {
    'code': 'lightning',
    'decimals': 0,
    'symbol': 'sats',
  },
  'defaultEnabled': false,
  'status': ENetworkStatus.LISTED,
};

const algo: IServerNetwork = {
  'chainId': '4160',
  'code': 'algo',
  'decimals': 6,
  'extensions': {
    'position': 15,
  },
  'id': 'algo--4160',
  'impl': 'algo',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/algo.png',
  'name': 'Algorand',
  'shortcode': 'algo',
  'shortname': 'ALGO',
  'symbol': 'ALGO',
  'feeMeta': {
    'code': 'algo',
    'decimals': 6,
    'symbol': 'ALGO',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const cardano: IServerNetwork = {
  'chainId': '0',
  'code': 'ada',
  'decimals': 6,
  'id': 'ada--0',
  'impl': 'ada',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/ada.png',
  'name': 'Cardano',
  'shortcode': 'ada',
  'shortname': 'Cardano',
  'symbol': 'ADA',
  'feeMeta': {
    'code': 'ada',
    'decimals': 6,
    'symbol': 'ada',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const nostr: IServerNetwork = {
  id: 'nostr--0',
  impl: 'nostr',
  chainId: '0',
  code: 'nostr',
  defaultEnabled: true,
  isTestnet: false,
  feeMeta: {
    symbol: 'nostr',
    decimals: 0,
    code: 'nostr',
  },
  decimals: 0,
  'status': ENetworkStatus.LISTED,
  name: 'Nostr',
  symbol: 'Nostr',
  shortname: 'Nostr',
  shortcode: 'nostr',
  logoURI: 'https://uni.onekey-asset.com/static/chain/nostr.png',
};

const ripple: IServerNetwork = {
  'chainId': '0',
  'code': 'xrp',
  'decimals': 6,
  'id': 'xrp--0',
  'impl': 'xrp',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/xrp.png',
  'name': 'Ripple',
  'shortcode': 'xrp',
  'shortname': 'Ripple',
  'symbol': 'XRP',
  'feeMeta': {
    'code': 'xrp',
    'decimals': 6,
    'symbol': 'xrp',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const tron: IServerNetwork = {
  'chainId': '0x2b6653dc',
  'code': 'trx',
  'decimals': 6,
  'id': 'tron--0x2b6653dc',
  'impl': 'tron',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/tron.png',
  'name': 'Tron',
  'shortcode': 'trx',
  'shortname': 'TRX',
  'symbol': 'TRX',
  'feeMeta': {
    'code': 'trx',
    'decimals': 6,
    'symbol': 'TRX',
  },
  'defaultEnabled': true,
  'backendIndex': true,
  'status': ENetworkStatus.LISTED,
};

const near: IServerNetwork = {
  'chainId': '0',
  'code': 'near',
  'decimals': 24,
  'id': 'near--0',
  'impl': 'near',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/near.png',
  'name': 'Near',
  'shortcode': 'near',
  'shortname': 'Near',
  'symbol': 'NEAR',
  'feeMeta': {
    'code': 'near',
    'decimals': 24,
    'symbol': 'NEAR',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const sol: IServerNetwork = {
  'chainId': '101',
  'code': 'sol',
  'decimals': 9,
  'extensions': {
    'position': 4,
  },
  'id': 'sol--101',
  'impl': 'sol',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/sol.png',
  'name': 'Solana',
  'shortcode': 'sol',
  'shortname': 'SOL',
  'symbol': 'SOL',
  'feeMeta': {
    'code': 'sol',
    'decimals': 9,
    'symbol': 'SOL',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const polkadot: IServerNetwork = {
  'chainId': 'polkadot',
  'code': 'dot',
  'decimals': 10,
  'id': 'dot--polkadot',
  'impl': 'dot',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/polkadot.png',
  'name': 'Polkadot',
  'shortcode': 'dot',
  'shortname': 'DOT',
  'symbol': 'DOT',
  'feeMeta': {
    'code': 'dot',
    'decimals': 10,
    'symbol': 'DOT',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const astar: IServerNetwork = {
  'chainId': 'astar',
  'code': 'astar',
  'decimals': 18,
  'id': 'dot--astar',
  'impl': 'dot',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/astar.png',
  'name': 'Astar',
  'shortcode': 'astar',
  'shortname': 'ASTR',
  'symbol': 'ASTR',
  'feeMeta': {
    'code': 'astar',
    'decimals': 18,
    'symbol': '18',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const kusama: IServerNetwork = {
  'chainId': 'kusama',
  'code': 'ksm',
  'decimals': 12,
  'id': 'dot--kusama',
  'impl': 'dot',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/kusama.png',
  'name': 'Kusama',
  'shortcode': 'ksm',
  'shortname': 'KSM',
  'symbol': 'KSM',
  'feeMeta': {
    'code': 'dot',
    'decimals': 12,
    'symbol': 'KSM',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const manta: IServerNetwork = {
  'chainId': 'manta',
  'code': 'dot-manta',
  'decimals': 18,
  'id': 'dot--manta',
  'impl': 'dot',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/manta-atlantic.png',
  'name': 'Manta Atlantic',
  'shortcode': 'manta',
  'shortname': 'MANTA',
  'symbol': 'MANTA',
  'feeMeta': {
    'code': 'manta',
    'decimals': 18,
    'symbol': 'MANTA',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const joystream: IServerNetwork = {
  'chainId': 'joystream',
  'code': 'dot-joystream',
  'decimals': 10,
  'id': 'dot--joystream',
  'impl': 'dot',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/joystream.png',
  'name': 'Joystream',
  'shortcode': 'joy',
  'shortname': 'JOY',
  'symbol': 'JOY',
  'feeMeta': {
    'code': 'joy',
    'decimals': 10,
    'symbol': 'JOY',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const kaspa: IServerNetwork = {
  'chainId': 'kaspa',
  'code': 'kaspa',
  'decimals': 8,
  'id': 'kaspa--kaspa',
  'impl': 'kaspa',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/kas.png',
  'name': 'Kaspa',
  'shortcode': 'kaspa',
  'shortname': 'KAS',
  'symbol': 'KAS',
  'feeMeta': {
    'code': 'kaspa',
    'decimals': 8,
    'symbol': 'KAS',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const cfx: IServerNetwork = {
  'chainId': '1029',
  'code': 'cfx',
  'decimals': 18,
  'extensions': {
    'position': 14,
  },
  'id': 'cfx--1029',
  'impl': 'cfx',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/cfx.png',
  'name': 'Conflux',
  'shortcode': 'cfx',
  'shortname': 'CFX',
  'symbol': 'CFX',
  'feeMeta': {
    'code': 'cfx',
    'decimals': 18,
    'symbol': 'CFX',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const nexa: IServerNetwork = {
  'chainId': '0',
  'code': 'nexa',
  'decimals': 2,
  'id': 'nexa--0',
  'impl': 'nexa',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/nexa.png',
  'name': 'Nexa',
  'shortcode': 'nexa',
  'shortname': 'Nexa',
  'symbol': 'NEX',
  'feeMeta': {
    'code': 'nexa',
    'decimals': 2,
    'symbol': 'NEX',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const dnx: IServerNetwork = {
  'chainId': '0',
  'code': 'dnx',
  'decimals': 9,
  'id': 'dynex--0',
  'impl': 'dynex',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/dynex.png',
  'name': 'Dynex',
  'shortcode': 'dnx',
  'shortname': 'DNX',
  'symbol': 'DNX',
  'feeMeta': {
    'code': 'dnx',
    'decimals': 9,
    'symbol': 'DNX',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const sui: IServerNetwork = {
  'chainId': 'mainnet',
  'code': 'sui',
  'decimals': 9,
  'id': 'sui--mainnet',
  'impl': 'sui',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/sui.png',
  'name': 'SUI',
  'shortcode': 'sui',
  'shortname': 'SUI',
  'symbol': 'SUI',
  'feeMeta': {
    'code': 'sui',
    'decimals': 9,
    'symbol': 'SUI',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const fil: IServerNetwork = {
  'chainId': '314',
  'code': 'fil',
  'decimals': 18,
  'id': 'fil--314',
  'impl': 'fil',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/fil.png',
  'name': 'Filecoin',
  'shortcode': 'fil',
  'shortname': 'FIL',
  'symbol': 'FIL',
  'feeMeta': {
    'code': 'fil',
    'decimals': 18,
    'symbol': 'FIL',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const aptos: IServerNetwork = {
  'chainId': '1',
  'code': 'apt',
  'decimals': 8,
  'id': 'aptos--1',
  'impl': 'aptos',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/apt.png',
  'name': 'Aptos',
  'shortcode': 'apt',
  'shortname': 'APT',
  'symbol': 'APT',
  'feeMeta': {
    'code': 'apt',
    'decimals': 8,
    'symbol': 'APT',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const ckb: IServerNetwork = {
  'chainId': 'nervos',
  'code': 'nervos',
  'decimals': 8,
  'id': 'nervos--mainnet',
  'impl': 'nervos',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/nervos.png',
  'name': 'Nervos',
  'shortcode': 'ckb',
  'shortname': 'CKB',
  'symbol': 'CKB',
  'feeMeta': {
    'code': 'ckb',
    'decimals': 8,
    'symbol': 'CKB',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const ton: IServerNetwork = {
  'chainId': '607',
  'code': 'ton',
  'decimals': 9,
  'id': 'ton--mainnet',
  'impl': 'ton',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/ton.png',
  'name': 'TON',
  'shortcode': 'ton',
  'shortname': 'ton',
  'symbol': 'TON',
  'feeMeta': {
    'code': 'TON',
    'decimals': 9,
    'symbol': 'TON',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const scdo: IServerNetwork = {
  'chainId': '541',
  'code': 'scdo',
  'decimals': 8,
  'id': 'scdo--net1',
  'impl': 'scdo',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/scdo.png',
  'name': 'SCDO',
  'shortcode': 'scdo',
  'shortname': 'SCDO',
  'symbol': 'SCDO',
  'feeMeta': {
    'code': 'scdo',
    'decimals': 8,
    'symbol': 'SCDO',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const alph: IServerNetwork = {
  'chainId': 'alph--mainnet',
  'code': 'alph',
  'decimals': 18,
  'id': 'alph--mainnet',
  'impl': 'alph',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/alph.png',
  'name': 'Alephium',
  'shortcode': 'alph',
  'shortname': 'alph',
  'symbol': 'ALPH',
  'feeMeta': {
    'code': 'ALPH',
    'decimals': 18,
    'symbol': 'ALPH',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const benfen: IServerNetwork = {
  'chainId': 'mainnet',
  'code': 'bfc',
  'decimals': 9,
  'id': 'bfc--mainnet',
  'impl': 'bfc',
  'isTestnet': false,
  'logoURI': 'https://uni.onekey-asset.com/static/chain/bfc.png',
  'name': 'BenFen',
  'shortcode': 'bfc',
  'shortname': 'BFC',
  'symbol': 'BFC',
  'feeMeta': {
    'code': 'bfc',
    'decimals': 9,
    'symbol': 'BFC',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

const chainsOnlyEnabledInDev = [
  tatom, // Cosmos Testnet
];

export const presetNetworksMap = {
  // btc & btc fork
  btc,
  doge,
  bch,
  ltc,
  neurai,
  tbtc,
  sbtc,

  // evm
  eth,
  bsc,
  polygon,
  fantom,
  arbitrum,
  avalanche,
  okt,
  optimism,
  xdai,
  celo,
  zksyncera,
  zklinknova,
  opbnb,
  zora,
  zetachain,
  okb,
  wemix,
  taiko,
  scr,
  ronin,
  pulse,
  polygonzkevm,
  octa,
  moonbeam,
  mode,
  mvm,
  metis,
  merlinmainnet,
  mantle,
  mantapacific,
  linea,
  kaia,
  kava,
  iotex,
  harmony,
  flare,
  fevm,
  ethw,
  sepolia,
  etc,
  ace,
  dymension,
  dis,
  cyeth,
  cronos,
  core,
  cfxespace,
  b2,
  bouncebit,
  boba,
  blast,
  btr,
  base,
  bob,
  aurora,
  holesky,
  zircuit,
  neox,
  azero,

  // cosmos
  celestia,
  secret,
  juno,
  fetchai,
  cryptoorgchain,
  akash,
  osmosis,
  cosmoshub,
  // polkadot
  polkadot,
  astar,
  kusama,
  manta,
  joystream,

  aptos,
  lightning,
  tlightning,
  cardano,
  ripple,
  nostr,
  near,
  tron,
  cfx,
  sol,
  nexa,
  kaspa,
  dnx,
  fil,
  algo,
  sui,
  ckb,
  tatom,
  alph,
  ton,
  scdo,
  benfen,
};

const bbnTestnet: IServerNetwork = {
  'chainId': 'bbn-test-5',
  'code': 'ubbn',
  'decimals': 6,
  'id': 'cosmos--bbn-test-5',
  'impl': 'cosmos',
  'isTestnet': true,
  'logoURI': 'https://uni.onekey-asset.com/static/logo/babylon.png',
  'name': 'Babylon Testnet',
  'shortcode': 'bbn',
  'shortname': 'BBN',
  'symbol': 'BBN',
  'feeMeta': {
    'code': 'ubbn',
    'decimals': 6,
    'symbol': 'UBBN',
  },
  'defaultEnabled': false,
  'status': ENetworkStatus.LISTED,
};

// top 20 tvl evm networks
export const getDefaultEnabledEVMNetworksInAllNetworks = memoFn(
  (): IServerNetwork[] => [
    eth,
    bsc,
    base,
    arbitrum,
    avalanche,
    polygon,
    core,
    optimism,
    blast,
    mantle,
    cronos,
    linea,
    btr,
    pulse,
    scr,
    mode,
    xdai,
    b2,
    bob,
    zircuit,
  ],
);

export const getPresetNetworks = memoFn((): IServerNetwork[] => [
  dangerAllNetworkRepresent,
  // btc & btc fork
  btc,
  doge,
  bch,
  ltc,
  neurai,
  tbtc,
  sbtc,
  // evm
  eth,
  bsc,
  polygon,
  fantom,
  arbitrum,
  avalanche,
  okt,
  optimism,
  xdai,
  celo,
  zksyncera,
  zklinknova,
  opbnb,
  zora,
  zetachain,
  okb,
  wemix,
  taiko,
  scr,
  ronin,
  pulse,
  polygonzkevm,
  octa,
  moonbeam,
  mode,
  mvm,
  metis,
  merlinmainnet,
  mantle,
  mantapacific,
  linea,
  kaia,
  kava,
  iotex,
  harmony,
  flare,
  fevm,
  ethw,
  sepolia,
  etc,
  ace,
  dymension,
  dis,
  cyeth,
  cronos,
  core,
  cfxespace,
  b2,
  bouncebit,
  boba,
  blast,
  btr,
  base,
  bob,
  aurora,
  holesky,
  zircuit,
  neox,
  azero,
  dtc,
  // cosmos
  celestia,
  secret,
  juno,
  fetchai,
  cryptoorgchain,
  akash,
  osmosis,
  cosmoshub,
  bbnTestnet,

  // polkadot
  polkadot,
  astar,
  kusama,
  manta,
  joystream,

  aptos,
  lightning,
  tlightning,
  cardano,
  ripple,
  nostr,
  near,
  tron,
  cfx,
  sol,
  nexa,
  kaspa,
  dnx,
  fil,
  algo,
  sui,
  ckb,
  alph,
  ton,
  scdo,
  benfen,
  ...(platformEnv.isDev ? chainsOnlyEnabledInDev : []),
]);
