/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable spellcheck/spell-checker */
import { memoFn } from '@onekeyhq/shared/src/utils/cacheUtils';
import type { IServerNetwork } from '@onekeyhq/shared/types';
import { ENetworkStatus } from '@onekeyhq/shared/types';

import platformEnv from '../platformEnv';

// dangerNetwork represents a virtual network
export const dangerAllNetworkRepresent: IServerNetwork = {
  'chainId': '0',
  'code': 'onekeyall',
  'decimals': 0,
  'id': 'onekeyall--0',
  'impl': 'onekeyall',
  'isTestnet': false,
  'isAllNetworks': true,
  'logoURI': 'https://uni.onekey-asset.com/static/logo/chain_selector_logo.png',
  'name': 'All Networks',
  'shortcode': 'onekeyall',
  'shortname': 'onekeyall',
  'symbol': 'ALL NETWORKS',
  'feeMeta': {
    'code': '',
    'decimals': 0,
    'symbol': '0',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};
// EVM networks

const eth: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1',
  'id': 'evm--1',
  'name': 'Ethereum',
  'symbol': 'ETH',
  'code': 'eth',
  'shortcode': 'eth',
  'shortname': 'ETH',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': true,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 1,
    'isTokenSupported': true,
    'isNFTEnabled': true,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/eth.png',
  'defaultEnabled': true,
  'backendIndex': true,
};

const sepolia: IServerNetwork = {
  'impl': 'evm',
  'chainId': '11155111',
  'id': 'evm--11155111',
  'name': 'Ethereum Sepolia Testnet',
  'symbol': 'TETH',
  'code': 'sepolia',
  'shortcode': 'sepolia',
  'shortname': 'Sepolia',
  'decimals': 18,
  'feeMeta': {
    'code': 'sepolia',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': true,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI':
    'https://uni.onekey-asset.com/static/chain/ethereum-sepolia-testnet.png',
  'defaultEnabled': false,
  'backendIndex': true,
};

const optimism: IServerNetwork = {
  'impl': 'evm',
  'chainId': '10',
  'id': 'evm--10',
  'name': 'Optimism',
  'symbol': 'ETH',
  'code': 'optimism',
  'shortcode': 'optimism',
  'shortname': 'Optimism',
  'decimals': 18,
  'feeMeta': {
    'code': 'optimism',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': true,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 11,
    'isTokenSupported': true,
    'isNFTEnabled': true,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/optimism.png',
  'defaultEnabled': true,
  'backendIndex': true,
};

const xdai: IServerNetwork = {
  'impl': 'evm',
  'chainId': '100',
  'id': 'evm--100',
  'name': 'Gnosis Chain',
  'symbol': 'xDAI',
  'code': 'xdai',
  'shortcode': 'xdai',
  'shortname': 'GNO',
  'decimals': 18,
  'feeMeta': {
    'code': 'xdai',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 12,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/gno.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const ethw: IServerNetwork = {
  'impl': 'evm',
  'chainId': '10001',
  'id': 'evm--10001',
  'name': 'EthereumPoW',
  'symbol': 'ETHW',
  'code': 'ethw',
  'shortcode': 'ethw',
  'shortname': 'ETHW',
  'decimals': 18,
  'feeMeta': {
    'code': 'ethw',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/ethw.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const cfxespace: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1030',
  'id': 'evm--1030',
  'name': 'Conflux eSpace',
  'symbol': 'CFX',
  'code': 'cfxespace',
  'shortcode': 'cfxespace',
  'shortname': 'CFXESPACE',
  'decimals': 18,
  'feeMeta': {
    'code': 'cfxespace',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/conflux-espace.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const aurora: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1313161554',
  'id': 'evm--1313161554',
  'name': 'Aurora',
  'symbol': 'ETH',
  'code': 'aurora',
  'shortcode': 'aurora',
  'shortname': 'Aurora',
  'decimals': 18,
  'feeMeta': {
    'code': 'aurora',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/aurora.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const polygon: IServerNetwork = {
  'impl': 'evm',
  'chainId': '137',
  'id': 'evm--137',
  'name': 'Polygon',
  'symbol': 'MATIC',
  'code': 'polygon',
  'shortcode': 'polygon',
  'shortname': 'Polygon',
  'decimals': 18,
  'feeMeta': {
    'code': 'polygon',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': true,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 5,
    'isTokenSupported': true,
    'isNFTEnabled': true,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/polygon.png',
  'defaultEnabled': true,
  'backendIndex': true,
};

const cronos: IServerNetwork = {
  'impl': 'evm',
  'chainId': '25',
  'id': 'evm--25',
  'name': 'Cronos',
  'symbol': 'CRO',
  'code': 'cronos',
  'shortcode': 'cronos',
  'shortname': 'CRO',
  'decimals': 18,
  'feeMeta': {
    'code': 'cronos',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/cronos.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const fantom: IServerNetwork = {
  'impl': 'evm',
  'chainId': '250',
  'id': 'evm--250',
  'name': 'Fantom',
  'symbol': 'FTM',
  'code': 'fantom',
  'shortcode': 'fantom',
  'shortname': 'FTM',
  'decimals': 18,
  'feeMeta': {
    'code': 'fantom',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 6,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/fantom.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const boba: IServerNetwork = {
  'impl': 'evm',
  'chainId': '288',
  'id': 'evm--288',
  'name': 'Boba Network',
  'symbol': 'ETH',
  'code': 'boba',
  'shortcode': 'boba',
  'shortname': 'Boba',
  'decimals': 18,
  'feeMeta': {
    'code': 'boba',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': true,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/boba_1.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const fevm: IServerNetwork = {
  'impl': 'evm',
  'chainId': '314',
  'id': 'evm--314',
  'name': 'Filecoin FEVM',
  'symbol': 'FIL',
  'code': 'fevm',
  'shortcode': 'fevm',
  'shortname': 'FEVM',
  'decimals': 18,
  'feeMeta': {
    'code': 'fevm',
    'decimals': 9,
    'symbol': 'Gwei',
    'maxSendFeeUpRatio': 1.1,
    'isEIP1559FeeEnabled': true,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/filecoin-fevm.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const zksyncera: IServerNetwork = {
  'impl': 'evm',
  'chainId': '324',
  'id': 'evm--324',
  'name': 'zkSync Era Mainnet',
  'symbol': 'ETH',
  'code': 'zksyncera',
  'shortcode': 'zksyncera',
  'shortname': 'ZKSYNCERA',
  'decimals': 18,
  'feeMeta': {
    'code': 'zksyncera',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/zksync-era-mainnet.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const arbitrum: IServerNetwork = {
  'impl': 'evm',
  'chainId': '42161',
  'id': 'evm--42161',
  'name': 'Arbitrum',
  'symbol': 'ETH',
  'code': 'arbitrum',
  'shortcode': 'arbitrum',
  'shortname': 'Arbitrum',
  'decimals': 18,
  'feeMeta': {
    'code': 'arbitrum',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 7,
    'isTokenSupported': true,
    'isNFTEnabled': true,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/arbitrum.png',
  'defaultEnabled': true,
  'backendIndex': true,
};

const celo: IServerNetwork = {
  'impl': 'evm',
  'chainId': '42220',
  'id': 'evm--42220',
  'name': 'Celo',
  'symbol': 'CELO',
  'code': 'celo',
  'shortcode': 'celo',
  'shortname': 'CELO',
  'decimals': 18,
  'feeMeta': {
    'code': 'celo',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 16,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/celo.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const avalanche: IServerNetwork = {
  'impl': 'evm',
  'chainId': '43114',
  'id': 'evm--43114',
  'name': 'Avalanche',
  'symbol': 'AVAX',
  'code': 'avalanche',
  'shortcode': 'avalanche',
  'shortname': 'Avalanche',
  'decimals': 18,
  'feeMeta': {
    'code': 'avalanche',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 8,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/avalanche.png',
  'defaultEnabled': true,
  'backendIndex': true,
};

const dis: IServerNetwork = {
  'impl': 'evm',
  'chainId': '513100',
  'id': 'evm--513100',
  'name': 'DIS CHAIN',
  'symbol': 'DIS',
  'code': 'dis',
  'shortcode': 'dis',
  'shortname': 'DIS',
  'decimals': 18,
  'feeMeta': {
    'code': 'dis',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/etf.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const bsc: IServerNetwork = {
  'impl': 'evm',
  'chainId': '56',
  'id': 'evm--56',
  'name': 'BNB Smart Chain',
  'symbol': 'BNB',
  'code': 'bsc',
  'shortcode': 'bsc',
  'shortname': 'BSC',
  'decimals': 18,
  'feeMeta': {
    'code': 'bsc',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 4,
    'isTokenSupported': true,
    'isNFTEnabled': true,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/bsc.png',
  'defaultEnabled': true,
  'backendIndex': true,
};

const etc: IServerNetwork = {
  'impl': 'evm',
  'chainId': '61',
  'id': 'evm--61',
  'name': 'Ethereum Classic',
  'symbol': 'ETC',
  'code': 'etc',
  'shortcode': 'etc',
  'shortname': 'ETC',
  'decimals': 18,
  'feeMeta': {
    'code': 'etc',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/etc.png',
  'defaultEnabled': true,
  'backendIndex': true,
};

const okt: IServerNetwork = {
  'impl': 'evm',
  'chainId': '66',
  'id': 'evm--66',
  'name': 'OKX Chain',
  'symbol': 'OKT',
  'code': 'okt',
  'shortcode': 'okt',
  'shortname': 'OKC',
  'decimals': 18,
  'feeMeta': {
    'code': 'okt',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 10,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/okx-chain.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const mvm: IServerNetwork = {
  'impl': 'evm',
  'chainId': '73927',
  'id': 'evm--73927',
  'name': 'Mixin Virtual Machine',
  'symbol': 'ETH',
  'code': 'mvm',
  'shortcode': 'mvm',
  'shortname': 'MVM',
  'decimals': 18,
  'feeMeta': {
    'code': 'mvm',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI':
    'https://uni.onekey-asset.com/static/chain/mixin-virtual-machine.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const linea: IServerNetwork = {
  'impl': 'evm',
  'chainId': '59144',
  'id': 'evm--59144',
  'name': 'Linea',
  'symbol': 'ETH',
  'code': 'linea',
  'shortcode': 'linea',
  'shortname': 'Linea',
  'decimals': 18,
  'feeMeta': {
    'code': 'Linea',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/linea.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const base: IServerNetwork = {
  'impl': 'evm',
  'chainId': '8453',
  'id': 'evm--8453',
  'name': 'Base',
  'symbol': 'ETH',
  'code': 'base',
  'shortcode': 'base',
  'shortname': 'Base',
  'decimals': 18,
  'feeMeta': {
    'code': 'base',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': true,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/base.png',
  'defaultEnabled': true,
  'backendIndex': true,
};

const mantle: IServerNetwork = {
  'impl': 'evm',
  'chainId': '5000',
  'id': 'evm--5000',
  'name': 'Mantle',
  'symbol': 'MNT',
  'code': 'mantle',
  'shortcode': 'mantle',
  'shortname': 'Mantle',
  'decimals': 18,
  'feeMeta': {
    'code': 'mantle',
    'decimals': 9,
    'symbol': 'Gwei',
    'maxSendFeeUpRatio': 1.2,
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/mantle.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const iotex: IServerNetwork = {
  'impl': 'evm',
  'chainId': '4689',
  'id': 'evm--4689',
  'name': 'IoTeX Network Mainnet',
  'symbol': 'IOTX',
  'code': 'iotex',
  'shortcode': 'iotex',
  'shortname': 'iotex',
  'decimals': 18,
  'feeMeta': {
    'code': 'iotex',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI':
    'https://uni.onekey-asset.com/static/logo/IoTeXNetworkMainnet.webp',
  'defaultEnabled': true,
  'backendIndex': false,
};

const mantapacific: IServerNetwork = {
  'impl': 'evm',
  'chainId': '169',
  'id': 'evm--169',
  'name': 'Manta Pacific Mainnet',
  'symbol': 'MANTASPACIFIC',
  'code': 'mantapacific',
  'shortcode': 'mantapacific',
  'shortname': 'mantapacific',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'ETH',
    'maxSendFeeUpRatio': 1.2,
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI':
    'https://uni.onekey-asset.com/static/chain/manta-pacific-mainnet.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const blast: IServerNetwork = {
  'impl': 'evm',
  'chainId': '81457',
  'id': 'evm--81457',
  'name': 'Blast',
  'symbol': 'BLAST',
  'code': 'blast',
  'shortcode': 'blast',
  'shortname': 'blast',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'ETH',
    'maxSendFeeUpRatio': 1.2,
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/logo/blast.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const octa: IServerNetwork = {
  'impl': 'evm',
  'chainId': '800001',
  'id': 'evm--800001',
  'name': 'OctaSpace',
  'symbol': 'OCTA',
  'code': 'octa',
  'shortcode': 'octa',
  'shortname': 'octa',
  'decimals': 18,
  'feeMeta': {
    'code': 'octa',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/octa.webp',
  'defaultEnabled': true,
  'backendIndex': false,
};

const polygonzkevm: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1101',
  'id': 'evm--1101',
  'name': 'Polygon Zkevm',
  'symbol': 'ETH',
  'code': 'polygonzkevm',
  'shortcode': 'polygonzkevm',
  'shortname': 'polygonzkevm',
  'decimals': 18,
  'feeMeta': {
    'code': 'polygonzkevm',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/polygon-zkevm.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const okb: IServerNetwork = {
  'impl': 'evm',
  'chainId': '196',
  'id': 'evm--196',
  'name': 'X Layer Mainnet',
  'symbol': 'OKB',
  'code': 'okb',
  'shortcode': 'okb',
  'shortname': 'okb',
  'decimals': 18,
  'feeMeta': {
    'code': 'okb',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/okb.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const core: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1116',
  'id': 'evm--1116',
  'name': 'Core Blockchain Mainnet',
  'symbol': 'CORE',
  'code': 'core',
  'shortcode': 'core',
  'shortname': 'core',
  'decimals': 18,
  'feeMeta': {
    'code': 'core',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/core.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const klaytn: IServerNetwork = {
  'impl': 'evm',
  'chainId': '8217',
  'id': 'evm--8217',
  'name': 'Klaytn Mainnet Cypress',
  'symbol': 'KLAY',
  'code': 'klaytn',
  'shortcode': 'klaytn',
  'shortname': 'Cypress',
  'decimals': 18,
  'feeMeta': {
    'code': 'klay',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': '',
  'defaultEnabled': true,
  'backendIndex': false,
};

const metis: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1088',
  'id': 'evm--1088',
  'name': 'Metis Andromeda Mainnet',
  'symbol': 'METIS',
  'code': 'metis',
  'shortcode': 'metis',
  'shortname': 'metis-andromeda',
  'decimals': 18,
  'feeMeta': {
    'code': 'metis',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': '',
  'defaultEnabled': true,
  'backendIndex': false,
};

const moonbeam: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1284',
  'id': 'evm--1284',
  'name': 'Moonbeam',
  'symbol': 'GLMR',
  'code': 'moonbeam',
  'shortcode': 'moonbeam',
  'shortname': 'mbeam',
  'decimals': 18,
  'feeMeta': {
    'code': 'glmr',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': '',
  'defaultEnabled': true,
  'backendIndex': false,
};

const ronin: IServerNetwork = {
  'impl': 'evm',
  'chainId': '2020',
  'id': 'evm--2020',
  'name': 'Ronin',
  'symbol': 'RON',
  'code': 'ronin',
  'shortcode': 'ronin',
  'shortname': 'ronin',
  'decimals': 18,
  'feeMeta': {
    'code': 'ron',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/ronin.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const harmony: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1666600000',
  'id': 'evm--1666600000',
  'name': 'Harmony Mainnet Shard 0',
  'symbol': 'ONE',
  'code': 'harmony',
  'shortcode': 'harmony',
  'shortname': 'hmy-s0',
  'decimals': 18,
  'feeMeta': {
    'code': 'one',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': '',
  'defaultEnabled': true,
  'backendIndex': false,
};

const hmys1: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1666600001',
  'id': 'evm--1666600001',
  'name': 'Harmony Mainnet Shard 1',
  'symbol': 'ONE',
  'code': 'hmy-s1',
  'shortcode': 'hmy-s1',
  'shortname': 'hmy-s1',
  'decimals': 18,
  'feeMeta': {
    'code': 'one',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': '',
  'defaultEnabled': true,
  'backendIndex': false,
};

const flare: IServerNetwork = {
  'impl': 'evm',
  'chainId': '14',
  'id': 'evm--14',
  'name': 'Flare Mainnet',
  'symbol': 'FLR',
  'code': 'flare',
  'shortcode': 'flare',
  'shortname': 'flr',
  'decimals': 18,
  'feeMeta': {
    'code': 'flr',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/flare.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const kava: IServerNetwork = {
  'impl': 'evm',
  'chainId': '2222',
  'id': 'evm--2222',
  'name': 'Kava',
  'symbol': 'KAVA',
  'code': 'kava',
  'shortcode': 'kava',
  'shortname': 'kava',
  'decimals': 18,
  'feeMeta': {
    'code': 'kava',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/kava.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const pulse: IServerNetwork = {
  'impl': 'evm',
  'chainId': '369',
  'id': 'evm--369',
  'name': 'PulseChain',
  'symbol': 'PLS',
  'code': 'pulse',
  'shortcode': 'pulse',
  'shortname': 'pls',
  'decimals': 18,
  'feeMeta': {
    'code': 'pls',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': '',
  'defaultEnabled': true,
  'backendIndex': false,
};

const opbnb: IServerNetwork = {
  'impl': 'evm',
  'chainId': '204',
  'id': 'evm--204',
  'name': 'opBNB Mainnet',
  'symbol': 'BNB',
  'code': 'op_bnb',
  'shortcode': 'op_bnb',
  'shortname': 'obnb',
  'decimals': 18,
  'feeMeta': {
    'code': 'bnb',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/op_bnb.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const scr: IServerNetwork = {
  'impl': 'evm',
  'chainId': '534352',
  'id': 'evm--534352',
  'name': 'Scroll',
  'symbol': 'ETH',
  'code': 'scr',
  'shortcode': 'scr',
  'shortname': 'scr',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': '',
  'defaultEnabled': true,
  'backendIndex': false,
};

const wemix: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1111',
  'id': 'evm--1111',
  'name': 'WEMIX3.0 Mainnet',
  'symbol': 'WEMIX',
  'code': 'wemix',
  'shortcode': 'wemix',
  'shortname': 'wemix',
  'decimals': 18,
  'feeMeta': {
    'code': 'wemix',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': '',
  'defaultEnabled': true,
  'backendIndex': false,
};

const merlinmainnet: IServerNetwork = {
  'impl': 'evm',
  'chainId': '4200',
  'id': 'evm--4200',
  'name': 'Merlin Mainnet',
  'symbol': 'BTC',
  'code': 'merlin-mainnet',
  'shortcode': 'merlin-mainnet',
  'shortname': 'Merlin-Mainnet',
  'decimals': 18,
  'feeMeta': {
    'code': 'btc',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/merlin-mainnet.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const taiko: IServerNetwork = {
  'impl': 'evm',
  'chainId': '167000',
  'id': 'evm--167000',
  'name': 'Taiko Mainnet',
  'symbol': 'ETH',
  'code': 'taiko',
  'shortcode': 'taiko',
  'shortname': 'tko-mainnet',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/taiko.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const bob: IServerNetwork = {
  'impl': 'evm',
  'chainId': '60808',
  'id': 'evm--60808',
  'name': 'BOB',
  'symbol': 'ETH',
  'code': 'bob',
  'shortcode': 'bob',
  'shortname': 'bob',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/bob.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const zora: IServerNetwork = {
  'impl': 'evm',
  'chainId': '7777777',
  'id': 'evm--7777777',
  'name': 'Zora',
  'symbol': 'ETH',
  'code': 'zora',
  'shortcode': 'zora',
  'shortname': 'zora',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/zora.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const zetachain: IServerNetwork = {
  'impl': 'evm',
  'chainId': '7000',
  'id': 'evm--7000',
  'name': 'ZetaChain Mainnet',
  'symbol': 'ZETA',
  'code': 'zetachain',
  'shortcode': 'zetachain',
  'shortname': 'zetachain-mainnet',
  'decimals': 18,
  'feeMeta': {
    'code': 'zeta',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/zetachain.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const dymension: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1100',
  'id': 'evm--1100',
  'name': 'Dymension',
  'symbol': 'DYM',
  'code': 'dymension',
  'shortcode': 'dymension',
  'shortname': 'dymension',
  'decimals': 18,
  'feeMeta': {
    'code': 'dym',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/dymension.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const mode: IServerNetwork = {
  'impl': 'evm',
  'chainId': '34443',
  'id': 'evm--34443',
  'name': 'Mode',
  'symbol': 'ETH',
  'code': 'mode',
  'shortcode': 'mode',
  'shortname': 'mode',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/mode.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const zklinknova: IServerNetwork = {
  'impl': 'evm',
  'chainId': '810180',
  'id': 'evm--810180',
  'name': 'zkLink Nova Mainnet',
  'symbol': 'ETH',
  'code': 'zklink-nova',
  'shortcode': 'zklink-nova',
  'shortname': 'zklink-nova',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/zklink-nova.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const btr: IServerNetwork = {
  'impl': 'evm',
  'chainId': '200901',
  'id': 'evm--200901',
  'name': 'Bitlayer Mainnet',
  'symbol': 'BTC',
  'code': 'btr',
  'shortcode': 'btr',
  'shortname': 'btr',
  'decimals': 18,
  'feeMeta': {
    'code': 'btc',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/btr.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const cyeth: IServerNetwork = {
  'impl': 'evm',
  'chainId': '7560',
  'id': 'evm--7560',
  'name': 'Cyber Mainnet',
  'symbol': 'ETH',
  'code': 'cyeth',
  'shortcode': 'cyeth',
  'shortname': 'cyeth',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/cyeth.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const bouncebit: IServerNetwork = {
  'impl': 'evm',
  'chainId': '6001',
  'id': 'evm--6001',
  'name': 'BounceBit Mainnet',
  'symbol': 'BB',
  'code': 'bouncebit',
  'shortcode': 'bouncebit',
  'shortname': 'bouncebit-mainnet',
  'decimals': 18,
  'feeMeta': {
    'code': 'bb',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/bouncebit.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

const ace: IServerNetwork = {
  'impl': 'evm',
  'chainId': '648',
  'id': 'evm--648',
  'name': 'Endurance Smart Chain Mainnet',
  'symbol': 'ACE',
  'code': 'ace',
  'shortcode': 'ace',
  'shortname': 'ace',
  'decimals': 18,
  'feeMeta': {
    'code': 'ace',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': '',
  'defaultEnabled': true,
  'backendIndex': false,
};

const chainsOnlyEnabledInDev: IServerNetwork[] = [
  // Add your dev-only chains here
];

export const presetNetworksMap = {
  eth,
  sepolia,
  optimism,
  xdai,
  ethw,
  cfxespace,
  aurora,
  polygon,
  cronos,
  fantom,
  boba,
  fevm,
  zksyncera,
  arbitrum,
  celo,
  avalanche,
  dis,
  bsc,
  etc,
  okt,
  mvm,
  linea,
  base,
  mantle,
  iotex,
  mantapacific,
  blast,
  octa,
  polygonzkevm,
  okb,
  core,
  klaytn,
  metis,
  moonbeam,
  ronin,
  harmony,
  hmys1,
  flare,
  kava,
  pulse,
  opbnb,
  scr,
  wemix,
  merlinmainnet,
  taiko,
  bob,
  zora,
  zetachain,
  dymension,
  mode,
  zklinknova,
  btr,
  cyeth,
  bouncebit,
  ace,
};

export const getPresetNetworks = memoFn((): IServerNetwork[] => [
  dangerAllNetworkRepresent,
  eth,
  sepolia,
  optimism,
  xdai,
  ethw,
  cfxespace,
  aurora,
  polygon,
  cronos,
  fantom,
  boba,
  fevm,
  zksyncera,
  arbitrum,
  celo,
  avalanche,
  dis,
  bsc,
  etc,
  okt,
  mvm,
  linea,
  base,
  mantle,
  iotex,
  mantapacific,
  blast,
  octa,
  polygonzkevm,
  okb,
  core,
  klaytn,
  metis,
  moonbeam,
  ronin,
  harmony,
  hmys1,
  flare,
  kava,
  pulse,
  opbnb,
  scr,
  wemix,
  merlinmainnet,
  taiko,
  bob,
  zora,
  zetachain,
  dymension,
  mode,
  zklinknova,
  btr,
  cyeth,
  bouncebit,
  ace,
  ...(platformEnv.isDev ? chainsOnlyEnabledInDev : []),
]);
