/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable spellcheck/spell-checker */
import { memoFn } from '@onekeyhq/shared/src/utils/cacheUtils';
import type { IServerNetwork } from '@onekeyhq/shared/types';
import { ENetworkStatus } from '@onekeyhq/shared/types';

import platformEnv from '../platformEnv';

// dangerNetwork represents a virtual network
export const dangerAllNetworkRepresent: IServerNetwork = {
  'chainId': '0',
  'code': 'onekeyall',
  'decimals': 0,
  'id': 'onekeyall--0',
  'impl': 'onekeyall',
  'isTestnet': false,
  'isAllNetworks': true,
  'logoURI': 'https://uni.onekey-asset.com/static/logo/chain_selector_logo.png',
  'name': 'All Networks',
  'shortcode': 'onekeyall',
  'shortname': 'onekeyall',
  'symbol': 'ALL NETWORKS',
  'feeMeta': {
    'code': '',
    'decimals': 0,
    'symbol': '0',
  },
  'defaultEnabled': true,
  'status': ENetworkStatus.LISTED,
};

// ADA networks
const ada: IServerNetwork = {
  'impl': 'ada',
  'chainId': '0',
  'id': 'ada--0',
  'name': 'Cardano',
  'symbol': 'ADA',
  'code': 'ada',
  'shortcode': 'ada',
  'shortname': 'Cardano',
  'decimals': 6,
  'feeMeta': {
    'code': 'ada',
    'decimals': 6,
    'symbol': 'ADA',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/ada.png',
  'defaultEnabled': true,
};

// ALGO networks
const algo: IServerNetwork = {
  'impl': 'algo',
  'chainId': '4160',
  'id': 'algo--4160',
  'name': 'Algorand',
  'symbol': 'ALGO',
  'code': 'algo',
  'shortcode': 'algo',
  'shortname': 'ALGO',
  'decimals': 6,
  'feeMeta': {
    'code': 'algo',
    'decimals': 6,
    'symbol': 'ALGO',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 15,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/algo.png',
  'defaultEnabled': true,
};

// APTOS networks
const apt: IServerNetwork = {
  'impl': 'aptos',
  'chainId': '1',
  'id': 'aptos--1',
  'name': 'Aptos',
  'symbol': 'APT',
  'code': 'apt',
  'shortcode': 'apt',
  'shortname': 'APT',
  'decimals': 8,
  'feeMeta': {
    'code': 'apt',
    'decimals': 8,
    'symbol': 'APT',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/apt.png',
  'defaultEnabled': true,
};

// BCH networks
const bch: IServerNetwork = {
  'impl': 'bch',
  'chainId': '0',
  'id': 'bch--0',
  'name': 'Bitcoin Cash',
  'symbol': 'BCH',
  'code': 'bch',
  'shortcode': 'bch',
  'shortname': 'BCH',
  'decimals': 8,
  'feeMeta': {
    'code': 'sat',
    'decimals': 0,
    'symbol': 'sat',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/bch.png',
  'defaultEnabled': true,
  'backendIndex': true,
};

// BTC networks
const btc: IServerNetwork = {
  'impl': 'btc',
  'chainId': '0',
  'id': 'btc--0',
  'name': 'Bitcoin',
  'symbol': 'BTC',
  'code': 'btc',
  'shortcode': 'btc',
  'shortname': 'BTC',
  'decimals': 8,
  'feeMeta': {
    'code': 'sat',
    'decimals': 0,
    'symbol': 'sat',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 1,
    'isTokenSupported': false,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/btc.png',
  'defaultEnabled': true,
  'backendIndex': true,
};

// CFX networks
const cfx: IServerNetwork = {
  'impl': 'cfx',
  'chainId': '1029',
  'id': 'cfx--1029',
  'name': 'Conflux',
  'symbol': 'CFX',
  'code': 'cfx',
  'shortcode': 'cfx',
  'shortname': 'CFX',
  'decimals': 18,
  'feeMeta': {
    'code': 'cfx',
    'decimals': 18,
    'symbol': 'CFX',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 14,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/cfx.png',
  'defaultEnabled': true,
};

// COSMOS networks
const secretnetwork: IServerNetwork = {
  'impl': 'cosmos',
  'chainId': 'secret-4',
  'id': 'cosmos--secret-4',
  'name': 'Secret Network',
  'symbol': 'SCRT',
  'code': 'secretnetwork',
  'shortcode': 'secretnetwork',
  'shortname': 'Secret Network',
  'decimals': 6,
  'feeMeta': {
    'code': 'uscrt',
    'decimals': 0,
    'symbol': 'uscrt',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/secret.png',
  'defaultEnabled': true,
};
const osmosis: IServerNetwork = {
  'impl': 'cosmos',
  'chainId': 'osmosis-1',
  'id': 'cosmos--osmosis-1',
  'name': 'Osmosis',
  'symbol': 'OSMO',
  'code': 'osmosis',
  'shortcode': 'osmosis',
  'shortname': 'Osmosis',
  'decimals': 6,
  'feeMeta': {
    'code': 'uosmo',
    'decimals': 0,
    'symbol': 'uosmo',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/osmosis.png',
  'defaultEnabled': true,
};
const juno: IServerNetwork = {
  'impl': 'cosmos',
  'chainId': 'juno-1',
  'id': 'cosmos--juno-1',
  'name': 'Juno',
  'symbol': 'JUNO',
  'code': 'juno',
  'shortcode': 'juno',
  'shortname': 'Juno',
  'decimals': 6,
  'feeMeta': {
    'code': 'ujuno',
    'decimals': 0,
    'symbol': 'ujuno',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/juno.png',
  'defaultEnabled': true,
};
const fetch: IServerNetwork = {
  'impl': 'cosmos',
  'chainId': 'fetchhub-4',
  'id': 'cosmos--fetchhub-4',
  'name': 'Fetch.ai',
  'symbol': 'FET',
  'code': 'fetch',
  'shortcode': 'fetch',
  'shortname': 'Fetch.ai',
  'decimals': 18,
  'feeMeta': {
    'code': 'afet',
    'decimals': 0,
    'symbol': 'afet',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/fetch.png',
  'defaultEnabled': true,
};
const cryptoorgchain: IServerNetwork = {
  'impl': 'cosmos',
  'chainId': 'crypto-org-chain-mainnet-1',
  'id': 'cosmos--crypto-org-chain-mainnet-1',
  'name': 'Crypto.org',
  'symbol': 'CRO',
  'code': 'cryptoorgchain',
  'shortcode': 'cryptoorgchain',
  'shortname': 'Crypto.org',
  'decimals': 8,
  'feeMeta': {
    'code': 'basecro',
    'decimals': 0,
    'symbol': 'basecro',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/cryptoorg.png',
  'defaultEnabled': true,
};
const cosmoshub: IServerNetwork = {
  'impl': 'cosmos',
  'chainId': 'cosmoshub-4',
  'id': 'cosmos--cosmoshub-4',
  'name': 'Cosmos',
  'symbol': 'ATOM',
  'code': 'cosmoshub',
  'shortcode': 'cosmoshub',
  'shortname': 'Cosmos',
  'decimals': 6,
  'feeMeta': {
    'code': 'uatom',
    'decimals': 0,
    'symbol': 'uatom',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/cosmos.png',
  'defaultEnabled': true,
};
const celestia: IServerNetwork = {
  'impl': 'cosmos',
  'chainId': 'celestia',
  'id': 'cosmos--celestia',
  'name': 'Celestia',
  'symbol': 'TIA',
  'code': 'celestia',
  'shortcode': 'celestia',
  'shortname': 'Celestia',
  'decimals': 6,
  'feeMeta': {
    'code': 'utia',
    'decimals': 0,
    'symbol': 'utia',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/celestia.png',
  'defaultEnabled': true,
};
const akash: IServerNetwork = {
  'impl': 'cosmos',
  'chainId': 'akashnet-2',
  'id': 'cosmos--akashnet-2',
  'name': 'Akash',
  'symbol': 'AKT',
  'code': 'akash',
  'shortcode': 'akash',
  'shortname': 'Akash',
  'decimals': 6,
  'feeMeta': {
    'code': 'uakt',
    'decimals': 0,
    'symbol': 'uakt',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/akash.png',
  'defaultEnabled': true,
};

// DOGE networks
const doge: IServerNetwork = {
  'impl': 'doge',
  'chainId': '0',
  'id': 'doge--0',
  'name': 'Dogecoin',
  'symbol': 'DOGE',
  'code': 'doge',
  'shortcode': 'doge',
  'shortname': 'DOGE',
  'decimals': 8,
  'feeMeta': {
    'code': 'sat',
    'decimals': 0,
    'symbol': 'sat',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/doge.png',
  'defaultEnabled': true,
  'backendIndex': true,
};

// DOT networks
const dot: IServerNetwork = {
  'impl': 'dot',
  'chainId': 'polkadot',
  'id': 'dot--polkadot',
  'name': 'Polkadot',
  'symbol': 'DOT',
  'code': 'dot',
  'shortcode': 'dot',
  'shortname': 'DOT',
  'decimals': 10,
  'feeMeta': {
    'code': 'DOT',
    'decimals': 10,
    'symbol': 'DOT',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': false,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/polkadot.png',
  'defaultEnabled': true,
};
const manta: IServerNetwork = {
  'impl': 'dot',
  'chainId': 'manta',
  'id': 'dot--manta',
  'name': 'Manta Atlantic',
  'symbol': 'MANTA',
  'code': 'dot-manta',
  'shortcode': 'manta',
  'shortname': 'MANTA',
  'decimals': 18,
  'feeMeta': {
    'code': 'manta',
    'decimals': 18,
    'symbol': 'MANTA',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': false,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/manta-atlantic.png',
  'defaultEnabled': true,
};
const ksm: IServerNetwork = {
  'impl': 'dot',
  'chainId': 'kusama',
  'id': 'dot--kusama',
  'name': 'Kusama',
  'symbol': 'KSM',
  'code': 'ksm',
  'shortcode': 'ksm',
  'shortname': 'KSM',
  'decimals': 12,
  'feeMeta': {
    'code': 'ksm',
    'decimals': 12,
    'symbol': 'KSM',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': false,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/kusama.png',
  'defaultEnabled': true,
};
const joy: IServerNetwork = {
  'impl': 'dot',
  'chainId': 'joystream',
  'id': 'dot--joystream',
  'name': 'Joystream',
  'symbol': 'JOY',
  'code': 'dot-joystream',
  'shortcode': 'joy',
  'shortname': 'JOY',
  'decimals': 10,
  'feeMeta': {
    'code': 'joy',
    'decimals': 10,
    'symbol': 'JOY',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': false,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/joystream.png',
  'defaultEnabled': true,
};
const astar: IServerNetwork = {
  'impl': 'dot',
  'chainId': 'astar',
  'id': 'dot--astar',
  'name': 'Astar',
  'symbol': 'ASTR',
  'code': 'astar',
  'shortcode': 'astar',
  'shortname': 'ASTR',
  'decimals': 18,
  'feeMeta': {
    'code': 'astar',
    'decimals': 18,
    'symbol': 'ASTR',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': false,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/astar.png',
  'defaultEnabled': true,
};

// DYNEX networks
const dnx: IServerNetwork = {
  'impl': 'dynex',
  'chainId': '0',
  'id': 'dynex--0',
  'name': 'Dynex',
  'symbol': 'DNX',
  'code': 'dnx',
  'shortcode': 'dnx',
  'shortname': 'DNX',
  'decimals': 9,
  'feeMeta': {
    'code': 'dnx',
    'decimals': 9,
    'symbol': 'DNX',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': false,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/dynex.png',
  'defaultEnabled': true,
};

// EVM networks
const eth: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1',
  'id': 'evm--1',
  'name': 'Ethereum',
  'symbol': 'ETH',
  'code': 'eth',
  'shortcode': 'eth',
  'shortname': 'ETH',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': true,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 3,
    'isTokenSupported': true,
    'isNFTEnabled': true,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/eth.png',
  'defaultEnabled': true,
  'backendIndex': true,
};
const bsc: IServerNetwork = {
  'impl': 'evm',
  'chainId': '56',
  'id': 'evm--56',
  'name': 'BNB Smart Chain',
  'symbol': 'BNB',
  'code': 'bsc',
  'shortcode': 'bsc',
  'shortname': 'BSC',
  'decimals': 18,
  'feeMeta': {
    'code': 'bsc',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 4,
    'isTokenSupported': true,
    'isNFTEnabled': true,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/bsc.png',
  'defaultEnabled': true,
  'backendIndex': true,
};
const polygon: IServerNetwork = {
  'impl': 'evm',
  'chainId': '137',
  'id': 'evm--137',
  'name': 'Polygon',
  'symbol': 'MATIC',
  'code': 'polygon',
  'shortcode': 'polygon',
  'shortname': 'Polygon',
  'decimals': 18,
  'feeMeta': {
    'code': 'polygon',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': true,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 5,
    'isTokenSupported': true,
    'isNFTEnabled': true,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/polygon.png',
  'defaultEnabled': true,
  'backendIndex': true,
};
const fantom: IServerNetwork = {
  'impl': 'evm',
  'chainId': '250',
  'id': 'evm--250',
  'name': 'Fantom',
  'symbol': 'FTM',
  'code': 'fantom',
  'shortcode': 'fantom',
  'shortname': 'FTM',
  'decimals': 18,
  'feeMeta': {
    'code': 'fantom',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 6,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/fantom.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const arbitrum: IServerNetwork = {
  'impl': 'evm',
  'chainId': '42161',
  'id': 'evm--42161',
  'name': 'Arbitrum',
  'symbol': 'ETH',
  'code': 'arbitrum',
  'shortcode': 'arbitrum',
  'shortname': 'Arbitrum',
  'decimals': 18,
  'feeMeta': {
    'code': 'arbitrum',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 7,
    'isTokenSupported': true,
    'isNFTEnabled': true,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/arbitrum.png',
  'defaultEnabled': true,
  'backendIndex': true,
};
const avalanche: IServerNetwork = {
  'impl': 'evm',
  'chainId': '43114',
  'id': 'evm--43114',
  'name': 'Avalanche',
  'symbol': 'AVAX',
  'code': 'avalanche',
  'shortcode': 'avalanche',
  'shortname': 'Avalanche',
  'decimals': 18,
  'feeMeta': {
    'code': 'avalanche',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 8,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/avalanche.png',
  'defaultEnabled': true,
  'backendIndex': true,
};
const okt: IServerNetwork = {
  'impl': 'evm',
  'chainId': '66',
  'id': 'evm--66',
  'name': 'OKX Chain',
  'symbol': 'OKT',
  'code': 'okt',
  'shortcode': 'okt',
  'shortname': 'OKC',
  'decimals': 18,
  'feeMeta': {
    'code': 'okt',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 10,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/okx-chain.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const optimism: IServerNetwork = {
  'impl': 'evm',
  'chainId': '10',
  'id': 'evm--10',
  'name': 'Optimism',
  'symbol': 'ETH',
  'code': 'optimism',
  'shortcode': 'optimism',
  'shortname': 'Optimism',
  'decimals': 18,
  'feeMeta': {
    'code': 'optimism',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': true,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 11,
    'isTokenSupported': true,
    'isNFTEnabled': true,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/optimism.png',
  'defaultEnabled': true,
  'backendIndex': true,
};
const xdai: IServerNetwork = {
  'impl': 'evm',
  'chainId': '100',
  'id': 'evm--100',
  'name': 'Gnosis Chain',
  'symbol': 'xDAI',
  'code': 'xdai',
  'shortcode': 'xdai',
  'shortname': 'GNO',
  'decimals': 18,
  'feeMeta': {
    'code': 'xdai',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 12,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/gno.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const celo: IServerNetwork = {
  'impl': 'evm',
  'chainId': '42220',
  'id': 'evm--42220',
  'name': 'Celo',
  'symbol': 'CELO',
  'code': 'celo',
  'shortcode': 'celo',
  'shortname': 'CELO',
  'decimals': 18,
  'feeMeta': {
    'code': 'celo',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 16,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/celo.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const zksyncera: IServerNetwork = {
  'impl': 'evm',
  'chainId': '324',
  'id': 'evm--324',
  'name': 'zkSync Era Mainnet',
  'symbol': 'ETH',
  'code': 'zksyncera',
  'shortcode': 'zksyncera',
  'shortname': 'ZKSYNCERA',
  'decimals': 18,
  'feeMeta': {
    'code': 'zksyncera',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/zksync-era-mainnet.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const zklinknova: IServerNetwork = {
  'impl': 'evm',
  'chainId': '810180',
  'id': 'evm--810180',
  'name': 'zkLink Nova Mainnet',
  'symbol': 'ETH',
  'code': 'zklinknova',
  'shortcode': 'zklinknova',
  'shortname': 'zklink-nova',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/zklink-nova.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const opbnb: IServerNetwork = {
  'impl': 'evm',
  'chainId': '204',
  'id': 'evm--204',
  'name': 'opBNB Mainnet',
  'symbol': 'BNB',
  'code': 'opbnb',
  'shortcode': 'opbnb',
  'shortname': 'obnb',
  'decimals': 18,
  'feeMeta': {
    'code': 'bnb',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/op_bnb.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const zora: IServerNetwork = {
  'impl': 'evm',
  'chainId': '7777777',
  'id': 'evm--7777777',
  'name': 'Zora',
  'symbol': 'ETH',
  'code': 'zora',
  'shortcode': 'zora',
  'shortname': 'zora',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/zora.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const zetachain: IServerNetwork = {
  'impl': 'evm',
  'chainId': '7000',
  'id': 'evm--7000',
  'name': 'ZetaChain Mainnet',
  'symbol': 'ZETA',
  'code': 'zetachain',
  'shortcode': 'zetachain',
  'shortname': 'zetachain-mainnet',
  'decimals': 18,
  'feeMeta': {
    'code': 'zeta',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/zetachain.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const okb: IServerNetwork = {
  'impl': 'evm',
  'chainId': '196',
  'id': 'evm--196',
  'name': 'X Layer Mainnet',
  'symbol': 'OKB',
  'code': 'okb',
  'shortcode': 'okb',
  'shortname': 'okb',
  'decimals': 18,
  'feeMeta': {
    'code': 'okb',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/okb.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const wemix: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1111',
  'id': 'evm--1111',
  'name': 'WEMIX3.0 Mainnet',
  'symbol': 'WEMIX',
  'code': 'wemix',
  'shortcode': 'wemix',
  'shortname': 'wemix',
  'decimals': 18,
  'feeMeta': {
    'code': 'wemix',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': '',
  'defaultEnabled': true,
  'backendIndex': false,
};
const taiko: IServerNetwork = {
  'impl': 'evm',
  'chainId': '167000',
  'id': 'evm--167000',
  'name': 'Taiko Mainnet',
  'symbol': 'ETH',
  'code': 'taiko',
  'shortcode': 'taiko',
  'shortname': 'tko-mainnet',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/taiko.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const scr: IServerNetwork = {
  'impl': 'evm',
  'chainId': '534352',
  'id': 'evm--534352',
  'name': 'Scroll',
  'symbol': 'ETH',
  'code': 'scr',
  'shortcode': 'scr',
  'shortname': 'scr',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': '',
  'defaultEnabled': true,
  'backendIndex': false,
};
const ronin: IServerNetwork = {
  'impl': 'evm',
  'chainId': '2020',
  'id': 'evm--2020',
  'name': 'Ronin',
  'symbol': 'RON',
  'code': 'ronin',
  'shortcode': 'ronin',
  'shortname': 'ronin',
  'decimals': 18,
  'feeMeta': {
    'code': 'ron',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/ronin.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const pulse: IServerNetwork = {
  'impl': 'evm',
  'chainId': '369',
  'id': 'evm--369',
  'name': 'PulseChain',
  'symbol': 'PLS',
  'code': 'pulse',
  'shortcode': 'pulse',
  'shortname': 'pls',
  'decimals': 18,
  'feeMeta': {
    'code': 'pls',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': '',
  'defaultEnabled': true,
  'backendIndex': false,
};
const polygonzkevm: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1101',
  'id': 'evm--1101',
  'name': 'Polygon Zkevm',
  'symbol': 'ETH',
  'code': 'polygonzkevm',
  'shortcode': 'polygonzkevm',
  'shortname': 'polygonzkevm',
  'decimals': 18,
  'feeMeta': {
    'code': 'polygonzkevm',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/polygon-zkevm.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const octa: IServerNetwork = {
  'impl': 'evm',
  'chainId': '800001',
  'id': 'evm--800001',
  'name': 'OctaSpace',
  'symbol': 'OCTA',
  'code': 'octa',
  'shortcode': 'octa',
  'shortname': 'octa',
  'decimals': 18,
  'feeMeta': {
    'code': 'octa',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/octa.webp',
  'defaultEnabled': true,
  'backendIndex': false,
};
const moonbeam: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1284',
  'id': 'evm--1284',
  'name': 'Moonbeam',
  'symbol': 'GLMR',
  'code': 'moonbeam',
  'shortcode': 'moonbeam',
  'shortname': 'mbeam',
  'decimals': 18,
  'feeMeta': {
    'code': 'glmr',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': '',
  'defaultEnabled': true,
  'backendIndex': false,
};
const mode: IServerNetwork = {
  'impl': 'evm',
  'chainId': '34443',
  'id': 'evm--34443',
  'name': 'Mode',
  'symbol': 'ETH',
  'code': 'mode',
  'shortcode': 'mode',
  'shortname': 'mode',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/mode.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const mvm: IServerNetwork = {
  'impl': 'evm',
  'chainId': '73927',
  'id': 'evm--73927',
  'name': 'Mixin Virtual Machine',
  'symbol': 'ETH',
  'code': 'mvm',
  'shortcode': 'mvm',
  'shortname': 'MVM',
  'decimals': 18,
  'feeMeta': {
    'code': 'mvm',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI':
    'https://uni.onekey-asset.com/static/chain/mixin-virtual-machine.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const metis: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1088',
  'id': 'evm--1088',
  'name': 'Metis Andromeda Mainnet',
  'symbol': 'METIS',
  'code': 'metis',
  'shortcode': 'metis',
  'shortname': 'metis-andromeda',
  'decimals': 18,
  'feeMeta': {
    'code': 'metis',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': '',
  'defaultEnabled': true,
  'backendIndex': false,
};
const merlinmainnet: IServerNetwork = {
  'impl': 'evm',
  'chainId': '4200',
  'id': 'evm--4200',
  'name': 'Merlin Mainnet',
  'symbol': 'BTC',
  'code': 'merlinmainnet',
  'shortcode': 'merlinmainnet',
  'shortname': 'Merlin-Mainnet',
  'decimals': 18,
  'feeMeta': {
    'code': 'btc',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/merlin-mainnet.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const mantle: IServerNetwork = {
  'impl': 'evm',
  'chainId': '5000',
  'id': 'evm--5000',
  'name': 'Mantle',
  'symbol': 'MNT',
  'code': 'mantle',
  'shortcode': 'mantle',
  'shortname': 'Mantle',
  'decimals': 18,
  'feeMeta': {
    'code': 'mantle',
    'decimals': 9,
    'symbol': 'Gwei',
    'maxSendFeeUpRatio': 1.2,
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/mantle.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const mantapacific: IServerNetwork = {
  'impl': 'evm',
  'chainId': '169',
  'id': 'evm--169',
  'name': 'Manta Pacific Mainnet',
  'symbol': 'MANTASPACIFIC',
  'code': 'mantapacific',
  'shortcode': 'mantapacific',
  'shortname': 'mantapacific',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'ETH',
    'maxSendFeeUpRatio': 1.2,
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI':
    'https://uni.onekey-asset.com/static/chain/manta-pacific-mainnet.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const linea: IServerNetwork = {
  'impl': 'evm',
  'chainId': '59144',
  'id': 'evm--59144',
  'name': 'Linea',
  'symbol': 'ETH',
  'code': 'linea',
  'shortcode': 'linea',
  'shortname': 'Linea',
  'decimals': 18,
  'feeMeta': {
    'code': 'Linea',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/linea.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const klaytn: IServerNetwork = {
  'impl': 'evm',
  'chainId': '8217',
  'id': 'evm--8217',
  'name': 'Klaytn Mainnet Cypress',
  'symbol': 'KLAY',
  'code': 'klaytn',
  'shortcode': 'klaytn',
  'shortname': 'Cypress',
  'decimals': 18,
  'feeMeta': {
    'code': 'klay',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': '',
  'defaultEnabled': true,
  'backendIndex': false,
};
const kava: IServerNetwork = {
  'impl': 'evm',
  'chainId': '2222',
  'id': 'evm--2222',
  'name': 'Kava',
  'symbol': 'KAVA',
  'code': 'kava',
  'shortcode': 'kava',
  'shortname': 'kava',
  'decimals': 18,
  'feeMeta': {
    'code': 'kava',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/kava.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const iotex: IServerNetwork = {
  'impl': 'evm',
  'chainId': '4689',
  'id': 'evm--4689',
  'name': 'IoTeX Network Mainnet',
  'symbol': 'IOTX',
  'code': 'iotex',
  'shortcode': 'iotex',
  'shortname': 'iotex',
  'decimals': 18,
  'feeMeta': {
    'code': 'iotex',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI':
    'https://uni.onekey-asset.com/static/logo/IoTeXNetworkMainnet.webp',
  'defaultEnabled': true,
  'backendIndex': false,
};
const hmys1: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1666600001',
  'id': 'evm--1666600001',
  'name': 'Harmony Mainnet Shard 1',
  'symbol': 'ONE',
  'code': 'hmys1',
  'shortcode': 'hmys1',
  'shortname': 'hmy-s1',
  'decimals': 18,
  'feeMeta': {
    'code': 'one',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': '',
  'defaultEnabled': true,
  'backendIndex': false,
};
const harmony: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1666600000',
  'id': 'evm--1666600000',
  'name': 'Harmony Mainnet Shard 0',
  'symbol': 'ONE',
  'code': 'harmony',
  'shortcode': 'harmony',
  'shortname': 'hmy-s0',
  'decimals': 18,
  'feeMeta': {
    'code': 'one',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': '',
  'defaultEnabled': true,
  'backendIndex': false,
};
const flare: IServerNetwork = {
  'impl': 'evm',
  'chainId': '14',
  'id': 'evm--14',
  'name': 'Flare Mainnet',
  'symbol': 'FLR',
  'code': 'flare',
  'shortcode': 'flare',
  'shortname': 'flr',
  'decimals': 18,
  'feeMeta': {
    'code': 'flr',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/flare.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const fevm: IServerNetwork = {
  'impl': 'evm',
  'chainId': '314',
  'id': 'evm--314',
  'name': 'Filecoin FEVM',
  'symbol': 'FIL',
  'code': 'fevm',
  'shortcode': 'fevm',
  'shortname': 'FEVM',
  'decimals': 18,
  'feeMeta': {
    'code': 'fevm',
    'decimals': 9,
    'symbol': 'Gwei',
    'maxSendFeeUpRatio': 1.1,
    'isEIP1559FeeEnabled': true,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/filecoin-fevm.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const ethw: IServerNetwork = {
  'impl': 'evm',
  'chainId': '10001',
  'id': 'evm--10001',
  'name': 'EthereumPoW',
  'symbol': 'ETHW',
  'code': 'ethw',
  'shortcode': 'ethw',
  'shortname': 'ETHW',
  'decimals': 18,
  'feeMeta': {
    'code': 'ethw',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/ethw.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const sepolia: IServerNetwork = {
  'impl': 'evm',
  'chainId': '11155111',
  'id': 'evm--11155111',
  'name': 'Ethereum Sepolia Testnet',
  'symbol': 'TETH',
  'code': 'sepolia',
  'shortcode': 'sepolia',
  'shortname': 'Sepolia',
  'decimals': 18,
  'feeMeta': {
    'code': 'sepolia',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': true,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI':
    'https://uni.onekey-asset.com/static/chain/ethereum-sepolia-testnet.png',
  'defaultEnabled': false,
  'backendIndex': true,
};
const etc: IServerNetwork = {
  'impl': 'evm',
  'chainId': '61',
  'id': 'evm--61',
  'name': 'Ethereum Classic',
  'symbol': 'ETC',
  'code': 'etc',
  'shortcode': 'etc',
  'shortname': 'ETC',
  'decimals': 18,
  'feeMeta': {
    'code': 'etc',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/etc.png',
  'defaultEnabled': true,
  'backendIndex': true,
};
const ace: IServerNetwork = {
  'impl': 'evm',
  'chainId': '648',
  'id': 'evm--648',
  'name': 'Endurance Smart Chain Mainnet',
  'symbol': 'ACE',
  'code': 'ace',
  'shortcode': 'ace',
  'shortname': 'ace',
  'decimals': 18,
  'feeMeta': {
    'code': 'ace',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': '',
  'defaultEnabled': true,
  'backendIndex': false,
};
const dymension: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1100',
  'id': 'evm--1100',
  'name': 'Dymension',
  'symbol': 'DYM',
  'code': 'dymension',
  'shortcode': 'dymension',
  'shortname': 'dymension',
  'decimals': 18,
  'feeMeta': {
    'code': 'dym',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/dymension.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const dis: IServerNetwork = {
  'impl': 'evm',
  'chainId': '513100',
  'id': 'evm--513100',
  'name': 'DIS CHAIN',
  'symbol': 'DIS',
  'code': 'dis',
  'shortcode': 'dis',
  'shortname': 'DIS',
  'decimals': 18,
  'feeMeta': {
    'code': 'dis',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/etf.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const cyeth: IServerNetwork = {
  'impl': 'evm',
  'chainId': '7560',
  'id': 'evm--7560',
  'name': 'Cyber Mainnet',
  'symbol': 'ETH',
  'code': 'cyeth',
  'shortcode': 'cyeth',
  'shortname': 'cyeth',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/cyeth.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const cronos: IServerNetwork = {
  'impl': 'evm',
  'chainId': '25',
  'id': 'evm--25',
  'name': 'Cronos',
  'symbol': 'CRO',
  'code': 'cronos',
  'shortcode': 'cronos',
  'shortname': 'CRO',
  'decimals': 18,
  'feeMeta': {
    'code': 'cronos',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/cronos.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const core: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1116',
  'id': 'evm--1116',
  'name': 'Core Blockchain Mainnet',
  'symbol': 'CORE',
  'code': 'core',
  'shortcode': 'core',
  'shortname': 'core',
  'decimals': 18,
  'feeMeta': {
    'code': 'core',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/core.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const cfxespace: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1030',
  'id': 'evm--1030',
  'name': 'Conflux eSpace',
  'symbol': 'CFX',
  'code': 'cfxespace',
  'shortcode': 'cfxespace',
  'shortname': 'CFXESPACE',
  'decimals': 18,
  'feeMeta': {
    'code': 'cfxespace',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/conflux-espace.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const bouncebit: IServerNetwork = {
  'impl': 'evm',
  'chainId': '6001',
  'id': 'evm--6001',
  'name': 'BounceBit Mainnet',
  'symbol': 'BB',
  'code': 'bouncebit',
  'shortcode': 'bouncebit',
  'shortname': 'bouncebit-mainnet',
  'decimals': 18,
  'feeMeta': {
    'code': 'bb',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/bouncebit.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const boba: IServerNetwork = {
  'impl': 'evm',
  'chainId': '288',
  'id': 'evm--288',
  'name': 'Boba Network',
  'symbol': 'ETH',
  'code': 'boba',
  'shortcode': 'boba',
  'shortname': 'Boba',
  'decimals': 18,
  'feeMeta': {
    'code': 'boba',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': true,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/boba_1.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const blast: IServerNetwork = {
  'impl': 'evm',
  'chainId': '81457',
  'id': 'evm--81457',
  'name': 'Blast',
  'symbol': 'BLAST',
  'code': 'blast',
  'shortcode': 'blast',
  'shortname': 'blast',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'ETH',
    'maxSendFeeUpRatio': 1.2,
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/logo/blast.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const btr: IServerNetwork = {
  'impl': 'evm',
  'chainId': '200901',
  'id': 'evm--200901',
  'name': 'Bitlayer Mainnet',
  'symbol': 'BTC',
  'code': 'btr',
  'shortcode': 'btr',
  'shortname': 'btr',
  'decimals': 18,
  'feeMeta': {
    'code': 'btc',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/btr.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const base: IServerNetwork = {
  'impl': 'evm',
  'chainId': '8453',
  'id': 'evm--8453',
  'name': 'Base',
  'symbol': 'ETH',
  'code': 'base',
  'shortcode': 'base',
  'shortname': 'Base',
  'decimals': 18,
  'feeMeta': {
    'code': 'base',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': true,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/base.png',
  'defaultEnabled': true,
  'backendIndex': true,
};
const bob: IServerNetwork = {
  'impl': 'evm',
  'chainId': '60808',
  'id': 'evm--60808',
  'name': 'BOB',
  'symbol': 'ETH',
  'code': 'bob',
  'shortcode': 'bob',
  'shortname': 'bob',
  'decimals': 18,
  'feeMeta': {
    'code': 'eth',
    'decimals': 9,
    'symbol': 'Gwei',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/bob.png',
  'defaultEnabled': true,
  'backendIndex': false,
};
const aurora: IServerNetwork = {
  'impl': 'evm',
  'chainId': '1313161554',
  'id': 'evm--1313161554',
  'name': 'Aurora',
  'symbol': 'ETH',
  'code': 'aurora',
  'shortcode': 'aurora',
  'shortname': 'Aurora',
  'decimals': 18,
  'feeMeta': {
    'code': 'aurora',
    'decimals': 9,
    'symbol': 'Gwei',
    'isEIP1559FeeEnabled': false,
    'isWithL1BaseFee': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 9999,
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/aurora.png',
  'defaultEnabled': true,
  'backendIndex': false,
};

// FIL networks
const fil: IServerNetwork = {
  'impl': 'fil',
  'chainId': '314',
  'id': 'fil--314',
  'name': 'Filecoin',
  'symbol': 'FIL',
  'code': 'fil',
  'shortcode': 'fil',
  'shortname': 'FIL',
  'decimals': 18,
  'feeMeta': {
    'code': 'attoFil',
    'decimals': 0,
    'symbol': 'attoFil',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': false,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/fil.png',
  'defaultEnabled': true,
};

// KASPA networks
const kaspa: IServerNetwork = {
  'impl': 'kaspa',
  'chainId': 'kaspa',
  'id': 'kaspa--kaspa',
  'name': 'Kaspa',
  'symbol': 'KAS',
  'code': 'kaspa',
  'shortcode': 'kaspa',
  'shortname': 'KAS',
  'decimals': 8,
  'feeMeta': {
    'code': 'kaspa',
    'decimals': 8,
    'symbol': 'KAS',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': false,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/kas.png',
  'defaultEnabled': true,
};

// LIGHTNING networks
const lightning: IServerNetwork = {
  'impl': 'lightning',
  'chainId': '0',
  'id': 'lightning--0',
  'name': 'Lightning Network',
  'symbol': 'sats',
  'code': 'lightning',
  'shortcode': 'lightning',
  'shortname': 'Lightning',
  'decimals': 0,
  'feeMeta': {
    'code': 'lightning',
    'decimals': 0,
    'symbol': 'sats',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 2,
    'isTokenSupported': false,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/lnd.png',
  'defaultEnabled': true,
};

// LTC networks
const ltc: IServerNetwork = {
  'impl': 'ltc',
  'chainId': '0',
  'id': 'ltc--0',
  'name': 'Litecoin',
  'symbol': 'LTC',
  'code': 'ltc',
  'shortcode': 'ltc',
  'shortname': 'LTC',
  'decimals': 8,
  'feeMeta': {
    'code': 'sat',
    'decimals': 0,
    'symbol': 'sat',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/ltc.png',
  'defaultEnabled': true,
  'backendIndex': true,
};

// NEAR networks
const near: IServerNetwork = {
  'impl': 'near',
  'chainId': '0',
  'id': 'near--0',
  'name': 'Near',
  'symbol': 'NEAR',
  'code': 'near',
  'shortcode': 'near',
  'shortname': 'Near',
  'decimals': 24,
  'feeMeta': {
    'code': 'near',
    'decimals': 24,
    'symbol': 'NEAR',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/near.png',
  'defaultEnabled': true,
};

// NERVOS networks
const ckb: IServerNetwork = {
  'impl': 'nervos',
  'chainId': 'nervos',
  'id': 'nervos--mainnet',
  'name': 'Nervos',
  'symbol': 'CKB',
  'code': 'nervos',
  'shortcode': 'ckb',
  'shortname': 'CKB',
  'decimals': 8,
  'feeMeta': {
    'code': 'ckb',
    'decimals': 8,
    'symbol': 'CKB',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/nervos.png',
  'defaultEnabled': true,
};

// NEURAI networks
const xna: IServerNetwork = {
  'impl': 'neurai',
  'chainId': '0',
  'id': 'neurai--0',
  'name': 'Neurai',
  'symbol': 'XNA',
  'code': 'neurai',
  'shortcode': 'xna',
  'shortname': 'XNA',
  'decimals': 8,
  'feeMeta': {
    'code': 'xna',
    'decimals': 0,
    'symbol': 'XNA',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': false,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/neurai.png',
  'defaultEnabled': true,
};

// NEXA networks
const nexa: IServerNetwork = {
  'impl': 'nexa',
  'chainId': '0',
  'id': 'nexa--0',
  'name': 'Nexa',
  'symbol': 'NEX',
  'code': 'nexa',
  'shortcode': 'nexa',
  'shortname': 'Nexa',
  'decimals': 2,
  'feeMeta': {
    'code': 'nexa',
    'decimals': 2,
    'symbol': 'NEX',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': false,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/nexa.png',
  'defaultEnabled': true,
};

// NOSTR networks
const nostr: IServerNetwork = {
  'impl': 'nostr',
  'chainId': '0',
  'id': 'nostr--0',
  'name': 'Nostr',
  'symbol': 'Nostr',
  'code': 'nostr',
  'shortcode': 'nostr',
  'shortname': 'Nostr',
  'decimals': 0,
  'feeMeta': {
    'symbol': 'nostr',
    'decimals': 0,
    'code': 'nostr',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': false,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/nostr.png',
  'defaultEnabled': true,
};

// SCDO networks
const scdo: IServerNetwork = {
  'impl': 'scdo',
  'chainId': 'net1',
  'id': 'scdo--net1',
  'name': 'Scdo',
  'symbol': 'SCDO',
  'code': 'scdo',
  'shortcode': 'scdo',
  'shortname': 'SCDO',
  'decimals': 8,
  'feeMeta': {
    'symbol': 'SCDO',
    'decimals': 8,
    'code': 'scdo',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': false,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/token/scdo--net1/native.png',
  'defaultEnabled': true,
};

// SOL networks
const sol: IServerNetwork = {
  'impl': 'sol',
  'chainId': '101',
  'id': 'sol--101',
  'name': 'Solana',
  'symbol': 'SOL',
  'code': 'sol',
  'shortcode': 'sol',
  'shortname': 'SOL',
  'decimals': 9,
  'feeMeta': {
    'code': 'sol',
    'decimals': 9,
    'symbol': 'SOL',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'position': 4,
    'isTokenSupported': true,
    'isNFTEnabled': true,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/sol.png',
  'defaultEnabled': true,
};

// SUI networks
const sui: IServerNetwork = {
  'impl': 'sui',
  'chainId': 'mainnet',
  'id': 'sui--mainnet',
  'name': 'SUI',
  'symbol': 'SUI',
  'code': 'sui',
  'shortcode': 'sui',
  'shortname': 'SUI',
  'decimals': 9,
  'feeMeta': {
    'code': 'sui',
    'decimals': 9,
    'symbol': 'SUI',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/sui.png',
  'defaultEnabled': true,
};

// TBTC networks
const tbtc: IServerNetwork = {
  'impl': 'tbtc',
  'chainId': '0',
  'id': 'tbtc--0',
  'name': 'Bitcoin Testnet',
  'symbol': 'TBTC',
  'code': 'tbtc',
  'shortcode': 'tbtc',
  'shortname': 'TBTC',
  'decimals': 8,
  'feeMeta': {
    'code': 'sat',
    'decimals': 0,
    'symbol': 'sat',
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': true,
  'extensions': {
    'isTokenSupported': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/bitcoin-testnet.png',
  'defaultEnabled': false,
};
const sbtc: IServerNetwork = {
  'impl': 'tbtc',
  'chainId': '0',
  'id': 'tbtc--1',
  'name': 'Bitcoin Signet',
  'symbol': 'SBTC',
  'code': 'sbtc',
  'shortcode': 'sbtc',
  'shortname': 'SBTC',
  'decimals': 8,
  'feeMeta': {
    'code': 'sat',
    'decimals': 0,
    'symbol': 'sat',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': true,
  'extensions': {
    'isTokenSupported': false,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/sbtc.png',
  'defaultEnabled': false,
};

// TLIGHTNING networks
const tlightning: IServerNetwork = {
  'impl': 'tlightning',
  'chainId': '0',
  'id': 'tlightning--0',
  'name': 'Lightning Network Testnet',
  'symbol': 'sats',
  'code': 'tlightning',
  'shortcode': 'tlightning',
  'shortname': 'LightningTestnet',
  'decimals': 0,
  'feeMeta': {
    'code': 'lightning',
    'decimals': 0,
    'symbol': 'sats',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': true,
  'extensions': {
    'isTokenSupported': false,
    'isNFTEnabled': false,
  },
  'logoURI':
    'https://uni.onekey-asset.com/static/chain/lightning-network-testnet.png',
  'defaultEnabled': false,
};

// TRON networks
const trx: IServerNetwork = {
  'impl': 'tron',
  'chainId': '0x2b6653dc',
  'id': 'tron--0x2b6653dc',
  'name': 'Tron',
  'symbol': 'TRX',
  'code': 'trx',
  'shortcode': 'trx',
  'shortname': 'TRX',
  'decimals': 6,
  'feeMeta': {
    'code': 'trx',
    'decimals': 6,
    'symbol': 'Gwei',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': true,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/tron.png',
  'defaultEnabled': true,
  'backendIndex': true,
};

// XRP networks
const xrp: IServerNetwork = {
  'impl': 'xrp',
  'chainId': '0',
  'id': 'xrp--0',
  'name': 'Ripple',
  'symbol': 'XRP',
  'code': 'xrp',
  'shortcode': 'xrp',
  'shortname': 'Ripple',
  'decimals': 6,
  'feeMeta': {
    'code': 'xrp',
    'decimals': 6,
    'symbol': 'XRP',
    'isWithL1BaseFee': false,
    'isEIP1559FeeEnabled': false,
  },
  'status': ENetworkStatus.LISTED,
  'isTestnet': false,
  'extensions': {
    'isTokenSupported': false,
    'isNFTEnabled': false,
  },
  'logoURI': 'https://uni.onekey-asset.com/static/chain/xrp.png',
  'defaultEnabled': true,
};

const chainsOnlyEnabledInDev: IServerNetwork[] = [
  // Add your dev-only chains here
];

export const presetNetworksMap = {
  ada,
  algo,
  apt,
  bch,
  btc,
  cfx,
  secretnetwork,
  osmosis,
  juno,
  fetch,
  cryptoorgchain,
  cosmoshub,
  celestia,
  akash,
  doge,
  dot,
  manta,
  ksm,
  joy,
  astar,
  dnx,
  eth,
  bsc,
  polygon,
  fantom,
  arbitrum,
  avalanche,
  okt,
  optimism,
  xdai,
  celo,
  zksyncera,
  zklinknova,
  opbnb,
  zora,
  zetachain,
  okb,
  wemix,
  taiko,
  scr,
  ronin,
  pulse,
  polygonzkevm,
  octa,
  moonbeam,
  mode,
  mvm,
  metis,
  merlinmainnet,
  mantle,
  mantapacific,
  linea,
  klaytn,
  kava,
  iotex,
  hmys1,
  harmony,
  flare,
  fevm,
  ethw,
  sepolia,
  etc,
  ace,
  dymension,
  dis,
  cyeth,
  cronos,
  core,
  cfxespace,
  bouncebit,
  boba,
  blast,
  btr,
  base,
  bob,
  aurora,
  fil,
  kaspa,
  lightning,
  ltc,
  near,
  ckb,
  xna,
  nexa,
  nostr,
  scdo,
  sol,
  sui,
  tbtc,
  sbtc,
  tlightning,
  trx,
  xrp,
};

export const getPresetNetworks = memoFn((): IServerNetwork[] => [
  dangerAllNetworkRepresent,
  ada,
  algo,
  apt,
  bch,
  btc,
  cfx,
  secretnetwork,
  osmosis,
  juno,
  fetch,
  cryptoorgchain,
  cosmoshub,
  celestia,
  akash,
  doge,
  dot,
  manta,
  ksm,
  joy,
  astar,
  dnx,
  eth,
  bsc,
  polygon,
  fantom,
  arbitrum,
  avalanche,
  okt,
  optimism,
  xdai,
  celo,
  zksyncera,
  zklinknova,
  opbnb,
  zora,
  zetachain,
  okb,
  wemix,
  taiko,
  scr,
  ronin,
  pulse,
  polygonzkevm,
  octa,
  moonbeam,
  mode,
  mvm,
  metis,
  merlinmainnet,
  mantle,
  mantapacific,
  linea,
  klaytn,
  kava,
  iotex,
  hmys1,
  harmony,
  flare,
  fevm,
  ethw,
  sepolia,
  etc,
  ace,
  dymension,
  dis,
  cyeth,
  cronos,
  core,
  cfxespace,
  bouncebit,
  boba,
  blast,
  btr,
  base,
  bob,
  aurora,
  fil,
  kaspa,
  lightning,
  ltc,
  near,
  ckb,
  xna,
  nexa,
  nostr,
  scdo,
  sol,
  sui,
  tbtc,
  sbtc,
  tlightning,
  trx,
  xrp,
  ...(platformEnv.isDev ? chainsOnlyEnabledInDev : []),
]);
