export const BROWSER_BOTTOM_BAR_HEIGHT = 54;
export const MIN_TOGGLE_BROWSER_VISIBLE_DISTANCE =
  BROWSER_BOTTOM_BAR_HEIGHT * 2;
export const DISPLAY_BOTTOM_BAR_DURATION = 100;
export const MAX_OPACITY_BOTTOM_BAR = 1;
export const MIN_OPACITY_BOTTOM_BAR = 0;
