# yaml-language-server: $schema=https://raw.githubusercontent.com/runkids/skillshare/main/schemas/project-config.schema.json
targets:
  - name: claude
    skills:
      mode: symlink
  - name: universal
    skills:
      mode: symlink
audit:
  block_threshold: CRITICAL
hub:
  default: vercel-agent-skills
  hubs:
    - label: vercel-skills
      url: https://skills.sh
    - label: vercel-agent-skills
      url: https://github.com/vercel-labs/agent-skills
