
auth.token=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

defaults.org=onekey-bb
defaults.project=react-native

defaults.url=https://sentry.io/
