import { useCallback, useEffect, useRef, useState } from 'react';

import type { IPageScreenProps } from '@onekeyhq/components';
import {
  Button,
  Divider,
  Input,
  Page,
  SizableText,
  Toast,
  XStack,
  YStack,
} from '@onekeyhq/components';
import backgroundApiProxy from '@onekeyhq/kit/src/background/instance/backgroundApiProxy';
import type {
  EAppUpdateRoutes,
  IAppUpdatePagesParamList,
} from '@onekeyhq/shared/src/routes';

import {
  type IFeaturedChangelogPreviewData,
  showFeaturedChangelogDialog,
} from '../dialogs/showFeaturedChangelogDialog';
import { AppUpdateTestIDs } from '../testIDs';

// Ops-only tool, reachable ONLY via the
// onekey-wallet://preview-featured-changelog deeplink generated by the admin
// dashboard (there is deliberately no in-app entry point). Lets ops verify the
// Featured Changelog they configured for a target app version inside a
// production build: the fetch overrides the request version header so the
// server's real update-selection pipeline runs for that version, and nothing is
// persisted to the app-update state.
function FeaturedChangelogPreview({
  route,
}: IPageScreenProps<
  IAppUpdatePagesParamList,
  EAppUpdateRoutes.FeaturedChangelogPreview
>) {
  const { version: versionParam } = route.params ?? {};
  const [version, setVersion] = useState(versionParam ?? '');
  const [preview, setPreview] = useState<
    IFeaturedChangelogPreviewData | undefined
  >();
  const [echo, setEcho] = useState('');
  const [loading, setLoading] = useState(false);

  const fetchPreview = useCallback(
    async (
      versionOverride?: string,
    ): Promise<IFeaturedChangelogPreviewData | undefined> => {
      const target = (versionOverride ?? version).trim();
      if (!target) {
        Toast.error({ title: 'Enter a version first' });
        return undefined;
      }
      setLoading(true);
      try {
        const res =
          await backgroundApiProxy.serviceAppUpdate.previewFeaturedChangelog({
            version: target,
          });
        if (!res.featuredChangelog) {
          setPreview(undefined);
          setEcho(`No featured changelog configured for version ${target}.`);
          return undefined;
        }
        const data: IFeaturedChangelogPreviewData = {
          featuredChangelog: res.featuredChangelog,
          latestVersion: res.version,
        };
        setPreview(data);
        setEcho(
          `Matched · version ${res.version ?? target} · ${
            res.featuredChangelog.features.length
          } feature(s).`,
        );
        return data;
      } catch (e) {
        setPreview(undefined);
        setEcho((e as Error)?.message ?? 'Request failed');
        Toast.error({
          title: 'Preview fetch failed',
          message: (e as Error)?.message,
        });
        return undefined;
      } finally {
        setLoading(false);
      }
    },
    [version],
  );

  // Auto-fetch when arriving via deeplink with a version param, so scanning
  // the dashboard QR immediately surfaces the configured content. Note:
  // re-firing the deeplink while this screen is already the top modal is
  // swallowed by pushModal's duplicate-target guard (useAppNavigation), so
  // params never change on re-fire — the operator edits the input instead.
  // This effect still guards by param value for the day that changes.
  const lastAutoFetchedParamRef = useRef<string | undefined>(undefined);
  useEffect(() => {
    const target = versionParam?.trim();
    if (target && lastAutoFetchedParamRef.current !== target) {
      lastAutoFetchedParamRef.current = target;
      setVersion(target);
      void fetchPreview(target);
    }
  }, [versionParam, fetchPreview]);

  const openPreview = useCallback(
    async (isPreInstall: boolean) => {
      const data = preview ?? (await fetchPreview());
      if (!data) return;
      showFeaturedChangelogDialog({ isPreInstall, previewData: data });
    },
    [preview, fetchPreview],
  );

  return (
    <Page scrollEnabled>
      <Page.Header title="Featured Changelog Preview" />
      <Page.Body>
        <YStack p="$5" gap="$3">
          <SizableText size="$bodySm" color="$textSubdued">
            Ops-only. Enter a target app version to fetch the Featured Changelog
            the server has configured for it, then preview both dialog states.
            Nothing here changes the app&apos;s real update state.
          </SizableText>

          <SizableText size="$bodyMdMedium">Target version</SizableText>
          <XStack gap="$2">
            <Input
              flex={1}
              testID={AppUpdateTestIDs.previewVersionInput}
              placeholder="e.g. 6.5.0"
              value={version}
              onChangeText={(text) => {
                setVersion(text);
                // Invalidate the cached fetch so a preview button can never
                // render a previously-fetched version after the input changed.
                setPreview(undefined);
                setEcho('');
              }}
            />
            <Button
              testID={AppUpdateTestIDs.previewFetchBtn}
              variant="secondary"
              loading={loading}
              onPress={() => void fetchPreview()}
            >
              Fetch
            </Button>
          </XStack>

          {echo ? (
            <YStack
              p="$3"
              gap="$1"
              borderRadius="$3"
              borderWidth={1}
              borderColor="$borderSubdued"
            >
              <SizableText size="$bodyMdMedium">Result</SizableText>
              <SizableText size="$bodySm" color="$textSubdued">
                {echo}
              </SizableText>
            </YStack>
          ) : null}

          <Divider />

          <SizableText size="$bodyMdMedium">Preview dialog</SizableText>
          <XStack gap="$2">
            <Button
              flex={1}
              variant="primary"
              testID={AppUpdateTestIDs.previewNotUpgradedBtn}
              onPress={() => void openPreview(true)}
            >
              Not upgraded yet
            </Button>
            <Button
              flex={1}
              variant="secondary"
              testID={AppUpdateTestIDs.previewUpgradedBtn}
              onPress={() => void openPreview(false)}
            >
              Already upgraded
            </Button>
          </XStack>
        </YStack>
      </Page.Body>
    </Page>
  );
}

export default FeaturedChangelogPreview;
