#!/usr/bin/env node
/**
 * 1k-cycle-scan blueprint generator.
 *
 * Builds a deterministic manifest (JSONL, path-sorted) of scannable source
 * files for the working tree the repo is currently checked out at. The same
 * commit + same rules always produce byte-identical output, so the manifest
 * never needs to be persisted — only (pinnedCommit, rulesHash, cursor).
 *
 * Usage:
 *   node manifest.mjs --repo <root> [--out /tmp/manifest.jsonl] [--stats]
 *                     [--hash] [--suspects] [--overrides overrides.json]
 *
 * Overrides JSON shape (per-dimension scope tuning):
 *   {
 *     "disableRules": ["dev-gallery"],
 *     "addExclude": [{ "id": "x", "pattern": "^apps/cli/", "reason": "..." }],
 *     "addIncludeGlobs": ["packages/**\/*.json"]
 *   }
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const INCLUDE_GLOBS = [
  'packages/**/*.ts',
  'packages/**/*.tsx',
  'apps/**/*.ts',
  'apps/**/*.tsx',
];

// Baseline exclusions, verified against the repo on 2026-06-11 (8171
// candidates -> 5628 files / ~975k lines). Each rule is individually
// addressable so a dimension can disable it via overrides.disableRules.
const BASELINE_RULES = [
  {
    id: 'apps-cli',
    pattern: '^apps/cli/',
    reason:
      'Node CLI product, not wallet runtime (re-enable via overrides.disableRules)',
  },
  {
    id: 'tests',
    pattern: '\\.(test|spec)\\.(ts|tsx)$',
    reason: 'unit/integration tests',
  },
  {
    id: 'test-dirs',
    pattern: '(^|/)__(tests?|mocks|fixtures|snapshots|test-utils)__/',
    reason: 'test support dirs',
  },
  {
    id: 'e2e-dirs',
    pattern: '(^|/)(e2e|@tests|test-utils)/',
    reason: 'e2e suites and test fixtures',
  },
  {
    id: 'dts',
    pattern: '\\.d\\.ts$',
    reason: 'type declarations (incl. generated cli-api.d.ts)',
  },
  {
    id: 'stories',
    pattern: '\\.stories\\.(ts|tsx)$',
    reason: 'storybook files (future-proofing)',
  },
  {
    id: 'build-configs',
    pattern:
      '(^|/)(jest|babel|metro|webpack|rspack|vite|tsup|electron-builder|detox)[^/]*\\.(ts|tsx)$',
    reason: 'build/test tool configs; runtime tamagui.config.ts stays included',
  },
  {
    id: 'icons-generated',
    pattern: '^packages/components/src/primitives/Icon/(react/|Icons\\.tsx$)',
    reason: 'svgr-generated icon components (~1900 files)',
  },
  {
    id: 'locale-generated',
    pattern:
      '^packages/shared/src/locale/(enum/translations\\.ts|localeJsonMap\\.ts)$',
    reason: 'generated by yarn i18n:pull',
  },
  {
    id: 'dev-gallery',
    pattern: '^packages/kit/src/views/Developer/',
    reason: 'dev-only component gallery, not user-facing',
  },
  {
    id: 'preset-networks-data',
    pattern: '^packages/shared/src/config/presetNetworks\\.ts$',
    reason: 'chain-config data-as-code',
  },
  {
    id: 'color-tokens-data',
    pattern: '^packages/components/colors/primitive/(light|dark)\\.ts$',
    reason: 'design-token color tables, zero logic',
  },
  {
    id: 'monero-words-data',
    pattern: '^packages/core/src/chains/xmr/sdkXmr/moneroWords/',
    reason: 'vendored mnemonic wordlist data',
  },
  {
    id: 'emoji-data',
    pattern: '^packages/shared/src/utils/emojiUtils\\.ts$',
    reason: '98% emoji string literals',
  },
];

const GENERATED_MARKER =
  /(auto-?generated|automatically (created|generated)|do not edit|@generated)/i;
// Data-as-code candidates above this size get surfaced for model review at
// batch start; matches the threshold used in the 2026-06 calibration.
const SUSPECT_LINES = 1500;

function parseArgs(argv) {
  const args = { repo: process.cwd() };
  for (let i = 2; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === '--repo') args.repo = argv[(i += 1)];
    else if (a === '--out') args.out = argv[(i += 1)];
    else if (a === '--overrides') args.overrides = argv[(i += 1)];
    else if (a === '--stats') args.stats = true;
    else if (a === '--hash') args.hash = true;
    else if (a === '--suspects') args.suspects = true;
    else {
      console.error(`unknown argument: ${a}`);
      process.exit(2);
    }
  }
  return args;
}

function loadOverrides(path) {
  if (!path) return { disableRules: [], addExclude: [], addIncludeGlobs: [] };
  const o = JSON.parse(readFileSync(path, 'utf8'));
  return {
    disableRules: o.disableRules ?? [],
    addExclude: o.addExclude ?? [],
    addIncludeGlobs: o.addIncludeGlobs ?? [],
  };
}

function main() {
  const args = parseArgs(process.argv);
  const overrides = loadOverrides(args.overrides);

  const unknownRule = overrides.disableRules.find(
    (id) => !BASELINE_RULES.some((r) => r.id === id),
  );
  if (unknownRule) {
    console.error(
      `overrides.disableRules references unknown rule id: ${unknownRule}`,
    );
    process.exit(2);
  }

  const activeRules = BASELINE_RULES.filter(
    (r) => !overrides.disableRules.includes(r.id),
  ).concat(overrides.addExclude);
  const excludeRe = activeRules.map((r) => new RegExp(r.pattern));
  const globs = INCLUDE_GLOBS.concat(overrides.addIncludeGlobs);

  let commit;
  try {
    commit = execFileSync('git', ['rev-parse', 'HEAD'], {
      cwd: args.repo,
      encoding: 'utf8',
    }).trim();
  } catch (e) {
    console.error(
      `--repo "${args.repo}" is not a usable git checkout (stale worktree? run \`git worktree prune\` and re-materialize): ${e.message}`,
    );
    process.exit(2);
  }
  const raw = execFileSync('git', ['ls-files', '--', ...globs], {
    cwd: args.repo,
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  });

  const paths = raw
    .split('\n')
    .filter(Boolean)
    .filter((p) => !excludeRe.some((re) => re.test(p)))
    // Deterministic ordering is the contract the cursor depends on: default
    // Array.sort on strings compares UTF-16 code units — locale- and
    // platform-independent (never use localeCompare or shell `sort` here).
    // Do not rely on git ls-files output order.
    .toSorted();

  const entries = [];
  const suspects = [];
  for (const p of paths) {
    let content;
    try {
      content = readFileSync(join(args.repo, p), 'utf8');
    } catch (e) {
      // Tracked but unreadable (should not happen on a clean checkout);
      // record with 0 lines rather than aborting the whole blueprint.
      console.error(`warn: unreadable ${p}: ${e.message}`);
      entries.push({ path: p, lines: 0 });
    }
    if (typeof content === 'string') {
      let lines = 0;
      for (let i = 0; i < content.length; i += 1) {
        if (content.charCodeAt(i) === 10) lines += 1;
      }
      if (content.length > 0 && !content.endsWith('\n')) lines += 1;
      entries.push({ path: p, lines });

      if (args.suspects) {
        const head = content.split('\n', 5).join('\n');
        if (GENERATED_MARKER.test(head)) {
          suspects.push({
            path: p,
            lines,
            reason: 'generated-marker in header',
          });
        } else if (/(^|\/)[^/]*(test|mock|fixture|spec)[^/]*\//i.test(p)) {
          // A test-looking directory survived the filters — likely a naming
          // variant the exclusion rules don't know yet (e.g. __test-utils__).
          suspects.push({
            path: p,
            lines,
            reason: 'test-like path survived filters',
          });
        } else if (lines > SUSPECT_LINES) {
          suspects.push({
            path: p,
            lines,
            reason: `>${SUSPECT_LINES} lines, check for data-as-code`,
          });
        }
      }
    }
  }

  const jsonl = entries
    .map((e, i) => JSON.stringify({ i, path: e.path, lines: e.lines }))
    .join('\n');
  const manifestHash = createHash('sha256')
    .update(jsonl)
    .digest('hex')
    .slice(0, 16);
  const rulesHash = createHash('sha256')
    .update(JSON.stringify({ globs, rules: activeRules.map((r) => r.pattern) }))
    .digest('hex')
    .slice(0, 16);
  const totalLines = entries.reduce((s, e) => s + e.lines, 0);

  if (args.out) writeFileSync(args.out, `${jsonl}\n`);

  const summary = {
    commit,
    totalFiles: entries.length,
    totalLines,
    manifestHash,
    rulesHash,
    out: args.out ?? null,
  };

  if (args.stats) {
    const byDir = new Map();
    for (const e of entries) {
      const seg = e.path.split('/');
      const key = seg.slice(0, 2).join('/');
      const cur = byDir.get(key) ?? { files: 0, lines: 0 };
      cur.files += 1;
      cur.lines += e.lines;
      byDir.set(key, cur);
    }
    summary.perDir = [...byDir.entries()]
      .map(([dir, v]) => ({ dir, ...v }))
      .toSorted((a, b) => b.lines - a.lines);
  }
  if (args.suspects) {
    summary.suspects = suspects
      .toSorted((a, b) => b.lines - a.lines)
      .slice(0, 60);
    summary.suspectsTotal = suspects.length;
  }

  console.log(
    JSON.stringify(summary, null, args.stats || args.suspects ? 1 : 0),
  );
}

main();
