const DEFI_PORTFOLIO_DETAIL_POSITION_NAME_COLOR = '$textSubdued';
const DEFI_PORTFOLIO_DETAIL_COLUMN_NAME_COLOR = '$textSubdued';

export {
  DEFI_PORTFOLIO_DETAIL_COLUMN_NAME_COLOR,
  DEFI_PORTFOLIO_DETAIL_POSITION_NAME_COLOR,
};
