const { checkCocoaPodsVersions } = require('./podfile');

function createSources({
  activatedVersion = '1.17.0',
  installedVersion = '1.17.0',
  lockfileVersion = '1.17.0',
} = {}) {
  const packageName = 'CocoaPods'.toLowerCase();
  const lockfileKey = 'CocoaPods'.toUpperCase();
  return {
    lockfileSource: `PODS:\n${lockfileKey}: ${lockfileVersion}\n`,
    workflowSource: `
      gem install ${packageName} -v ${installedVersion}
      pod _${activatedVersion}_ install --deployment
    `,
  };
}

describe('CocoaPods version lint', () => {
  it('accepts matching lockfile, install, and activation versions', () => {
    expect(checkCocoaPodsVersions(createSources()).errors).toEqual([]);
  });

  it('rejects a lockfile generated by a different CocoaPods version', () => {
    expect(
      checkCocoaPodsVersions(createSources({ lockfileVersion: '1.16.2' }))
        .errors,
    ).toContain(
      'apps/mobile/ios/Podfile.lock was generated with CocoaPods 1.16.2, but CI activates 1.17.0',
    );
  });

  it('rejects mismatched install and activation versions', () => {
    expect(
      checkCocoaPodsVersions(createSources({ installedVersion: '1.16.2' }))
        .errors,
    ).toContain(
      'CocoaPods install version 1.16.2 does not match activated version 1.17.0',
    );
  });

  it('requires CI to activate an explicit CocoaPods version', () => {
    const sources = createSources();
    sources.workflowSource = sources.workflowSource.replace(
      'pod _1.17.0_ install --deployment',
      'pod install --deployment',
    );

    expect(checkCocoaPodsVersions(sources).errors).toContain(
      '.github/workflows/mobile-dev-shell-ios-simulator.yml must declare exactly one CocoaPods version',
    );
  });
});
