import crypto from 'crypto';

import { getBtcForkNetwork } from '.';

import type { ILocalHistory } from '@onekeyhq/kit-bg/src/dbs/simple/entity/SimpleDbEntityLocalHistory';
import type { IAccountHistoryTx } from '@onekeyhq/shared/types/history';
import { EDecodedTxStatus } from '@onekeyhq/shared/types/tx';

import { EAddressEncodings } from '../../../types';

import {
  getLocalUsedAddressFromLocalPendingTxs,
  transformAddress,
} from './fresh-address';

import type { IBtcBlockbookDerivedInfo, IEncodedTxBtc } from '../types';

const fixtures = [
  {
    xpub: 'ypub6YHeP4xR81KXQzQCgTtmmWM7X9D7NFDhRkHZWPT6yLGxKyF8xqUy5w1yQiL8ff7iC8eErcPr3SEofKtc2rnEtv8L44zNkdJEEkp54U9h4sB',
    networkChainCode: 'btc',
    addressEncoding: EAddressEncodings.P2SH_P2WPKH,
    firstUnusedFreshAddress: '3FjPSQdNCiVwvfJX73QqSbJHpGwFw5HeLD',
    firstUnusedChangeAddress: '3BfJ8PrBrjNbtKVjwL2ZWDxvT65Gge63sy',
    tokens: [
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '37i5rvSfAinZY31sRUqywKsUCDSdo2nrMQ',
        'path': "m/49'/0'/0'/0/0",
        'transfers': 279,
        'decimals': 8,
        'balance': '4000',
        'totalReceived': '5551728',
        'totalSent': '5547728',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3MtQ7Loz2zSGJtZm1CQqYuV5XwjmAdo87c',
        'path': "m/49'/0'/0'/0/1",
        'transfers': 9,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '12600',
        'totalSent': '12600',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3QXWc4kqQzSNSWobWGWQb3uCxX6ugWsgo7',
        'path': "m/49'/0'/0'/0/2",
        'transfers': 12,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '38270',
        'totalSent': '38270',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3EoGhdEQpBne2fAsXUxjesZEB1PRV2J1M1',
        'path': "m/49'/0'/0'/0/3",
        'transfers': 7,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '3600',
        'totalSent': '3600',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3LoUgCKqcTg79Gr8uPgtiNZWUDq33uQorg',
        'path': "m/49'/0'/0'/0/4",
        'transfers': 6,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '2600',
        'totalSent': '2600',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3Lkv9ea9v7gBztguor6RdmbHgtRKNuR9kF',
        'path': "m/49'/0'/0'/0/5",
        'transfers': 8,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '4600',
        'totalSent': '4600',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3MmaJemgGFw3zFFs3AakQyXHK52EsTo2tv',
        'path': "m/49'/0'/0'/0/6",
        'transfers': 5,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '12000',
        'totalSent': '12000',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3F1sG7MbAtJCxRuffcRr6prYV6sCHiQ5ZD',
        'path': "m/49'/0'/0'/0/7",
        'transfers': 2,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '600',
        'totalSent': '600',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3KcpSJb3JBAbWir8u5f9mATfvBP6x6dJYt',
        'path': "m/49'/0'/0'/0/8",
        'transfers': 2,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '547',
        'totalSent': '547',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '33knZqwAPCsAY7dVVQfc8uX7cT519Me5L2',
        'path': "m/49'/0'/0'/0/9",
        'transfers': 13,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '29472',
        'totalSent': '29472',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3LtgsPReTV7uKMk1aJjyFk2m35dhDRA8yA',
        'path': "m/49'/0'/0'/0/10",
        'transfers': 2,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '548',
        'totalSent': '548',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3PzEoXp586s8uAUbxYBu1BdiPmiCAjo1FK',
        'path': "m/49'/0'/0'/0/11",
        'transfers': 2,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '2000',
        'totalSent': '2000',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3BTaJP9vwkMazhwD1SxvHyhCW2uU8zhKGs',
        'path': "m/49'/0'/0'/0/12",
        'transfers': 2,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '546',
        'totalSent': '546',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '32FfJnaq63461DFeBav1MuMUK4oUZ8TjDp',
        'path': "m/49'/0'/0'/0/13",
        'transfers': 2,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '7000',
        'totalSent': '7000',
      },
      {
        'type': 'XPUBAddress',
        'name': '3FjPSQdNCiVwvfJX73QqSbJHpGwFw5HeLD',
        'path': "m/49'/0'/0'/0/14",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3CE1xBbyCAYQu81WtDE4aXQumM3ckuH6a8',
        'path': "m/49'/0'/0'/0/15",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3H8cEqHWxV5kvnaquDE4zkq6RHyQRDiw1o',
        'path': "m/49'/0'/0'/0/16",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '37SaqjmsjvAuv5eqgPi4TVP9dpfRMkUGdH',
        'path': "m/49'/0'/0'/0/17",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '37hQrKZbDL4rkuwJDJtnByUvqkuuXB6bJ8',
        'path': "m/49'/0'/0'/0/18",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '38Qkm1UKxvcWjJ9NU8U4ABV6pmYBSrmpMj',
        'path': "m/49'/0'/0'/0/19",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '33Vo3uea85fqKxb87kHfVjAoyBQndeLjix',
        'path': "m/49'/0'/0'/0/20",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '38qLhMhgLQzSD61FJ6QC8dqezJ4XgPEd5Z',
        'path': "m/49'/0'/0'/0/21",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3CCwho98W6MAYyixcmnZ1b2fqYJZjKiRXA',
        'path': "m/49'/0'/0'/0/22",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3DJf1LWLc5eT1CzvLpXnwBeTva9UWSKnQK',
        'path': "m/49'/0'/0'/0/23",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '35JMHjRHeW5D7dsrAjhmS7BQeWK9PeFmHv',
        'path': "m/49'/0'/0'/0/24",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3Mks9mL2uXgRZjsbZzU6gCwVhpvZh5WzCH',
        'path': "m/49'/0'/0'/0/25",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '35jf3QyJngd662JTa31KnzefTvdTJfCQB5',
        'path': "m/49'/0'/0'/0/26",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '38h3bgQ88AbxLk8gWTc6bnvCpURgoPW3qC',
        'path': "m/49'/0'/0'/0/27",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3AyMMNijUDxYw5HLN6m3eVqmwzYBCY6gHa',
        'path': "m/49'/0'/0'/0/28",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '33PhszjG3eF6KbsK3Cr2ksvjgejCnER2H4',
        'path': "m/49'/0'/0'/0/29",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '35BtQV9LqGoJF9FXXoszdp6qh8mhZrdrTn',
        'path': "m/49'/0'/0'/0/30",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3JqbjiFE3cBf88jcWwnB8iV1iZnP6nJTtd',
        'path': "m/49'/0'/0'/0/31",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '38pxrjJpQaPvf3Rsgco5u8R7LAoVKsQH56',
        'path': "m/49'/0'/0'/0/32",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3EcDqDQekSNWzHUAvzqnpXmpgiXMvvWqqA',
        'path': "m/49'/0'/0'/0/33",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3Q88LfVpRPnb1yotCBnvL566Akq1Z2WKUk',
        'path': "m/49'/0'/0'/1/0",
        'transfers': 2,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '19000',
        'totalSent': '19000',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '35cGftX79KUFeQFL2xDyvmEjd4J2dNgv2f',
        'path': "m/49'/0'/0'/1/1",
        'transfers': 2,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '7800',
        'totalSent': '7800',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '39PUzsQbE5JCQzk1Pr7nxsbcK86C2Tdp4G',
        'path': "m/49'/0'/0'/1/2",
        'transfers': 2,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '9400',
        'totalSent': '9400',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3McWgRekYBKXXTuo3anR9VWhgQkhr5hzme',
        'path': "m/49'/0'/0'/1/3",
        'transfers': 2,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '24400',
        'totalSent': '24400',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3DUUvqq4DFS1fJx1xQQu2CsuPd1Uk4jvxB',
        'path': "m/49'/0'/0'/1/4",
        'transfers': 2,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '21400',
        'totalSent': '21400',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3L1FX6NYjq9fojejPnPSf9iv7sf5Li7uAe',
        'path': "m/49'/0'/0'/1/5",
        'transfers': 2,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '20600',
        'totalSent': '20600',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '38GTkQYiEbYtaXpER5rDpB4mSWukGN6nPQ',
        'path': "m/49'/0'/0'/1/6",
        'transfers': 2,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '17700',
        'totalSent': '17700',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '33rtRbjuZgBPkiV8TrV27cSo9TNxLWetih',
        'path': "m/49'/0'/0'/1/7",
        'transfers': 2,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '16900',
        'totalSent': '16900',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3CW2zRKyUkb3RxUJdnf8V67YDR5YAMRgWw',
        'path': "m/49'/0'/0'/1/8",
        'transfers': 2,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '10700',
        'totalSent': '10700',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3AjmJgUuB7qGA1UqAY1mjsr81tw7FkZUhA',
        'path': "m/49'/0'/0'/1/9",
        'transfers': 2,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '9835',
        'totalSent': '9835',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3431SobSUSCuxkSrbmtxm16Z6MpT9aijvh',
        'path': "m/49'/0'/0'/1/10",
        'transfers': 7,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '16103',
        'totalSent': '16103',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3QBKFV4QoqhDoiQXJ7SsrNGMGXYQXTAZjW',
        'path': "m/49'/0'/0'/1/11",
        'transfers': 3,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '10930',
        'totalSent': '10930',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3Hq2UBZL2CdiQz3rTCFYUtft7FqGfzZmoe',
        'path': "m/49'/0'/0'/1/12",
        'transfers': 3,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '13172',
        'totalSent': '13172',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '36A4uhqAeYoGSsKFBz85hC9StRrzp1JkGf',
        'path': "m/49'/0'/0'/1/13",
        'transfers': 2,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '36154',
        'totalSent': '36154',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '388nZDYt1ZJjp6iuxjKHfvcjuvgkyio6Qd',
        'path': "m/49'/0'/0'/1/14",
        'transfers': 2,
        'decimals': 8,
        'balance': '0',
        'totalReceived': '7493',
        'totalSent': '7493',
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3BfJ8PrBrjNbtKVjwL2ZWDxvT65Gge63sy',
        'path': "m/49'/0'/0'/1/15",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '39g2NzVWumuNqhsmMbskKdN6QroPBZVZ4c',
        'path': "m/49'/0'/0'/1/16",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3DwacdELj9KXqjH56eqwcSP1ycCyy7QS1g',
        'path': "m/49'/0'/0'/1/17",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '34dv197uobZTQxAgYXNiWteguovPn27n78',
        'path': "m/49'/0'/0'/1/18",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3BN26SvGRVmGehnvj5e3KnpeFaoDmhg4Av',
        'path': "m/49'/0'/0'/1/19",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '36T2GzKyy7nmj3Kso3Ub7RSs4dPRW9nCkM',
        'path': "m/49'/0'/0'/1/20",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3CpzXRsqeWhtAk645d2ugni5cyva3LvN84',
        'path': "m/49'/0'/0'/1/21",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3Cx1guCj5bSsky23eXDC6fBFBMCvc9seZM',
        'path': "m/49'/0'/0'/1/22",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3A9TqVHwodX69pLxfWxWow41esVhoJfFo1',
        'path': "m/49'/0'/0'/1/23",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '34e16jBPzCXAPFjbJ8ZKZpcP8Xp3ckHNbT',
        'path': "m/49'/0'/0'/1/24",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '35hEnKvUf5VfQgPeDT7SqNsgQweeFPAe7z',
        'path': "m/49'/0'/0'/1/25",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3AkYQMUHmaBV3rVZLkk8pkkD15Akjiyg8k',
        'path': "m/49'/0'/0'/1/26",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '37e7PVyMc6kuL2Hb8kuHFBHo7wcci7ko6p',
        'path': "m/49'/0'/0'/1/27",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3H9SaEiHSiH4Xsv3KFHVn4b5wN7jFx6oUu',
        'path': "m/49'/0'/0'/1/28",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3JFW7gn4BZ5d5BivmWasRAqmTVp3kEyHA8',
        'path': "m/49'/0'/0'/1/29",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3ERvPX94KdxdNQviZeWnxY8MYWdMCvTvh1',
        'path': "m/49'/0'/0'/1/30",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '32SohtUeqrutckW7e3Wnv9soaXECHhtpMD',
        'path': "m/49'/0'/0'/1/31",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3JgkMyJQKvXYwBWxHv7ebLffV4dGoi4qS6',
        'path': "m/49'/0'/0'/1/32",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3NdVX1fyxdhpnA44Gqqt8kTcrEJSMZKfwb',
        'path': "m/49'/0'/0'/1/33",
        'transfers': 0,
        'decimals': 8,
      },
      {
        'type': 'XPUBAddress',
        'standard': 'XPUBAddress',
        'name': '3KDzxHCFzgFMikmQSR1VLMnhGYiQuoWJop',
        'path': "m/49'/0'/0'/1/34",
        'transfers': 0,
        'decimals': 8,
      },
    ] as IBtcBlockbookDerivedInfo[],
  },
];

describe('BTC - Fresh Address', () => {
  it('should generate correct fresh addresses', async () => {
    for (const f of fixtures) {
      const addresses = await transformAddress({
        network: getBtcForkNetwork(f.networkChainCode),
        xpub: f.xpub,
        addressEncoding: f.addressEncoding,
        derivedInfos: f.tokens,
        localUsedAddressesMap: {},
      });
      expect(addresses).toBeDefined();
      expect(addresses?.fresh.unused[0].address).toBe(
        f.firstUnusedFreshAddress,
      );
      expect(addresses?.change.unused[0].address).toBe(
        f.firstUnusedChangeAddress,
      );
    }
  });
});

describe('getLocalUsedAddressFromLocalPendingTxs', () => {
  const buildHistoryTx = ({
    id,
    txid,
    outputs,
  }: {
    id: string;
    txid: string;
    outputs: IEncodedTxBtc['outputs'];
  }): IAccountHistoryTx => ({
    id,
    decodedTx: {
      txid,
      owner: 'owner',
      signer: 'signer',
      nonce: 0,
      actions: [],
      status: EDecodedTxStatus.Pending,
      networkId: 'btc--0',
      accountId: 'account',
      extraInfo: null,
      encodedTx: {
        inputs: [],
        outputs,
        inputsForCoinSelect: [],
        outputsForCoinSelect: [],
        fee: '1',
        txSize: 0,
      },
    },
  });

  it('should return stable hash for empty pending txs', async () => {
    const { localUsedAddressesHash, localUsedAddressesMap } =
      await getLocalUsedAddressFromLocalPendingTxs({});

    expect(localUsedAddressesMap).toEqual({});
    const expectedHash = crypto.createHash('sha256').update('').digest('hex');
    expect(localUsedAddressesHash).toBe(expectedHash);
  });

  it('should merge outputs, dedupe txIds, and produce deterministic hash', async () => {
    const pendingTxs: ILocalHistory['pendingTxs'] = {
      btc_account: [
        buildHistoryTx({
          id: 'local-1',
          txid: 'chain-1',
          outputs: [
            { address: 'addrA', value: '1000' },
            { address: 'addrB', value: '2000' },
          ],
        }),
        buildHistoryTx({
          id: 'local-2',
          txid: 'chain-2',
          outputs: [
            { address: 'addrA', value: '500' },
            { address: 'addrA', value: '700' },
            { address: 'addrC', value: '3000' },
          ],
        }),
      ],
      btc_account_other: [
        buildHistoryTx({
          id: 'local-3',
          txid: 'chain-3',
          outputs: [
            { address: 'addrB', value: '1500' },
            { address: 'addrD', value: '4000' },
          ],
        }),
        buildHistoryTx({
          id: 'local-4',
          txid: 'chain-3',
          outputs: [{ address: 'addrB', value: '1500' }],
        }),
      ],
    };

    const { localUsedAddressesHash, localUsedAddressesMap } =
      await getLocalUsedAddressFromLocalPendingTxs({
        pendingTxs,
      });

    const expectedMap = {
      addrA: ['chain-1', 'chain-2'],
      addrB: ['chain-1', 'chain-3'],
      addrC: ['chain-2'],
      addrD: ['chain-3'],
    };
    expect(localUsedAddressesMap).toEqual(expectedMap);

    const sortedEntries = Object.entries(expectedMap)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([address, txIds]) => `${address}:${txIds.join(',')}`)
      .join('|');
    const expectedHash = crypto
      .createHash('sha256')
      .update(sortedEntries)
      .digest('hex');
    expect(localUsedAddressesHash).toBe(expectedHash);
  });
});
