export const CUSTOM_INJECTION_AUTO_REVIEW_CONFIG_CHANNEL =
  'onekey@CUSTOM_INJECTION_AUTO_REVIEW_CONFIG';
export const CUSTOM_INJECTION_AUTO_REVIEW_RESULT_CHANNEL =
  'onekey@CUSTOM_INJECTION_AUTO_REVIEW';
export const CUSTOM_INJECTION_RECORDING_COMMAND_CHANNEL =
  'onekey@CUSTOM_INJECTION_RECORDING_COMMAND';
export const CUSTOM_INJECTION_RECORDING_EVENT_CHANNEL =
  'onekey@CUSTOM_INJECTION_RECORDING_EVENT';
