export const ACCOUNT_SELECTOR_IS_OPEN_REFRESH_DELAY = 500;
export const ACCOUNT_SELECTOR_IS_OPEN_VISIBLE_DELAY =
  ACCOUNT_SELECTOR_IS_OPEN_REFRESH_DELAY + 100;
export const ACCOUNT_SELECTOR_REFRESH_DEBOUNCE = 300;
export const ACCOUNT_SELECTOR_CHANGE_ACCOUNT_CLOSE_DRAWER_DELAY = 500;
export const ACCOUNT_SELECTOR_SELECTED_WALLET_DEBOUNCED = 600;
export const ACCOUNT_SELECTOR_EMPTY_VIEW_SHOW_DELAY = 100;
