#!/usr/bin/env node

// Generates packages/shared/src/runtime/version.ts from .env.version (postinstall hook).

const fs = require('fs');
const path = require('path');

const dotenv = require('dotenv');

const repoRoot = path.resolve(__dirname, '..', '..');
const envVersionPath = path.join(repoRoot, '.env.version');
const outPath = path.join(repoRoot, 'packages/shared/src/runtime/version.ts');

const parsed = dotenv.parse(fs.readFileSync(envVersionPath));
const version = parsed.VERSION;
if (!version) {
  throw new Error(`[sync-version] VERSION= not set in ${envVersionPath}`);
}
if (/['\\\r\n]/.test(version)) {
  throw new Error(`[sync-version] VERSION contains illegal char: ${version}`);
}

const banner = '// Auto-generated by development/scripts/sync-version.js';
const note = '// Source of truth: .env.version. Do not edit by hand.';
const next = `${banner}\n${note}\n\nexport const APP_VERSION = '${version}';\n`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
const wrote =
  !fs.existsSync(outPath) || fs.readFileSync(outPath, 'utf8') !== next;
if (wrote) fs.writeFileSync(outPath, next);

console.log(
  wrote
    ? `[sync-version] wrote APP_VERSION=${version} -> ${path.relative(repoRoot, outPath)}`
    : `[sync-version] up to date (APP_VERSION=${version})`,
);
