#!/usr/bin/env node

// Generate packages/shared/src/runtime/version.ts from .env.version.
//
// .env.version is the single source of truth for the app marketing version.
// Historically every build pipeline (desktop main/renderer, mobile babel, cli
// tsup, web/ext webpack) had to load it via dotenv before its bundler ran.
// Some pipelines forgot, which silently produced wrong values: iOS shipped
// "OneKeyWallet/1 (ios-native)" and CLI shipped "OneKeyWallet/unknown
// (cli-node)". The generated TypeScript file removes that fragility because
// any bundler (esbuild, webpack, rspack, metro, tsup, babel) handles a normal
// ts/json import natively — no per-pipeline hooks required.
//
// This file is gitignored and regenerated by the postinstall hook, so it can
// never drift from .env.version.

const fs = require('fs');
const path = require('path');

const repoRoot = path.resolve(__dirname, '..', '..');
const envVersionPath = path.join(repoRoot, '.env.version');
const outPath = path.join(
  repoRoot,
  'packages/shared/src/runtime/version.ts',
);

function readVersion() {
  const raw = fs.readFileSync(envVersionPath, 'utf8');
  const match = raw.match(/^VERSION=(.+)$/m);
  if (!match) {
    throw new Error(
      `[sync-version] VERSION= line not found in ${envVersionPath}`,
    );
  }
  return match[1].trim();
}

function writeVersion(version) {
  const banner = '// Auto-generated by development/scripts/sync-version.js';
  const note = '// Source of truth: .env.version. Do not edit by hand.';
  const body = `export const APP_VERSION = ${JSON.stringify(version)};\n`;
  const next = `${banner}\n${note}\n\n${body}`;

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  if (fs.existsSync(outPath) && fs.readFileSync(outPath, 'utf8') === next) {
    return false;
  }
  fs.writeFileSync(outPath, next);
  return true;
}

const version = readVersion();
const wrote = writeVersion(version);
console.log(
  wrote
    ? `[sync-version] wrote APP_VERSION=${version} -> ${path.relative(repoRoot, outPath)}`
    : `[sync-version] up to date (APP_VERSION=${version})`,
);
