export const POLLING_INTERVAL = 15000;
export const POLLING_INTERVAL_FOR_TOKEN = POLLING_INTERVAL;
export const POLLING_INTERVAL_FOR_NFT = POLLING_INTERVAL;
export const POLLING_INTERVAL_FOR_HISTORY = POLLING_INTERVAL;

export const DEBOUNCE_INTERVAL = 1000;
