// Objective-C API for talking to github.com/ProtonMail/gopenpgp/v3/constants Go package.
//   gobind -lang=objc github.com/ProtonMail/gopenpgp/v3/constants
//
// File is generated by gobind. Do not edit.

#ifndef __Constants_H__
#define __Constants_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Cipher suite names.
 */
FOUNDATION_EXPORT NSString* _Nonnull const ConstantsAES128;
/**
 * Cipher suite names.
 */
FOUNDATION_EXPORT NSString* _Nonnull const ConstantsAES192;
/**
 * Cipher suite names.
 */
FOUNDATION_EXPORT NSString* _Nonnull const ConstantsAES256;
/**
 * ArmorChecksumEnabled defines the default behavior for adding an armor checksum
to an armored message.

If set to true, an armor checksum is added to the message.

If set to false, no armor checksum is added.
 */
FOUNDATION_EXPORT const BOOL ConstantsArmorChecksumEnabled;
/**
 * Constants for armored data.
 */
FOUNDATION_EXPORT NSString* _Nonnull const ConstantsArmorHeaderComment;
/**
 * Constants for armored data.
 */
FOUNDATION_EXPORT const BOOL ConstantsArmorHeaderEnabled;
/**
 * Constants for armored data.
 */
FOUNDATION_EXPORT NSString* _Nonnull const ConstantsArmorHeaderVersion;
/**
 * Cipher suite names.
 */
FOUNDATION_EXPORT NSString* _Nonnull const ConstantsCAST5;
/**
 * Wraps the packet.CipherFunction enum from go-crypto
for go-mobile clients.
int8 type for go-mobile support.
 */
FOUNDATION_EXPORT const int8_t ConstantsCipher3DES;
/**
 * Wraps the packet.CipherFunction enum from go-crypto
for go-mobile clients.
int8 type for go-mobile support.
 */
FOUNDATION_EXPORT const int8_t ConstantsCipherAES128;
/**
 * Wraps the packet.CipherFunction enum from go-crypto
for go-mobile clients.
int8 type for go-mobile support.
 */
FOUNDATION_EXPORT const int8_t ConstantsCipherAES192;
/**
 * Wraps the packet.CipherFunction enum from go-crypto
for go-mobile clients.
int8 type for go-mobile support.
 */
FOUNDATION_EXPORT const int8_t ConstantsCipherAES256;
/**
 * Wraps the packet.CipherFunction enum from go-crypto
for go-mobile clients.
int8 type for go-mobile support.
 */
FOUNDATION_EXPORT const int8_t ConstantsCipherCAST5;
/**
 * Use compression defined by the pgp profile.
 */
FOUNDATION_EXPORT const int8_t ConstantsDefaultCompression;
/**
 * HighSecurity is the high security level.
 */
FOUNDATION_EXPORT const int8_t ConstantsHighSecurity;
/**
 * Use no compression (default).
 */
FOUNDATION_EXPORT const int8_t ConstantsNoCompression;
/**
 * Constants for armored data.
 */
FOUNDATION_EXPORT NSString* _Nonnull const ConstantsPGPMessageHeader;
/**
 * Constants for armored data.
 */
FOUNDATION_EXPORT NSString* _Nonnull const ConstantsPGPSignatureHeader;
/**
 * Constants for armored data.
 */
FOUNDATION_EXPORT NSString* _Nonnull const ConstantsPrivateKeyHeader;
/**
 * Constants for armored data.
 */
FOUNDATION_EXPORT NSString* _Nonnull const ConstantsPublicKeyHeader;
FOUNDATION_EXPORT const long ConstantsSIGNATURE_BAD_CONTEXT;
FOUNDATION_EXPORT const long ConstantsSIGNATURE_FAILED;
FOUNDATION_EXPORT const long ConstantsSIGNATURE_NOT_SIGNED;
FOUNDATION_EXPORT const long ConstantsSIGNATURE_NO_VERIFIER;
FOUNDATION_EXPORT const long ConstantsSIGNATURE_OK;
/**
 * OpenPGP signature types.
int8 type for go-mobile clients.
 */
FOUNDATION_EXPORT const int8_t ConstantsSigTypeBinary;
/**
 * OpenPGP signature types.
int8 type for go-mobile clients.
 */
FOUNDATION_EXPORT const int8_t ConstantsSigTypeCasualCert;
/**
 * OpenPGP signature types.
int8 type for go-mobile clients.
 */
FOUNDATION_EXPORT const int8_t ConstantsSigTypeCertificationRevocation;
/**
 * OpenPGP signature types.
int8 type for go-mobile clients.
 */
FOUNDATION_EXPORT const int8_t ConstantsSigTypeDirectSignature;
/**
 * OpenPGP signature types.
int8 type for go-mobile clients.
 */
FOUNDATION_EXPORT const int8_t ConstantsSigTypeGenericCert;
/**
 * OpenPGP signature types.
int8 type for go-mobile clients.
 */
FOUNDATION_EXPORT const int8_t ConstantsSigTypeKeyRevocation;
/**
 * OpenPGP signature types.
int8 type for go-mobile clients.
 */
FOUNDATION_EXPORT const int8_t ConstantsSigTypePersonaCert;
/**
 * OpenPGP signature types.
int8 type for go-mobile clients.
 */
FOUNDATION_EXPORT const int8_t ConstantsSigTypePositiveCert;
/**
 * OpenPGP signature types.
int8 type for go-mobile clients.
 */
FOUNDATION_EXPORT const int8_t ConstantsSigTypePrimaryKeyBinding;
/**
 * OpenPGP signature types.
int8 type for go-mobile clients.
 */
FOUNDATION_EXPORT const int8_t ConstantsSigTypeSubkeyBinding;
/**
 * OpenPGP signature types.
int8 type for go-mobile clients.
 */
FOUNDATION_EXPORT const int8_t ConstantsSigTypeSubkeyRevocation;
/**
 * OpenPGP signature types.
int8 type for go-mobile clients.
 */
FOUNDATION_EXPORT const int8_t ConstantsSigTypeText;
FOUNDATION_EXPORT NSString* _Nonnull const ConstantsSignatureContextName;
/**
 * StandardSecurity is the default security level.
 */
FOUNDATION_EXPORT const int8_t ConstantsStandardSecurity;
/**
 * Cipher suite names.
 */
FOUNDATION_EXPORT NSString* _Nonnull const ConstantsThreeDES;
/**
 * Cipher suite names.
 */
FOUNDATION_EXPORT NSString* _Nonnull const ConstantsTripleDES;
FOUNDATION_EXPORT NSString* _Nonnull const ConstantsVersion;
/**
 * Use ZIP compression.
 */
FOUNDATION_EXPORT const int8_t ConstantsZIPCompression;
/**
 * Use ZLIB compression.
 */
FOUNDATION_EXPORT const int8_t ConstantsZLIBCompression;

#endif
