#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

INPUT_FILE=$1
START_LINE=`head -n1 $INPUT_FILE`

PATTERN="^(OK)-[[:digit:]]+"

if ![[ "$START_LINE" =~ $PATTERN|^feat\:|^fix\:|^docs\:|^style\:|^refactor\:|^perf\:|^test\:|^chore\: ]]; then
  echo "
Bad commit message, you must add a jira issue key here. https://onekeyhq.atlassian.net/jira/your-work
See example:

  OK-1234: commit message...

Or your commit message must a valid commitizen standard message.https://github.com/commitizen/cz-cli

  feat:        A new feature
  fix:         A bug fix
  docs:        Documentation only changes
  style:       Changes that do not affect the meaning of the code.(white-space, formatting, missing semi-colons, etc)
  refactor:    A code change that neither fixes a bug or adds a feature
  perf:        A code change that improves performance
  test:        Adding missing tests
  chore:       Changes to the build process or auxiliary tools and libraries such as documentationgeneration

See example:
  test: add sum function testcase.
  docs: add sum function document.
  feat: add swap tab for token swap feature.
    "
  exit 1
fi