// Objective-C API for talking to github.com/ProtonMail/gopenpgp/v3/profile Go package.
//   gobind -lang=objc github.com/ProtonMail/gopenpgp/v3/profile
//
// File is generated by gobind. Do not edit.

#ifndef __Profile_H__
#define __Profile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Constants.objc.h"

@class ProfileCustom;

/**
 * Custom type represents a profile for setting algorithm
parameters for generating keys, encrypting data, and
signing data.
Use one of the pre-defined profiles if possible.
i.e., profile.Default(), profile.RFC4880().
 */
@interface ProfileCustom : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field Custom.SetKeyAlgorithm with unsupported type: func(*github.com/ProtonMail/go-crypto/openpgp/packet.Config, int8)

// skipped field Custom.AeadKeyEncryption with unsupported type: *github.com/ProtonMail/go-crypto/openpgp/packet.AEADConfig

// skipped field Custom.S2kKeyEncryption with unsupported type: *github.com/ProtonMail/go-crypto/openpgp/s2k.Config

// skipped field Custom.AeadEncryption with unsupported type: *github.com/ProtonMail/go-crypto/openpgp/packet.AEADConfig

// skipped field Custom.S2kEncryption with unsupported type: *github.com/ProtonMail/go-crypto/openpgp/s2k.Config

// skipped field Custom.CompressionConfiguration with unsupported type: *github.com/ProtonMail/go-crypto/openpgp/packet.CompressionConfig

// skipped field Custom.Hash with unsupported type: crypto.Hash

// skipped field Custom.SignHash with unsupported type: *crypto.Hash

// skipped field Custom.CipherKeyEncryption with unsupported type: github.com/ProtonMail/go-crypto/openpgp/packet.CipherFunction

// skipped field Custom.CipherEncryption with unsupported type: github.com/ProtonMail/go-crypto/openpgp/packet.CipherFunction

// skipped field Custom.CompressionAlgorithm with unsupported type: github.com/ProtonMail/go-crypto/openpgp/packet.CompressionAlgo

/**
 * V6 is a flag to indicate if v6 from the crypto-refresh should be used.
 */
@property (nonatomic) BOOL v6;
/**
 * AllowAllPublicKeyAlgorithms is a flag to disable all checks for deprecated public key algorithms.
 */
@property (nonatomic) BOOL allowAllPublicKeyAlgorithms;
/**
 * DisableIntendedRecipients is a flag to disable the intended recipients pgp feature from the crypto-refresh.
 */
@property (nonatomic) BOOL disableIntendedRecipients;
/**
 * InsecureAllowWeakRSA is a flag to disable checks for weak rsa keys.
 */
@property (nonatomic) BOOL insecureAllowWeakRSA;
/**
 * InsecureAllowDecryptionWithSigningKeys is a flag to enable to decrypt with signing keys for compatibility reasons.
 */
@property (nonatomic) BOOL insecureAllowDecryptionWithSigningKeys;
/**
 * MaxDecompressedMessageSize sets the maximum decompressed messages size that can be read
before throwing an error.
 */
@property (nonatomic) int64_t maxDecompressedMessageSize;
// skipped method Custom.CompressionConfig with unsupported parameter or return types

// skipped method Custom.EncryptionConfig with unsupported parameter or return types

// skipped method Custom.KeyEncryptionConfig with unsupported parameter or return types

// skipped method Custom.KeyGenerationConfig with unsupported parameter or return types

// skipped method Custom.SignConfig with unsupported parameter or return types

@end

/**
 * Default returns a custom profile that support features
that are widely implemented.
 */
FOUNDATION_EXPORT ProfileCustom* _Nullable ProfileDefault(void);

/**
 * RFC4880 returns a custom profile for this library
that conforms with the algorithms in RFC4880.
 */
FOUNDATION_EXPORT ProfileCustom* _Nullable ProfileRFC4880(void);

/**
 * RFC9580 returns a custom profile for this library
that conforms with the algorithms in RFC9580.
 */
FOUNDATION_EXPORT ProfileCustom* _Nullable ProfileRFC9580(void);

#endif
