export enum EAtomNames {
  bannerCloseIdsAtom = 'bannerCloseIdsAtom',
  demoPriceAtom = 'demoPriceAtom',
  demoPriceInfoAtom = 'demoPriceInfoAtom',
  demoPriceNotPersistAtom = 'demoPriceNotPersistAtom',
  // accountIdAtom = 'accountIdAtom',
  settingsPersistAtom = 'settingsPersistAtom',
  settingsAtom = 'settingsAtom',
  devSettingsPersistAtom = 'devSettingsPersistAtom',
  currencyPersistAtom = 'currencyPersistAtom',
  settingsLastActivityAtom = 'settingsLastActivityAtom',
  cloudBackupPersistAtom = 'cloudBackupPersistAtom',
  cloudBackupStatusAtom = 'cloudBackupStatusAtom',
  cloudBackupExitPreventAtom = 'cloudBackupExitPreventAtom',
  passwordAtom = 'passwordAtom',
  passwordPromptPromiseTriggerAtom = 'passwordPromptPromiseTriggerAtom',
  passwordPersistAtom = 'passwordPersistAtom',
  jotaiContextStoreMapAtom = 'jotaiContextStoreMapAtom',
  addressBookPersistAtom = 'addressBookPersistAtom',
  hardwareUiStateAtom = 'hardwareUiStateAtom',
  hardwareUiStateCompletedAtom = 'hardwareUiStateCompletedAtom',
  hardwareWalletXfpStatusAtom = 'hardwareWalletXfpStatusAtom',
  // firmwareUpdatesDetectStatusAtom is reserved for firmwareUpdatesDetectStatusPersistAtom
  firmwareUpdatesDetectStatusPersistAtom = 'firmwareUpdatesDetectStatusPersistAtom', // persist
  firmwareUpdateStepInfoAtom = 'firmwareUpdateStepInfoAtom',
  firmwareUpdateRetryAtom = 'firmwareUpdateRetryAtom',
  firmwareUpdateWorkflowRunningAtom = 'firmwareUpdateWorkflowRunningAtom',
  firmwareUpdateDevSettingsPersistAtom = 'firmwareUpdateDevSettingsPersistAtom',
  firmwareUpdateResultVerifyAtom = 'firmwareUpdateResultVerifyAtom',
  notificationsDevSettingsPersistAtom = 'notificationsDevSettingsPersistAtom',
  appUpdatePersistAtom = 'appUpdatePersistAtom',
  spotlightPersistAtom = 'spotlightPersistAtom',
  onboardingConnectWalletLoadingAtom = 'onboardingConnectWalletLoadingAtom',
  onboardingCloudBackupListRefreshAtom = 'onboardingCloudBackupListRefreshAtom',
  inAppNotificationAtom = 'inAppNotificationAtom',
  v4migrationAtom = 'v4migrationAtom',
  v4migrationPersistAtom = 'v4migrationPersistAtom',
  accountIsAutoCreatingAtom = 'accountIsAutoCreatingAtom',
  indexedAccountAddressCreationStateAtom = 'indexedAccountAddressCreationStateAtom',
  accountManualCreatingAtom = 'accountManualCreatingAtom',
  galleryPersistAtom = 'galleryPersistAtom',
  activeAccountValueAtom = 'activeAccountValueAtom',
  settingsValuePersistAtom = 'settingsValuePersistAtom',
  settingsTronRentalPersistAtom = 'settingsTronRentalPersistAtom',
  appSideBarStatusAtom = 'appSideBarStatusAtom',
  // notificationsAtom, notificationsPersistAtom is reserved for notificationsPersistAtom
  notificationsAtom = 'notificationsAtom', // persist
  notificationsReadedAtom = 'notificationsReadedAtom',
  notificationStatusAtom = 'notificationStatusAtom',
  // prime
  primePersistAtom = 'primePersistAtom',
  primeCloudSyncPersistAtom = 'primeCloudSyncPersistAtom',
  primeMasterPasswordPersistAtom = 'primeMasterPasswordPersistAtom',
  primeServerMasterPasswordStatusAtom = 'primeServerMasterPasswordStatusAtom',
  primeInitAtom = 'primeInitAtom',
  primeLoginDialogAtom = 'primeLoginDialogAtom',
  primeTransferAtom = 'primeTransferAtom',
  keylessDialogAtom = 'keylessDialogAtom',
  accountSelectorAccountsListIsLoadingAtom = 'accountSelectorAccountsListIsLoadingAtom',
  accountSelectorStatusAtom = 'accountSelectorStatusAtom',
  allNetworksPersistAtom = 'allNetworksPersistAtom',
  desktopBluetoothAtom = 'desktopBluetoothAtom',
  hardwareForceTransportAtom = 'hardwareForceTransportAtom',
  // perps
  perpsActiveAccountAtom = 'perpsActiveAccountAtom',
  perpsActiveAccountRefreshHookAtom = 'perpsActiveAccountRefreshHookAtom',
  perpsActiveAccountSummaryAtom = 'perpsActiveAccountSummaryAtom',
  perpsActiveAccountStatusInfoAtom = 'perpsActiveAccountStatusInfoAtom',
  perpsAccountLoadingInfoAtom = 'perpsAccountLoadingInfoAtom',
  perpsActiveAssetAtom = 'perpsActiveAssetAtom',
  perpsActiveAssetCtxAtom = 'perpsActiveAssetCtxAtom',
  perpsActiveAssetDataAtom = 'perpsActiveAssetDataAtom',
  perpsActiveOrderBookOptionsAtom = 'perpsActiveOrderBookOptionsAtom',
  perpsCustomSettingsAtom = 'perpsCustomSettingsAtom',
  perpsTradingPreferencesAtom = 'perpsTradingPreferencesAtom',
  perpsCommonConfigPersistAtom = 'perpsCommonConfigPersistAtom',
  perpsUserConfigPersistAtom = 'perpsUserConfigPersistAtom',
  perpsNetworkStatusAtom = 'perpsNetworkStatusAtom',
  perpsDepositNetworksAtom = 'perpsDepositNetworksAtom',
  perpsDepositTokensAtom = 'perpsDepositTokensAtom',
  perpsWebSocketReadyStateAtom = 'perpsWebSocketReadyStateAtom',
  perpsTradesHistoryRefreshHookAtom = 'perpsTradesHistoryRefreshHookAtom',
  perpsTradesHistoryDataAtom = 'perpsTradesHistoryDataAtom',
  perpsCandlesWebviewReloadHookAtom = 'perpsCandlesWebviewReloadHookAtom',
  perpsCandlesWebviewMountedAtom = 'perpsCandlesWebviewMountedAtom',
  perpsWebSocketDataUpdateTimesAtom = 'perpsWebSocketDataUpdateTimesAtom',
  perpTokenSelectorConfigPersistAtom = 'perpTokenSelectorConfigPersistAtom',
  perpsDepositOrderAtom = 'perpsDepositOrderAtom',
  perpsLastUsedLeverageAtom = 'perpsLastUsedLeverageAtom',
  perpsLayoutStateAtom = 'perpsLayoutStateAtom',
  // network doctor
  networkDoctorStateAtom = 'networkDoctorStateAtom',

  // swap
  swapProJumpTokenAtom = 'swapProJumpTokenAtom',
  // market
  marketSelectedTabAtom = 'marketSelectedTabAtom',
}
export type IAtomNameKeys = keyof typeof EAtomNames;
export const atomsConfig: Partial<
  Record<IAtomNameKeys, { deepCompare?: boolean }>
> = {
  [EAtomNames.notificationsAtom]: {
    deepCompare: true,
  },
};
