name: Build Native iOS Release CI

on:
  workflow_run:
    workflows:
      - daily_build_release
    types:
      - completed
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
          scope: '@onekeyhq'

      - name: Setup keys secret
        run: |
          echo ${{ secrets.IOS_KEYS_ENV }} | base64 -d > packages/app/ios/OneKeyWallet/RNBridge/NFCENV.m

      - name: Setup Expo
        uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true

      - name: 'Setup ENV'
        run: |
          echo "ActionTriggerBy = ${{ github.event.action }} / ${{ github.event_name }}"

          # Generate build number ------- start
          DATE=`date "+%Y%m%d"`
          run_number=$(($workflow_run_number % 100))
          run_number=$(printf "%02d" $run_number)
          build_number="${DATE}${run_number}"
          echo '$build_number='$build_number
          echo "BUILD_NUMBER=$build_number" >> $GITHUB_ENV
          # Generate build number ------- end

        env:
          workflow_run_number: ${{ github.event.workflow_run.run_number}}

      - name: Dotenv Action
        id: dotenv
        uses: falti/dotenv-action@v0.2.7
        with:
          path: .env.version

      - name: Modify info.plist
        uses: OneKeyHQ/onekey-github-actions/build-plist-edit@main
        with:
          buildNumber: ${{ env.BUILD_NUMBER }}
          versionName: ${{ steps.dotenv.outputs.version }}
          projectName: OneKeyWallet
          dir: ./packages/app
          
      - name: Build on EAS
        run: |
          cd packages/app
          npx eas-cli build --profile=production --platform ios --non-interactive --no-wait > eas-build.log
