export enum EAppEventBusNames {
  ConfirmAccountSelected = 'ConfirmAccountSelected',
  LocalSystemTimeInvalid = 'LocalSystemTimeInvalid',
  LocalSystemTimeStatusChanged = 'LocalSystemTimeStatusChanged',
  WalletClear = 'WalletClear',
  WalletUpdate = 'WalletUpdate',
  WalletRemove = 'WalletRemove',
  WalletRename = 'WalletRename',
  AccountUpdate = 'AccountUpdate',
  AccountRemove = 'AccountRemove',
  AddDBAccountsToWallet = 'AddDBAccountsToWallet',
  RenameDBAccounts = 'RenameDBAccounts',
  CloseCurrentBrowserTab = 'CloseCurrentBrowserTab',
  DAppConnectUpdate = 'DAppConnectUpdate',
  OnSwitchDAppNetwork = 'OnSwitchDAppNetwork',
  DAppNetworkUpdate = 'DAppNetworkUpdate',
  DAppLastFocusUrlUpdate = 'DAppLastFocusUrlUpdate',
  SyncDappAccountToHomeAccount = 'SyncDappAccountToHomeAccount',
  GlobalDeriveTypeUpdate = 'GlobalDeriveTypeUpdate',
  NetworkDeriveTypeChanged = 'NetworkDeriveTypeChanged',
  AccountSelectorSelectedAccountUpdate = 'AccountSelectorSelectedAccountUpdate',
  FinalizeWalletSetupStep = 'FinalizeWalletSetupStep',
  FinalizeWalletSetupError = 'FinalizeWalletSetupError',
  WalletConnectOpenModal = 'WalletConnectOpenModal',
  WalletConnectCloseModal = 'WalletConnectCloseModal',
  WalletConnectModalState = 'WalletConnectModalState',
  WalletConnectConnectSuccess = 'WalletConnectConnectSuccess',
  WalletConnectConnectError = 'WalletConnectConnectError',
  ShowDialogLoading = 'ShowDialogLoading',
  HideDialogLoading = 'HideDialogLoading',
  ShowToast = 'ShowToast',
  ShowAirGapQrcode = 'ShowAirGapQrcode',
  HideAirGapQrcode = 'HideAirGapQrcode',
  RealmInit = 'RealmInit',
  V4RealmInit = 'V4RealmInit',
  SyncDeviceLabelToWalletName = 'SyncDeviceLabelToWalletName',
  UpdateWalletAvatarByDeviceSerialNo = 'UpdateWalletAvatarByDeviceSerialNo',
  BatchCreateAccount = 'BatchCreateAccount',
  SDKGetAllNetworkAddressesStart = 'SDKGetAllNetworkAddressesStart',
  SDKGetAllNetworkAddressesEnd = 'SDKGetAllNetworkAddressesEnd',
  ExtensionContextMenuUpdate = 'ExtensionContextMenuUpdate',
  ShowFirmwareUpdateFromBootloaderMode = 'ShowFirmwareUpdateFromBootloaderMode',
  ShowFirmwareUpdateForce = 'ShowFirmwareUpdateForce',
  BeginFirmwareUpdate = 'BeginFirmwareUpdate', // notification begin hardware update, stop hardware progressing
  FinishFirmwareUpdate = 'FinishFirmwareUpdate',
  LoadWebEmbedWebView = 'LoadWebEmbedWebView',
  LoadWebEmbedWebViewComplete = 'LoadWebEmbedWebViewComplete',
  HardwareVerifyAfterDeviceConfirm = 'HardwareVerifyAfterDeviceConfirm',
  SwitchMarketHomeTab = 'SwitchMarketHomeTab',
  SwitchWalletHomeTab = 'SwitchWalletHomeTab',
  RefreshMarketWatchList = 'RefreshMarketWatchList',
  RefreshCustomRpcList = 'RefreshCustomRpcList',
  ClearLocalHistoryPendingTxs = 'ClearLocalHistoryPendingTxs',
  TxFeeInfoChanged = 'TxFeeInfoChanged',
  SignatureConfirmContainerMounted = 'SignatureConfirmContainerMounted',
  CloseHardwareUiStateDialogManually = 'CloseHardwareUiStateDialogManually',
  HardCloseHardwareUiStateDialog = 'CloseHardwareUiStateDialog',
  HistoryTxStatusChanged = 'HistoryTxStatusChanged',
  LocalPendingTxConfirmed = 'LocalPendingTxConfirmed',
  DeFiPositionRefreshed = 'DeFiPositionRefreshed',
  EstimateTxFeeRetry = 'estimateTxFeeRetry',
  GasAccountSubmitRetryScheduled = 'gasAccountSubmitRetryScheduled',
  GasAccountSubmitRetryCleared = 'gasAccountSubmitRetryCleared',
  // TokenList cells Phase-2 BG frame transport (D2=A hybrid push + PULL). The two
  // events are kept separate so the structure (low-frequency, generation-guard)
  // and valuation (per-tick, version-gap) channels can be guarded independently.
  TokenListStructureFrame = 'TokenListStructureFrame',
  TokenListValuationFrame = 'TokenListValuationFrame',
  // TokenList cells Phase-2 risky frame (design 2026-06-16 §R0). Full idempotent
  // risky-token snapshot for an owner with its OWN monotonic version (independent
  // of structure/valuation). Small + low-frequency -> PUSH; never diffed.
  TokenListRiskyFrame = 'TokenListRiskyFrame',
  TabListStateUpdate = 'TabListStateUpdate',
  RefreshTokenList = 'RefreshTokenList',
  RefreshHistoryList = 'RefreshHistoryList',
  RefreshBookmarkList = 'RefreshBookmarkList',
  InvalidateDiscoveryHomeBookmarksPrefetch = 'InvalidateDiscoveryHomeBookmarksPrefetch',
  RefreshApprovalList = 'RefreshApprovalList',
  AccountDataUpdate = 'AccountDataUpdate',
  AccountValueUpdate = 'AccountValueUpdate',
  onDragBeginInListView = 'onDragBeginInListView',
  onDragEndInListView = 'onDragEndInListView',
  SidePanel_BgToUI = 'SidePanel_BgToUI',
  SidePanel_UIToBg = 'SidePanel_UIToBg',
  SwapQuoteEvent = 'SwapQuoteEvent',
  ShowSystemDiskFullWarning = 'ShowSystemDiskFullWarning',
  ShowLinuxBundleUdevGuide = 'ShowLinuxBundleUdevGuide',
  SwapTxHistoryStatusUpdate = 'SwapTxHistoryStatusUpdate',
  // Fired after the swap history store is mutated in a way the pending-status
  // refresh key cannot detect (e.g. clearing finished orders), so list views
  // re-fetch instead of showing stale rows.
  RefreshSwapHistoryList = 'RefreshSwapHistoryList',
  SwapApprovingSuccess = 'SwapApprovingSuccess',
  SwapSpeedApprovingReset = 'SwapSpeedApprovingReset',
  SwapSpeedBalanceUpdate = 'SwapSpeedBalanceUpdate',
  SwapSpeedBuildTxSuccess = 'SwapSpeedBuildTxSuccess',
  SwapStockTokenSelected = 'SwapStockTokenSelected',
  AddedCustomNetwork = 'AddedCustomNetwork',
  ShowFindInWebPage = 'ShowFindInWebPage',
  ChangeTokenDetailTabVerticalScrollEnabled = 'ChangeTokenDetailTabVerticalScrollEnabled',
  RefreshNetInfo = 'RefreshNetInfo',
  ShowSwitchAccountSelector = 'ShowSwitchAccountSelector',
  PrimeLoginInvalidToken = 'PrimeLoginInvalidToken',
  PrimeExceedDeviceLimit = 'PrimeExceedDeviceLimit',
  PrimeDeviceLogout = 'PrimeDeviceLogout',
  PrimeMasterPasswordInvalid = 'PrimeMasterPasswordInvalid',
  PrimeTransferDataReceived = 'PrimeTransferDataReceived',
  PrimeTransferForceExit = 'PrimeTransferForceExit',
  PrimeTransferCancel = 'PrimeTransferCancel',
  CreateAddressByDialog = 'CreateAddressByDialog',
  CheckAddressBeforeSending = 'CheckAddressBeforeSending',
  HideTabBar = 'HideTabBar',
  RequestHardwareUIDialog = 'RequestHardwareUIDialog',
  ShowThirdPartyHardwarePermissionDialog = 'ShowThirdPartyHardwarePermissionDialog',
  RequestDeviceInBootloaderForWebDevice = 'RequestDeviceInBootloaderForWebDevice',
  RequestDeviceForSwitchFirmwareWebDevice = 'RequestDeviceForSwitchFirmwareWebDevice',
  EnabledNetworksChanged = 'EnabledNetworksChanged',
  CheckWalletBackupStatus = 'CheckWalletBackupStatus',
  doubleConfirmTxFeeInfo = 'doubleConfirmTxFeeInfo',
  HardwareFeaturesUpdate = 'HardwareFeaturesUpdate',
  UnlockApp = 'UnlockApp',
  LockApp = 'LockApp',
  // AccountNameChanged = 'AccountNameChanged',
  // CurrencyChanged = 'CurrencyChanged',
  // BackupRequired = 'BackupRequired',
  // NotificationStatusChanged = 'NotificationStatusChanged',
  // StoreInitedFromPersistor = 'StoreInitedFromPersistor',
  // Unlocked = 'Unlocked',
  // HttpServerRequest = 'HttpServerRequest',
  AddressBookUpdate = 'AddressBookUpdate',
  ClearStorageOnExtension = 'ClearStorageOnExtension',
  SupabaseStorageCacheCleared = 'SupabaseStorageCacheCleared',
  MarketWSDataUpdate = 'MarketWSDataUpdate',
  MarketWatchlistOnlyChanged = 'MarketWatchlistOnlyChanged',
  SettingsSearchResult = 'SettingsSearchResult',
  DesktopBleRepairRequired = 'DesktopBleRepairRequired',
  ShowHardwareErrorDialog = 'ShowHardwareErrorDialog',
  SwapPanelDismissKeyboard = 'SwapPanelDismissKeyboard',
  ShowFallbackUpdateDialog = 'ShowFallbackUpdateDialog',
  // Background → foreground signal: an update was discovered mid-session and
  // its server strategy is auto (silent/seamless) or it is a rollback, so the
  // foreground should kick off the real byte transfer. The background keeps the
  // status at `notify` and only emits this event — it cannot pull bytes nor
  // advance the status itself. The native download (BundleUpdate.downloadBundle,
  // with headers/retry) lives exclusively in the foreground useDownloadPackage
  // hook, whose serviceAppUpdate.downloadPackage() flips `notify` →
  // `downloadPackage`. This event bridges the two runtimes.
  StartAutoDownloadUpdate = 'StartAutoDownloadUpdate',
  PendingInstallTaskProcessFinished = 'PendingInstallTaskProcessFinished',
  HomePageReady = 'HomePageReady',
  ShowNotificationViewDialog = 'ShowNotificationViewDialog',
  ShowNotificationPageNavigation = 'ShowNotificationPageNavigation',
  ShowNotificationInDappPage = 'ShowNotificationInDappPage',
  ShowNotificationInWebViewOverlay = 'ShowNotificationInWebViewOverlay',
  UpdateNotificationBadge = 'UpdateNotificationBadge',
  HyperliquidDataUpdate = 'HyperliquidDataUpdate',
  HyperliquidConnectionChange = 'HyperliquidConnectionChange',
  PerpsWebSocketRecovered = 'PerpsWebSocketRecovered',
  PerpSwitchActiveInstrument = 'PerpSwitchActiveInstrument',
  BtcFreshAddressUpdated = 'BtcFreshAddressUpdated',
  BtcFreshAddressConnectDappRejected = 'BtcFreshAddressConnectDappRejected',
  BtcFindAddressUpdated = 'BtcFindAddressUpdated',
  ClientLogUploadProgress = 'ClientLogUploadProgress',
  SwitchDiscoveryTabInNative = 'SwitchDiscoveryTabInNative',
  SwitchEarnMode = 'SwitchEarnMode',
  SwitchEarnTab = 'SwitchEarnTab',
  SwitchTabBar = 'SwitchTabBar',
  PushPageInTabletDetailView = 'PushPageInTabletDetailView',
  PushModalPageInTabletDetailView = 'PushModalPageInTabletDetailView',
  CleanTokenDetailInTabletDetailView = 'CleanTokenDetailInTabletDetailView',
  MarketHomePageEnter = 'MarketHomePageEnter',
  MarketWatchListV2Changed = 'MarketWatchListV2Changed',
  SwapLimitOrderBuildSuccess = 'SwapLimitOrderBuildSuccess',
  RefreshNativeTokenInfo = 'RefreshNativeTokenInfo',
  ShowInAppPushNotification = 'ShowInAppPushNotification',
  ExecuteNotificationCommand = 'ExecuteNotificationCommand',
  ShowRookieShare = 'ShowRookieShare',
  CreateNewBrowserTab = 'CreateNewBrowserTab',
  ClearSavedBrowserActiveTab = 'ClearSavedBrowserActiveTab',
  NavigateModalFromBackgroundThread = 'NavigateModalFromBackgroundThread',
  TrayActionWillNavigate = 'TrayActionWillNavigate',
  MemoryPressureWarning = 'MemoryPressureWarning',
}
